{
  "hash": "6e35359452e4fb874e166b63adb018da",
  "result": {
    "markdown": "# Intro to MLM and the Null Model\n\n**Data for this chapter:** `hsbmerged.csv`\n\nThis week we use a larger version of the HSB dataset from 1988. Same structure as before: students nested within schools. This is the same dataset Garson uses in Chapter 3, so you can recreate what he has as well.\n\n## Load some packages to help with the analysis and data management\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'ggplot2' was built under R version 4.5.2\n```\n:::\n\n```{.r .cell-code}\nlibrary(Hmisc)     # label()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'Hmisc' was built under R version 4.5.2\n```\n:::\n\n```{.r .cell-code}\nlibrary(lme4)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'lme4' was built under R version 4.5.2\n```\n:::\n\n```{.r .cell-code}\nlibrary(lmerTest)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'lmerTest' was built under R version 4.5.2\n```\n:::\n:::\n\n\n`Hmisc` is new here. We want it for two things: `label()`, which attaches a description to a variable, and its own version of `describe()`, which reports more detail than the one in `psych`.\n\n::: {.callout-warning}\n## Package conflicts\n`Hmisc` and `dplyr` both define functions named `summarize` and `src`. Loading `Hmisc` after the tidyverse means its versions win, and you may see masking messages at load. If a tidyverse function starts behaving oddly, call it explicitly as `dplyr::summarize()`.\n:::\n\n## Load in the data and use `glimpse` to summarize the structure\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhsb <- read_csv(\"hsbmerged.csv\")\n\nglimpse(hsb)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 7,185\nColumns: 11\n$ schoolid <dbl> 1224, 1224, 1224, 1224, 1224, 1224, 1224, 1224, 1224, 1224, 1…\n$ minority <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0…\n$ female   <dbl> 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1…\n$ ses      <dbl> -1.528, -0.588, -0.528, -0.668, -0.158, 0.022, -0.618, -0.998…\n$ mathach  <dbl> 5.876, 19.708, 20.349, 8.781, 17.898, 4.583, -2.832, 0.523, 1…\n$ size     <dbl> 842, 842, 842, 842, 842, 842, 842, 842, 842, 842, 842, 842, 8…\n$ sector   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ pracad   <dbl> 0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0…\n$ disclim  <dbl> 1.597, 1.597, 1.597, 1.597, 1.597, 1.597, 1.597, 1.597, 1.597…\n$ himinty  <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ meanses  <dbl> -0.428, -0.428, -0.428, -0.428, -0.428, -0.428, -0.428, -0.42…\n```\n:::\n:::\n\n\n7,185 students across 160 schools. `mathach` is our outcome, a standardized math achievement score, and `schoolid` identifies the school each student attends. That second variable is what makes multilevel modeling possible here.\n\n## Quick data cleaning and coding tips\n\n### The `summary` command from base R is a quick and easy way to explore a new dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(hsb)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    schoolid       minority          female            ses            \n Min.   :1224   Min.   :0.0000   Min.   :0.0000   Min.   :-3.7580000  \n 1st Qu.:3020   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:-0.5380000  \n Median :5192   Median :0.0000   Median :1.0000   Median : 0.0020000  \n Mean   :5278   Mean   :0.2747   Mean   :0.5282   Mean   : 0.0001434  \n 3rd Qu.:7342   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.: 0.6020000  \n Max.   :9586   Max.   :1.0000   Max.   :1.0000   Max.   : 2.6920000  \n    mathach            size          sector           pracad      \n Min.   :-2.832   Min.   : 100   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.: 7.275   1st Qu.: 565   1st Qu.:0.0000   1st Qu.:0.3200  \n Median :13.131   Median :1016   Median :0.0000   Median :0.5300  \n Mean   :12.748   Mean   :1057   Mean   :0.4931   Mean   :0.5345  \n 3rd Qu.:18.317   3rd Qu.:1436   3rd Qu.:1.0000   3rd Qu.:0.7000  \n Max.   :24.993   Max.   :2713   Max.   :1.0000   Max.   :1.0000  \n    disclim           himinty        meanses         \n Min.   :-2.4160   Min.   :0.00   Min.   :-1.188000  \n 1st Qu.:-0.8170   1st Qu.:0.00   1st Qu.:-0.317000  \n Median :-0.2310   Median :0.00   Median : 0.038000  \n Mean   :-0.1319   Mean   :0.28   Mean   : 0.006138  \n 3rd Qu.: 0.4600   3rd Qu.:1.00   3rd Qu.: 0.333000  \n Max.   : 2.7560   Max.   :1.00   Max.   : 0.831000  \n```\n:::\n:::\n\n\nSummary gives you a quick, high-level look at every variable in a dataset. It is also useful for your own records: copy and paste it into a Word file and you have something to refer back to.\n\nRead it critically, though. Every column here gets a mean and quartiles, including `sector`, `female`, and `minority`, which are categories rather than quantities. The mean of `sector` is the proportion of students in one sector, which is mildly useful, but its quartiles are meaningless. This is the same issue from Chapter 1, and we are about to fix it.\n\n### Let's give some variables a label\n\nNow, data cleaning and coding. We will apply labels to two things: the variables themselves, and the values within a given variable. Both are good practice for keeping your data readable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlabel(hsb$mathach) = \"Std. Math Score\"\nlabel(hsb$sector) = \"School Sector\"\n\nstr(hsb$sector)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n 'labelled' num [1:7185] 0 0 0 0 0 0 0 0 0 0 ...\n - attr(*, \"label\")= chr \"School Sector\"\n```\n:::\n:::\n\n\nThe `str()` output now shows the label attached to the variable. This carries through to `Hmisc::describe()` output and to some plotting functions, which means a table six months from now still says \"Std. Math Score\" rather than `mathach`.\n\n### Let's create a factor version of `sector` and label its values\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhsb.clean <- hsb %>%\n  mutate(.,\n         sector.factor = as_factor(sector),\n         female.factor = as_factor(female),\n         minority.factor = as_factor(minority))\n\nlevels(hsb.clean$sector.factor) = c(\"Public\", \"Parochial\")\nlevels(hsb.clean$female.factor) = c(\"Male\", \"Female\")\nlevels(hsb.clean$minority.factor) = c(\"Non-Minority\", \"Minority\")\n\nstr(hsb.clean$sector.factor)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Factor w/ 2 levels \"Public\",\"Parochial\": 1 1 1 1 1 1 1 1 1 1 ...\n```\n:::\n:::\n\n\nTwo steps here, and it is worth separating them. `as_factor()` converts the numeric variable into a factor, so R treats it as a category. Assigning to `levels()` then renames those categories from 0 and 1 into words.\n\nOrder matters when you assign levels this way. The names are applied in the order R already has the levels in, so `c(\"Public\", \"Parochial\")` assumes 0 comes first. Always check the result:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(hsb.clean$sector.factor)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   Public Parochial \n     3642      3543 \n```\n:::\n:::\n\n\n3,642 public and 3,543 Parochial. If those counts had come out reversed from what you expected, the labels went on backwards, and every result from here forward would be silently mislabeled.\n\n### Run `summary` again and notice how it handles factors\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(hsb.clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    schoolid       minority          female            ses            \n Min.   :1224   Min.   :0.0000   Min.   :0.0000   Min.   :-3.7580000  \n 1st Qu.:3020   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:-0.5380000  \n Median :5192   Median :0.0000   Median :1.0000   Median : 0.0020000  \n Mean   :5278   Mean   :0.2747   Mean   :0.5282   Mean   : 0.0001434  \n 3rd Qu.:7342   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.: 0.6020000  \n Max.   :9586   Max.   :1.0000   Max.   :1.0000   Max.   : 2.6920000  \n    mathach            size          sector           pracad      \n Min.   :-2.832   Min.   : 100   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.: 7.275   1st Qu.: 565   1st Qu.:0.0000   1st Qu.:0.3200  \n Median :13.131   Median :1016   Median :0.0000   Median :0.5300  \n Mean   :12.748   Mean   :1057   Mean   :0.4931   Mean   :0.5345  \n 3rd Qu.:18.317   3rd Qu.:1436   3rd Qu.:1.0000   3rd Qu.:0.7000  \n Max.   :24.993   Max.   :2713   Max.   :1.0000   Max.   :1.0000  \n    disclim           himinty        meanses            sector.factor \n Min.   :-2.4160   Min.   :0.00   Min.   :-1.188000   Public   :3642  \n 1st Qu.:-0.8170   1st Qu.:0.00   1st Qu.:-0.317000   Parochial:3543  \n Median :-0.2310   Median :0.00   Median : 0.038000                   \n Mean   :-0.1319   Mean   :0.28   Mean   : 0.006138                   \n 3rd Qu.: 0.4600   3rd Qu.:1.00   3rd Qu.: 0.333000                   \n Max.   : 2.7560   Max.   :1.00   Max.   : 0.831000                   \n female.factor     minority.factor\n Male  :3390   Non-Minority:5211  \n Female:3795   Minority    :1974  \n                                  \n                                  \n                                  \n                                  \n```\n:::\n:::\n\n\nCompare this to the earlier output. The factor versions of the variables no longer report meaningless means and quartiles. Instead they report counts per category, which is what you actually want to know. Same data, same function, but R now understands what kind of variable it is looking at.\n\n## Exploring our outcome, math achievement\n\nNow let's look at `mathach` using the `describe` function from the `Hmisc` package:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndescribe(hsb.clean$mathach)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nhsb.clean$mathach : Std. Math Score \n       n  missing distinct     Info     Mean  pMedian      Gmd      .05 \n    7185        0     6031        1    12.75    12.85     7.91    1.210 \n     .10      .25      .50      .75      .90      .95 \n   3.301    7.275   13.131   18.317   22.016   23.123 \n\nlowest : -2.832 -2.83  -2.721 -2.658 -2.657, highest: 24.677 24.707 24.812 24.869 24.993\n```\n:::\n:::\n\n\n`Hmisc::describe()` reports more than the `psych` version: distinct values, several percentiles, and the five lowest and highest observations. That last part is a quiet outlier check. If the highest values were 24, 25, and 9999, you would see it here.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(hsb.clean$mathach,\n     main = \"Distribution of Math Achievement Scores\",\n     sub = \"N = 7,185. Students from the High School and Beyond Survey (1988).\",\n     xlab = \"Standardized Math Achievement Score\")\n```\n\n::: {.cell-output-display}\n![Distribution of math achievement scores.](03-null-model_files/figure-html/fig-mathach-1.png){#fig-mathach width=672}\n:::\n:::\n\n\nThis histogram describes students in general, which is useful but hides the thing we actually care about. The question motivating multilevel modeling is whether *schools* differ. One quick way to see it is to plot school averages instead of individual scores:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschool_means <- hsb.clean %>%\n  group_by(schoolid) %>%\n  dplyr::summarize(school_mean = mean(mathach, na.rm = TRUE))\n\nhist(school_means$school_mean,\n     main = \"School Average Math Achievement\",\n     sub = \"Each observation is one of 160 schools.\",\n     xlab = \"School mean math achievement\")\n```\n\n::: {.cell-output-display}\n![Average math achievement across the 160 schools.](03-null-model_files/figure-html/fig-schoolmeans-1.png){#fig-schoolmeans width=672}\n:::\n:::\n\n\nIf every school had the same average, this would be a single narrow spike. It is not, and that spread is exactly what the null model is about to quantify.\n\n## Running a null model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel.null <- lmer(mathach ~ (1|schoolid), REML = FALSE, data = hsb.clean)\n\nsummary(model.null)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear mixed model fit by maximum likelihood . t-tests use Satterthwaite's\n  method [lmerModLmerTest]\nFormula: mathach ~ (1 | schoolid)\n   Data: hsb.clean\n\n      AIC       BIC    logLik -2*log(L)  df.resid \n  47121.8   47142.4  -23557.9   47115.8      7182 \n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-3.06262 -0.75365  0.02676  0.76070  2.74184 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n schoolid (Intercept)  8.553   2.925   \n Residual             39.148   6.257   \nNumber of obs: 7185, groups:  schoolid, 160\n\nFixed effects:\n            Estimate Std. Error       df t value Pr(>|t|)    \n(Intercept)  12.6371     0.2436 157.6209   51.87   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nThe `(1|schoolid)` term is what makes this multilevel. It tells `lmer()` to estimate a separate intercept for each school, drawn from a distribution whose variance we want to estimate.\n\n::: {.callout-important}\n## What makes `schoolid` a clustering variable, and what does not\n\nThis is the most common early mistake, so it is worth stopping on. Nearly every dataset has categorical variables, and almost none of them belong inside `(1 | ... )`. Before writing that term, ask three questions.\n\n**How many units are there?** A random intercept does not estimate a set of group means. It estimates a *variance*, and it does so from as many observations as there are groups. Estimating a variance from nine numbers is exactly as unreliable as it sounds. Common guidance wants 30 to 50 level-2 units for reasonable precision, with roughly 20 as a floor below which the estimate should not be trusted. We have 160 schools, which is comfortable.\n\n**Are these units a sample from a population you want to generalize to?** This is the conceptual heart of it. Random effects treat groups as draws from a population of groups, so your conclusions extend to schools you did not observe. These 160 schools are a sample of American high schools. By contrast, a variable like `sector` has two categories that are not a sample of anything; they are the complete set. There is no larger population of sectors to infer toward.\n\n**Do you want group-specific effects, or the variation among groups?** If you want to know how each category differs, that is a fixed effect: put it on the right side of the `~` like any other predictor. If you want to know how much groups vary as a class, and to generalize beyond the ones you have, that is a random effect.\n\nSo in this dataset, `schoolid` goes in the random part and `sector`, `female`, and `minority` go in the fixed part. Sex has two categories. Treatment condition has two. Region usually has four. None of those are clustering variables, however naturally the data seem to group by them.\n\nR will not stop you from writing `(1 | sector)`. It will return a variance component and standard errors and flag nothing at all. The number will simply not mean what you think it means.\n:::\n\nTwo numbers in the Random effects section carry the story. The variance associated with `schoolid` is the between-school variance, written $\\tau_{00}$. The Residual variance is the within-school, student-level variance, written $\\sigma^2$.\n\nYou also get AIC and BIC, two very common information criterion measures used to assess model fit.\n\n::: {.callout-note}\n## Why `REML = FALSE`?\n`lmer()` can estimate a model two ways. Restricted maximum likelihood (REML), the default, gives less biased variance components, especially with few level-2 units. Maximum likelihood (ML), which `REML = FALSE` requests, is required whenever you compare models that differ in their *fixed* effects, because REML likelihoods are not comparable across different fixed-effect specifications.\n\nThis book uses ML throughout so that numbers stay consistent from one page to the next and model comparisons are always valid. With 160 schools, the difference between the two is small.\n:::\n\n## Post-estimation task: calculate the ICC\n\nThese commands are run after any kind of MLM. They are called post-estimation commands because they require that the model be saved in memory. If you do something else and then try to run them, you will likely get an error.\n\nThe intraclass correlation is the proportion of total variance lying between schools:\n\n$$\\text{ICC} = \\frac{\\tau_{00}}{\\tau_{00} + \\sigma^2}$$\n\nHere's a quick and easy way to get our friend the ICC:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnull.ICC <- 8.553/(8.553 + 39.148)\nnull.ICC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1793044\n```\n:::\n:::\n\n\nRoughly 18 percent of the variation in math achievement is between schools. Put another way, two students from the same school are noticeably more similar to each other than two students drawn at random from the full sample. That is the condition that makes ordinary regression standard errors too small.\n\n::: {.callout-tip}\n## Pulling the numbers out rather than typing them\nTyping the variance components by hand works and makes the formula visible, which is why it is worth doing once. For your own analyses it is safer to extract them from the model, since a transposed digit produces a plausible-looking wrong answer:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvc <- as.data.frame(VarCorr(model.null))\n\ntau00  <- vc$vcov[vc$grp == \"schoolid\"]\nsigma2 <- vc$vcov[vc$grp == \"Residual\"]\n\ntau00 / (tau00 + sigma2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1793109\n```\n:::\n:::\n\n\nThe `performance` package will also compute it directly with `performance::icc(model.null)`.\n:::\n\n## Using `lmerTest` to evaluate random effects\n\n\n::: {.cell}\n\n```{.r .cell-code}\nranova(model.null)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nANOVA-like table for random-effects: Single term deletions\n\nModel:\nmathach ~ 1 + (1 | schoolid)\n               npar logLik   AIC    LRT Df Pr(>Chisq)    \n<none>            3 -23558 47122                         \n(1 | schoolid)    2 -24050 48104 983.92  1  < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nThis is a likelihood ratio test comparing our model to one without the random intercept. A significant result says that letting schools have their own intercepts improves fit enough to justify the extra parameter.\n\nRead it alongside the ICC rather than instead of it. The test tells you whether school-level variance is distinguishable from zero; the ICC tells you how much of it there is. With 7,185 students you have enough power to detect quite small amounts of clustering, so significance alone is weak evidence that multilevel modeling matters substantively.\n\n::: {.callout-note}\n## `rand()` became `ranova()`\nOlder handouts call `lmerTest::rand()`. The function was renamed to `ranova()` several versions ago. The old name may still work but is no longer the documented one.\n:::\n\n## Always interesting: compare our MLM to a regular regression\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel.regular <- lm(mathach ~ NULL, data = hsb.clean)\n\nsummary(model.regular)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mathach ~ NULL, data = hsb.clean)\n\nResiduals:\nStd. Math Score \n     Min       1Q   Median       3Q      Max \n-15.5799  -5.4729   0.3831   5.5691  12.2451 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 12.74785    0.08115   157.1   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.878 on 7184 degrees of freedom\n```\n:::\n:::\n\n\nThe intercept estimates are similar, which is expected in a null model. What differs is the standard error, and that difference is the entire practical argument for multilevel modeling. Ordinary regression treats 7,185 students as 7,185 independent pieces of information, when students within a school share teachers, curricula, neighborhoods, and funding. The result is standard errors that are too small and p-values that are too optimistic.\n\nOne last point students routinely get wrong. The fixed-effect intercept in the null model is not simply the mean of all 7,185 scores. It estimates the average of the *school* means, weighting schools by how much information each contributes. With balanced data the two are close; with unbalanced data they differ, and the multilevel estimate is usually the one you want.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(hsb.clean$mathach, na.rm = TRUE)   # grand mean of all students\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 12.74785\n```\n:::\n\n```{.r .cell-code}\nfixef(model.null)                       # model-based estimate\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept) \n   12.63707 \n```\n:::\n:::\n\n\n## What comes next\n\nThe null model tells us schools differ. It does not tell us why. The next chapter starts adding predictors, at both the student and school levels, to explain some of the variance we just found.\n",
    "supporting": [
      "03-null-model_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}