{
  "hash": "31fa628ccae4c5822e5db516dcf4f8c8",
  "result": {
    "markdown": "# Goodness-of-Fit and Effect Sizes\n\n**Data for this chapter:** `lq2002.csv`\n\nSignificance tells you whether an association is distinguishable from zero. It does not tell you whether the association matters, and with large samples the two questions come apart badly. This chapter covers effect sizes for multilevel models and the fit statistics used to choose among competing models.\n\nWe return to the Gavin and Hofmann (2002) Army data from the last two chapters: 2,042 soldiers nested within 49 companies. The outcome is `HOSTILE`, a hostility scale score that runs from 0 to 4. The predictors are `TSIG` (task significance) and `LEAD` (leadership climate), both measured on each soldier, plus `GTSIG`, the company average of task significance. `COMPID` identifies the company.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressPackageStartupMessages(library(tidyverse))\nlibrary(lme4)\nlibrary(lmerTest)\nlibrary(performance)\nlibrary(modelsummary)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlq2002 <- readr::read_csv(\"lq2002.csv\") |>\n  group_by(COMPID) |>\n  mutate(\n    TSIG_gc = TSIG - mean(TSIG, na.rm = TRUE),   # group-mean center the level-1 predictors\n    LEAD_gc = LEAD - mean(LEAD, na.rm = TRUE)\n  ) |>\n  ungroup() |>\n  mutate(\n    GTSIG_c = GTSIG - mean(GTSIG, na.rm = TRUE)  # grand-mean center the level-2 predictor\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 2042 Columns: 28\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\ndbl (28): ROWID, COMPID, SUB, LEAD01, LEAD02, LEAD03, LEAD04, LEAD05, LEAD06...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n```{.r .cell-code}\nglimpse(lq2002)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 2,042\nColumns: 31\n$ ROWID    <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18…\n$ COMPID   <dbl> 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2…\n$ SUB      <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18…\n$ LEAD01   <dbl> 2, 4, 4, 1, 1, 2, 3, 3, 3, 4, 2, 2, 4, 4, 1, 2, 4, 4, 4, 4, 4…\n$ LEAD02   <dbl> 2, 4, 4, 1, 1, 3, 2, 3, 4, 3, 4, 3, 4, 4, 1, 1, 5, 4, 5, 4, 2…\n$ LEAD03   <dbl> 2, 2, 2, 1, 1, 2, 2, 2, 3, 3, 1, 1, 4, 4, 1, 2, 3, 4, 1, 4, 2…\n$ LEAD04   <dbl> 3, 4, 4, 1, 1, 4, 1, 4, 2, 4, 3, 1, 4, 4, 1, 4, 5, 4, 1, 5, 1…\n$ LEAD05   <dbl> 2, 4, 2, 1, 3, 2, 2, 2, 3, 3, 1, 2, 4, 4, 1, 3, 3, 4, 1, 2, 2…\n$ LEAD06   <dbl> 2, 4, 4, 1, 2, 4, 2, 2, 3, 4, 3, 4, 4, 4, 1, 3, 5, 4, 4, 2, 2…\n$ LEAD07   <dbl> 5, 4, 4, 4, 1, 3, 2, 2, 3, 3, 3, 1, 4, 3, 1, 5, 3, 4, 1, 3, 2…\n$ LEAD08   <dbl> 5, 4, 4, 2, 1, 4, 2, 4, 1, 4, 4, 3, 4, 4, 1, 2, 5, 4, 1, 3, 2…\n$ LEAD09   <dbl> 5, 4, 4, 3, 1, 2, 3, 2, 3, 3, 2, 2, 4, 4, 1, 4, 1, 4, 1, 4, 2…\n$ LEAD10   <dbl> 5, 4, 4, 3, 1, 4, 4, 2, 2, 4, 3, 2, 4, 4, 1, 2, 5, 4, 4, 4, 1…\n$ LEAD11   <dbl> 4, 3, 2, 2, 1, 3, 2, 4, 3, 3, 2, 1, 4, 4, 1, 2, 4, 4, 1, 4, 2…\n$ TSIG01   <dbl> 1, 3, 5, 1, 4, 4, 2, 2, 4, 4, 3, 3, 4, 4, 1, 1, 4, 4, 1, 5, 1…\n$ TSIG02   <dbl> 5, 4, 5, 3, 4, 4, 4, 2, 3, 4, 4, 3, 4, 4, 1, 5, 4, 4, 5, 5, 4…\n$ TSIG03   <dbl> 5, 3, 5, 2, 4, 4, 4, 4, 4, 4, 3, 3, 4, 4, 1, 4, 5, 4, 5, 5, 4…\n$ HOSTIL01 <dbl> 0, 3, 1, 2, 2, 0, 2, 0, 0, 1, 1, 2, 0, 0, 4, 3, 1, 0, 4, 3, 4…\n$ HOSTIL02 <dbl> 0, 2, 0, 1, 0, 0, 0, 0, 4, 0, 0, 2, 0, 0, 4, 0, 0, 0, 0, 1, 4…\n$ HOSTIL03 <dbl> 0, 0, 0, 3, 0, 0, 1, 0, 4, 0, 0, 0, 0, 0, 4, 0, 0, 0, 4, 2, 2…\n$ HOSTIL04 <dbl> 0, 0, 0, 3, 0, 0, 1, 0, 4, 0, 0, 1, 0, 0, 4, 0, 0, 0, 4, 3, 2…\n$ HOSTIL05 <dbl> 0, 1, 1, 0, 0, 0, 0, 0, 4, 0, 0, 2, 0, 0, 2, 0, 0, 0, 4, 2, 3…\n$ LEAD     <dbl> 3.363636, 3.727273, 3.454545, 1.818182, 1.272727, 3.000000, 2…\n$ TSIG     <dbl> 3.666667, 3.333333, 5.000000, 2.000000, 4.000000, 4.000000, 3…\n$ HOSTILE  <dbl> 0.0, 1.2, 0.4, 1.8, 0.4, 0.0, 0.8, 0.0, 3.2, 0.2, 0.2, 1.4, 0…\n$ GLEAD    <dbl> 2.882576, 2.882576, 2.882576, 2.882576, 2.882576, 2.882576, 2…\n$ GTSIG    <dbl> 3.541667, 3.541667, 3.541667, 3.541667, 3.541667, 3.541667, 3…\n$ GHOSTILE <dbl> 1.0416667, 1.0416667, 1.0416667, 1.0416667, 1.0416667, 1.0416…\n$ TSIG_gc  <dbl> 0.1250000, -0.2083333, 1.4583333, -1.5416667, 0.4583333, 0.45…\n$ LEAD_gc  <dbl> 0.4810606, 0.8446970, 0.5719697, -1.0643939, -1.6098485, 0.11…\n$ GTSIG_c  <dbl> 0.4086272, 0.4086272, 0.4086272, 0.4086272, 0.4086272, 0.4086…\n```\n:::\n:::\n\n\nAs in the last chapter, we group-mean center the level-1 predictors and grand-mean center the level-2 predictor. `TSIG_gc` and `LEAD_gc` express each soldier's score as a distance from their *own* company's average, so they carry only within-company variation. `GTSIG_c` expresses each company's average task significance as a distance from the average company. The intercept in every model below describes a soldier who sits exactly at their company's average on both predictors, in a company of average task significance.\n\n## Two models to compare\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_null <- lmer(HOSTILE ~ 1 + (1 | COMPID), data = lq2002, REML = FALSE)\n\nm_cond <- lmer(HOSTILE ~ GTSIG_c + TSIG_gc + LEAD_gc + (1 | COMPID),\n               data = lq2002, REML = FALSE)\n\nsummary(m_cond)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear mixed model fit by maximum likelihood . t-tests use Satterthwaite's\n  method [lmerModLmerTest]\nFormula: HOSTILE ~ GTSIG_c + TSIG_gc + LEAD_gc + (1 | COMPID)\n   Data: lq2002\n\n      AIC       BIC    logLik -2*log(L)  df.resid \n   5547.9    5581.6   -2768.0    5535.9      2036 \n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-2.3339 -0.6970 -0.2219  0.5082  3.5377 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n COMPID   (Intercept) 0.01985  0.1409  \n Residual             0.86785  0.9316  \nNumber of obs: 2042, groups:  COMPID, 49\n\nFixed effects:\n              Estimate Std. Error         df t value Pr(>|t|)    \n(Intercept)    0.93509    0.03053   35.27446  30.625  < 2e-16 ***\nGTSIG_c       -0.57251    0.09204   38.68403  -6.220 2.64e-07 ***\nTSIG_gc       -0.17486    0.02510 1991.15348  -6.967 4.38e-12 ***\nLEAD_gc       -0.34583    0.03134 1991.15348 -11.036  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n        (Intr) GTSIG_ TSIG_g\nGTSIG_c -0.063              \nTSIG_gc  0.000  0.000       \nLEAD_gc  0.000  0.000 -0.528\n```\n:::\n:::\n\n\nThe null model tells us that company membership accounts for only about 5% of the variance in hostility (an ICC of about .05, with $\\tau_{00}$ = .058 and $\\sigma^2$ = 1.017). In the conditional model, all three predictors are negatively related to hostility, and all three coefficients are clearly distinguishable from zero. Because of the centering, they answer different questions. The `TSIG_gc` and `LEAD_gc` coefficients are *within-company* effects: a soldier who finds the work more significant than their company-mates do, or who reports a better leadership climate than they do, reports less hostility. The `GTSIG_c` coefficient is a *between-company* effect: companies where task significance is high on average have lower average hostility, and the estimate (about $-.57$) is more than three times the within-company one for `TSIG_gc` ($-.17$). The question for the rest of the chapter is how much that matters.\n\n## Proportional reduction in variance\n\nThe most interpretable multilevel effect sizes ask how much variance a model explains relative to the null model, computed separately at each level. Extract the variance components first:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvc_null <- as.data.frame(VarCorr(m_null))\nvc_cond <- as.data.frame(VarCorr(m_cond))\n\ntau_null   <- vc_null$vcov[vc_null$grp == \"COMPID\"]\nsigma_null <- vc_null$vcov[vc_null$grp == \"Residual\"]\n\ntau_cond   <- vc_cond$vcov[vc_cond$grp == \"COMPID\"]\nsigma_cond <- vc_cond$vcov[vc_cond$grp == \"Residual\"]\n\nc(tau_null = tau_null, sigma_null = sigma_null,\n  tau_cond = tau_cond, sigma_cond = sigma_cond)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  tau_null sigma_null   tau_cond sigma_cond \n0.05764857 1.01667991 0.01985321 0.86784844 \n```\n:::\n:::\n\n\nWithin-group proportional reduction in variance is the share of soldier-level variance the predictors account for:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwg_prv <- (sigma_null - sigma_cond) / sigma_null\nwg_prv\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1463897\n```\n:::\n:::\n\n\nBetween-group PRV does the same at the company level:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbg_prv <- (tau_null - tau_cond) / tau_null\nbg_prv\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6556165\n```\n:::\n:::\n\n\nAnd a total, or multilevel, $R^2$ uses the combined variance:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntotal_null <- tau_null + sigma_null\ntotal_cond <- tau_cond + sigma_cond\n\nml_r2 <- (total_null - total_cond) / total_null\nml_r2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1737149\n```\n:::\n:::\n\n\nBe precise about what each denominator refers to when you write these up. WG-PRV is the proportion of *soldier-level* variance explained, not the proportion of all variance. Reporting it as though it were an overall $R^2$ overstates your model considerably.\n\nThese data show why. The predictors account for about 15% of the within-company variance (WG-PRV = .146) and about 66% of the between-company variance (BG-PRV = .656). That second number sounds impressive until you remember how little between-company variance there was to explain: $\\tau_{00}$ fell from .058 to .020, and company differences were only about 5% of the total to begin with. The multilevel $R^2$ of .174 is the fairer summary of how much of the variation in hostility the model accounts for, and almost all of that explained variance is *within* companies.\n\nNotice also where the between-company reduction comes from. The group-mean centered predictors contain no between-company information by construction, so the only predictor that can explain company differences is `GTSIG_c`. A model with `GTSIG_c` alone has a BG-PRV of about .73, higher than the .66 for the full model, which leads directly to the next point.\n\n### When PRV comes out negative\n\nA negative PRV looks like an arithmetic mistake and usually is not. Adding a level-one predictor can increase the estimated level-two variance, because the level-two variance is estimated conditional on everything else in the model. If a student-level predictor is unevenly distributed across teachers, controlling for it can reveal teacher differences that were previously masked. Report the negative value and explain it. Deleting it from your table is the one clearly wrong response.\n\nThese data produce a clean example. Fit a model with only the two group-mean centered level-1 predictors:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_within <- lmer(HOSTILE ~ TSIG_gc + LEAD_gc + (1 | COMPID),\n                 data = lq2002, REML = FALSE)\n\nvc_within    <- as.data.frame(VarCorr(m_within))\ntau_within   <- vc_within$vcov[vc_within$grp == \"COMPID\"]\nsigma_within <- vc_within$vcov[vc_within$grp == \"Residual\"]\n\nc(wg_prv = (sigma_null - sigma_within) / sigma_null,\n  bg_prv = (tau_null - tau_within) / tau_null)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     wg_prv      bg_prv \n 0.14907909 -0.06864074 \n```\n:::\n:::\n\n\nThe within-company PRV is positive, about .149, because these predictors do explain soldier-level variance. The between-company PRV is negative, about $-.069$, because $\\tau_{00}$ rose slightly, from .058 to .062. Group-mean centered predictors have nothing to say about differences between companies, so there was no reduction to expect. Once the within-company variance is accounted for, the estimate of the company-level variance shifts a little. The right reading is \"no reduction in between-company variance,\" and the right response is to report it.\n\n## The `performance` package version\n\n\n::: {.cell}\n\n```{.r .cell-code}\nperformance::r2(m_cond)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# R2 for Mixed Models\n\n  Conditional R2: 0.189\n     Marginal R2: 0.171\n```\n:::\n:::\n\n\nThis reports marginal $R^2$, the variance explained by fixed effects alone (.171), and conditional $R^2$, the variance explained by fixed and random effects together (.189). These are Nakagawa's measures, and they answer a slightly different question than the PRV statistics above. Marginal $R^2$ lands close to our multilevel $R^2$ of .174 but is not identical to it. The conditional value is only a little larger than the marginal one because company differences are such a small share of the variance. Both are defensible. Say which you used.\n\n## Translating for a non-technical audience\n\nSuppose a battalion commander asks how much leadership climate matters for hostility. Effect sizes in variance units rarely land. Predicted values usually do:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggeffects)\n\nggpredict(m_cond, terms = \"LEAD_gc [meansd]\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# Predicted values of HOSTILE\n\nLEAD_gc | Predicted |     95% CI\n--------------------------------\n  -0.77 |      1.20 | 1.13, 1.28\n   0.00 |      0.94 | 0.88, 0.99\n   0.77 |      0.67 | 0.59, 0.75\n\nAdjusted for:\n* GTSIG_c =  0.00\n* TSIG_gc = -0.00\n*  COMPID = 0 (population-level)\n```\n:::\n:::\n\n\nThe three rows show predicted hostility for a soldier one standard deviation below their company's average on leadership climate (1.20), at their company's average (0.94), and one standard deviation above (0.67), holding the other predictors at their means. Because `LEAD_gc` is centered within companies, one standard deviation here is the typical spread among soldiers in the same company (0.77), not the spread across the whole Army. Reporting that a soldier who rates leadership climate one standard deviation higher than their company-mates do is predicted to score about 0.27 points lower on hostility, on a scale that runs from 0 to 4, communicates more than a proportional reduction in variance ever will. A standardized mean difference is another good option when your audience is used to reading them: 0.27 points is about a quarter of a standard deviation of hostility (SD = 1.04).\n\n## Model comparison with information criteria\n\nNow a different question: which model should we report? Start by adding a random slope for task significance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_slope <- lmer(HOSTILE ~ GTSIG_c + TSIG_gc + LEAD_gc +\n                  (1 + TSIG_gc | COMPID),\n                data = lq2002, REML = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nboundary (singular) fit: see help('isSingular')\n```\n:::\n\n```{.r .cell-code}\nranova(m_slope)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nANOVA-like table for random-effects: Single term deletions\n\nModel:\nHOSTILE ~ GTSIG_c + TSIG_gc + LEAD_gc + (1 + TSIG_gc | COMPID)\n                                  npar  logLik    AIC    LRT Df Pr(>Chisq)    \n<none>                               8 -2757.1 5530.2                         \nTSIG_gc in (1 + TSIG_gc | COMPID)    6 -2767.9 5547.9 21.723  2  1.918e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(m_cond, m_slope)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData: lq2002\nModels:\nm_cond: HOSTILE ~ GTSIG_c + TSIG_gc + LEAD_gc + (1 | COMPID)\nm_slope: HOSTILE ~ GTSIG_c + TSIG_gc + LEAD_gc + (1 + TSIG_gc | COMPID)\n        npar    AIC    BIC  logLik -2*log(L)  Chisq Df Pr(>Chisq)    \nm_cond     6 5547.9 5581.6 -2767.9    5535.9                         \nm_slope    8 5530.2 5575.2 -2757.1    5514.2 21.723  2  1.918e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nAIC(m_cond, m_slope)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        df      AIC\nm_cond   6 5547.902\nm_slope  8 5530.179\n```\n:::\n\n```{.r .cell-code}\nBIC(m_cond, m_slope)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        df      BIC\nm_cond   6 5581.632\nm_slope  8 5575.153\n```\n:::\n:::\n\n\n### When the criteria disagree\n\nThey often will, and understanding why is more useful than memorizing a rule. AIC and BIC both penalize complexity, but BIC's penalty grows with sample size while AIC's does not. With a large sample, BIC prefers simpler models more aggressively than AIC does. The likelihood ratio test is a third thing again: a hypothesis test with a null of no improvement, which inherits all the usual sensitivities to sample size.\n\nFor random effects there is an additional wrinkle. Testing whether a variance component equals zero puts the null on the boundary of the parameter space, which makes the usual chi-square reference distribution conservative, and `ranova()` does not correct for it. It is a reason not to treat a p-value of .06 on a variance component as decisive.\n\nWhen the criteria disagree, say so, state which you weighted and why, and check whether your substantive conclusions change between the two models. If the treatment effect is essentially identical either way, the model choice matters less than it appears to.\n\nFor this random slope, the criteria do not disagree. The likelihood ratio test is clearly significant, $\\chi^2$(2) = 21.72, $p$ < .001. AIC drops from 5547.9 to 5530.2, and even BIC, with its heavier penalty, drops from 5581.6 to 5575.2. Everything points toward keeping the slope.\n\nAgreement among the criteria does not make a model trustworthy, though. Look inside it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nVarCorr(m_slope)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Groups   Name        Std.Dev. Corr   \n COMPID   (Intercept) 0.15592         \n          TSIG_gc     0.11796  -1.000 \n Residual             0.92303         \n```\n:::\n:::\n\n\nR printed `boundary (singular) fit` when it fitted this model, and the correlation between the intercept and the `TSIG_gc` slope is exactly $-1.00$. That is not a finding about the Army. It is the model reporting that it has run out of information, which is the same thing we saw in the last chapter. The slope variance is real enough that the fit statistics reward it, but the *correlation* is more than 49 companies can support.\n\n## When a model will not converge\n\nAsk for two random slopes and things get worse:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_two_slopes <- lmer(HOSTILE ~ GTSIG_c + TSIG_gc + LEAD_gc +\n                       (1 + TSIG_gc + LEAD_gc | COMPID),\n                     data = lq2002, REML = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nboundary (singular) fit: see help('isSingular')\n```\n:::\n\n```{.r .cell-code}\nVarCorr(m_two_slopes)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Groups   Name        Std.Dev. Corr          \n COMPID   (Intercept) 0.15690                \n          TSIG_gc     0.13269  -0.870        \n          LEAD_gc     0.12223  -0.098 -0.406 \n Residual             0.91926                \n```\n:::\n:::\n\n\nThis one fits, but R again reports a singular fit. The printed correlations ($-.87$, $-.10$, and $-.41$) look unremarkable, which is what makes this case easy to miss. The problem is hiding in the covariance matrix of the three random effects: it has a zero eigenvalue, meaning some combination of the intercept and the two slopes has no variance at all. The model has collapsed onto something smaller than the structure we asked for.\n\nIt is worth doing the arithmetic yourself before fitting a complex random effects structure. A model with $q$ random effects per company needs $q(q + 1)/2$ variance and covariance parameters: 1 for a random intercept alone, 3 for an intercept and one slope, and 6 for an intercept and two slopes. Compare that to the number of level-two units, not the number of soldiers. Slope variance is learned from how much slopes *differ across companies*, and we have only 49 companies, so 2,042 soldiers do not help as much as you might hope. The more parameters you ask 49 companies to support, the less well each one is determined, and the first thing to give is usually a correlation.\n\nThe more common situation is a message like this one rather than a failure to run. Instead of an outright refusal you get a singular fit, you might get a variance component estimated at essentially zero, or a correlation of exactly 1 or -1. Those are the same messages, just delivered a little more politely. The data cannot support that many random effects.\n\nSo how might you respond? You basically have three choices, in order from most to least preferred: 1) drop the random slope correlations and keep both slopes uncorrelated; 2) drop the less theoretically important slope; or 3) return to a random intercept model and acknowledge in your write-up that slope variation could not be estimated with these data. All three are defensible, and all are better than reporting a singular model as though it converged normally.\n\nHere is the first option:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Uncorrelated random effects\nm_uncorr <- lmer(HOSTILE ~ GTSIG_c + TSIG_gc + LEAD_gc +\n                   (1 | COMPID) + (0 + TSIG_gc | COMPID) + (0 + LEAD_gc | COMPID),\n                 data = lq2002, REML = FALSE)\n\nisSingular(m_uncorr)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] FALSE\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(m_cond, m_uncorr)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData: lq2002\nModels:\nm_cond: HOSTILE ~ GTSIG_c + TSIG_gc + LEAD_gc + (1 | COMPID)\nm_uncorr: HOSTILE ~ GTSIG_c + TSIG_gc + LEAD_gc + (1 | COMPID) + (0 + TSIG_gc | COMPID) + (0 + LEAD_gc | COMPID)\n         npar    AIC    BIC logLik -2*log(L)  Chisq Df Pr(>Chisq)  \nm_cond      6 5547.9 5581.6  -2768    5535.9                       \nm_uncorr    8 5545.9 5590.9  -2765    5529.9 6.0017  2    0.04975 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\nAIC(m_cond, m_uncorr)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         df      AIC\nm_cond    6 5547.902\nm_uncorr  8 5545.901\n```\n:::\n\n```{.r .cell-code}\nBIC(m_cond, m_uncorr)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         df      BIC\nm_cond    6 5581.632\nm_uncorr  8 5590.874\n```\n:::\n:::\n\n\nThis model is not singular, so it is a fit we can report honestly. It also gives us the disagreement described above, in miniature. The likelihood ratio test lands right at the edge of conventional significance ($\\chi^2$(2) = 6.00, $p$ = .050), and AIC edges toward the model with random slopes (5545.9 versus 5547.9), while BIC clearly favors the simpler random intercept model (5590.9 versus 5581.6). BIC charges each extra parameter ln(2,042) $\\approx$ 7.6, against 2 for AIC, so two additional variance components cost about 15 on the BIC scale and only 4 on the AIC scale.\n\nSo which do we report? Check whether the substantive story changes. The fixed effects barely move: `GTSIG_c` goes from $-.573$ to $-.571$, `TSIG_gc` from $-.175$ to $-.162$, and `LEAD_gc` from $-.346$ to $-.339$. All three stay negative and clearly distinguishable from zero in both models. Because the conclusions about the predictors do not depend on the choice, either model is defensible as long as you say which you used and why, and report the other as a check.\n\n## Putting it together\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(\n  list(\"Null\" = m_null, \"Conditional\" = m_cond,\n       \"+ Random slope\" = m_slope, \"+ Uncorrelated slopes\" = m_uncorr),\n  stars = c(\"*\" = .05, \"**\" = .01, \"***\" = .001),\n  gof_map = c(\"nobs\", \"aic\", \"bic\"),\n  title = \"Models predicting soldier hostility\"\n)\n```\n\n::: {.cell-output-display}\n```{=html}\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_l7mlew9o1uum9hcr3iki = TinyTable.createTableFunctions(\"tinytable_l7mlew9o1uum9hcr3iki\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '16', j: 2 }, { i: '16', j: 3 }, { i: '16', j: 4 }, { i: '16', j: 5 } ], css_id: 'tinytable_css_ubdepnhihna7p17x2gzx',}, \n          { positions: [ { i: '13', j: 2 }, { i: '13', j: 3 }, { i: '13', j: 4 }, { i: '13', j: 5 } ], css_id: 'tinytable_css_tbuz3nsez7kzbqc42zac',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '14', j: 2 }, { i: '15', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '10', j: 3 }, { i: '11', j: 3 }, { i: '12', j: 3 }, { i: '14', j: 3 }, { i: '15', j: 3 }, { i: '1', j: 4 }, { i: '2', j: 4 }, { i: '3', j: 4 }, { i: '4', j: 4 }, { i: '5', j: 4 }, { i: '6', j: 4 }, { i: '7', j: 4 }, { i: '8', j: 4 }, { i: '9', j: 4 }, { i: '10', j: 4 }, { i: '11', j: 4 }, { i: '12', j: 4 }, { i: '14', j: 4 }, { i: '15', j: 4 }, { i: '1', j: 5 }, { i: '2', j: 5 }, { i: '3', j: 5 }, { i: '4', j: 5 }, { i: '5', j: 5 }, { i: '6', j: 5 }, { i: '7', j: 5 }, { i: '8', j: 5 }, { i: '9', j: 5 }, { i: '10', j: 5 }, { i: '11', j: 5 }, { i: '12', j: 5 }, { i: '14', j: 5 }, { i: '15', j: 5 } ], css_id: 'tinytable_css_k23ku5tkfh6kygpqac7r',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 } ], css_id: 'tinytable_css_1fre2xyfbsd52qz3ml5p',}, \n          { positions: [ { i: '16', j: 1 } ], css_id: 'tinytable_css_uudve1rsvcf41eolfsge',}, \n          { positions: [ { i: '13', j: 1 } ], css_id: 'tinytable_css_zhonjanqjj3tpsjq4wnj',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '14', j: 1 }, { i: '15', j: 1 } ], css_id: 'tinytable_css_jm7rpzzj8zlwjsdhrwz2',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_3ngpwan3ray18wtwnvlz',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_l7mlew9o1uum9hcr3iki.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_l7mlew9o1uum9hcr3iki td.tinytable_css_ubdepnhihna7p17x2gzx, #tinytable_l7mlew9o1uum9hcr3iki th.tinytable_css_ubdepnhihna7p17x2gzx {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_l7mlew9o1uum9hcr3iki td.tinytable_css_tbuz3nsez7kzbqc42zac, #tinytable_l7mlew9o1uum9hcr3iki th.tinytable_css_tbuz3nsez7kzbqc42zac {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_l7mlew9o1uum9hcr3iki td.tinytable_css_k23ku5tkfh6kygpqac7r, #tinytable_l7mlew9o1uum9hcr3iki th.tinytable_css_k23ku5tkfh6kygpqac7r { text-align: center }\n    #tinytable_l7mlew9o1uum9hcr3iki td.tinytable_css_1fre2xyfbsd52qz3ml5p, #tinytable_l7mlew9o1uum9hcr3iki th.tinytable_css_1fre2xyfbsd52qz3ml5p {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_l7mlew9o1uum9hcr3iki td.tinytable_css_uudve1rsvcf41eolfsge, #tinytable_l7mlew9o1uum9hcr3iki th.tinytable_css_uudve1rsvcf41eolfsge {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_l7mlew9o1uum9hcr3iki td.tinytable_css_zhonjanqjj3tpsjq4wnj, #tinytable_l7mlew9o1uum9hcr3iki th.tinytable_css_zhonjanqjj3tpsjq4wnj {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_l7mlew9o1uum9hcr3iki td.tinytable_css_jm7rpzzj8zlwjsdhrwz2, #tinytable_l7mlew9o1uum9hcr3iki th.tinytable_css_jm7rpzzj8zlwjsdhrwz2 { text-align: left }\n    #tinytable_l7mlew9o1uum9hcr3iki td.tinytable_css_3ngpwan3ray18wtwnvlz, #tinytable_l7mlew9o1uum9hcr3iki th.tinytable_css_3ngpwan3ray18wtwnvlz {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_l7mlew9o1uum9hcr3iki\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <caption>Models predicting soldier hostility</caption>\n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Null</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Conditional</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">+ Random slope</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">+ Uncorrelated slopes</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='5'>* p < 0.05, ** p < 0.01, *** p < 0.001</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">0.906***</td>\n                  <td data-row=\"1\" data-col=\"3\">0.935***</td>\n                  <td data-row=\"1\" data-col=\"4\">0.923***</td>\n                  <td data-row=\"1\" data-col=\"5\">0.935***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.043)</td>\n                  <td data-row=\"2\" data-col=\"3\">(0.031)</td>\n                  <td data-row=\"2\" data-col=\"4\">(0.032)</td>\n                  <td data-row=\"2\" data-col=\"5\">(0.031)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">GTSIG_c</td>\n                  <td data-row=\"3\" data-col=\"2\"></td>\n                  <td data-row=\"3\" data-col=\"3\">-0.573***</td>\n                  <td data-row=\"3\" data-col=\"4\">-0.510***</td>\n                  <td data-row=\"3\" data-col=\"5\">-0.571***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\"></td>\n                  <td data-row=\"4\" data-col=\"3\">(0.092)</td>\n                  <td data-row=\"4\" data-col=\"4\">(0.085)</td>\n                  <td data-row=\"4\" data-col=\"5\">(0.092)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">TSIG_gc</td>\n                  <td data-row=\"5\" data-col=\"2\"></td>\n                  <td data-row=\"5\" data-col=\"3\">-0.175***</td>\n                  <td data-row=\"5\" data-col=\"4\">-0.153***</td>\n                  <td data-row=\"5\" data-col=\"5\">-0.162***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\"></td>\n                  <td data-row=\"6\" data-col=\"3\">(0.025)</td>\n                  <td data-row=\"6\" data-col=\"4\">(0.031)</td>\n                  <td data-row=\"6\" data-col=\"5\">(0.030)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">LEAD_gc</td>\n                  <td data-row=\"7\" data-col=\"2\"></td>\n                  <td data-row=\"7\" data-col=\"3\">-0.346***</td>\n                  <td data-row=\"7\" data-col=\"4\">-0.344***</td>\n                  <td data-row=\"7\" data-col=\"5\">-0.339***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\"></td>\n                  <td data-row=\"8\" data-col=\"3\">(0.031)</td>\n                  <td data-row=\"8\" data-col=\"4\">(0.031)</td>\n                  <td data-row=\"8\" data-col=\"5\">(0.035)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">SD (Intercept COMPID)</td>\n                  <td data-row=\"9\" data-col=\"2\">0.240</td>\n                  <td data-row=\"9\" data-col=\"3\">0.141</td>\n                  <td data-row=\"9\" data-col=\"4\">0.156</td>\n                  <td data-row=\"9\" data-col=\"5\">0.142</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\">SD (TSIG_gc COMPID)</td>\n                  <td data-row=\"10\" data-col=\"2\"></td>\n                  <td data-row=\"10\" data-col=\"3\"></td>\n                  <td data-row=\"10\" data-col=\"4\">0.118</td>\n                  <td data-row=\"10\" data-col=\"5\">0.100</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">Cor (Intercept~TSIG_gc COMPID)</td>\n                  <td data-row=\"11\" data-col=\"2\"></td>\n                  <td data-row=\"11\" data-col=\"3\"></td>\n                  <td data-row=\"11\" data-col=\"4\">-1.000</td>\n                  <td data-row=\"11\" data-col=\"5\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\">SD (LEAD_gc COMPID)</td>\n                  <td data-row=\"12\" data-col=\"2\"></td>\n                  <td data-row=\"12\" data-col=\"3\"></td>\n                  <td data-row=\"12\" data-col=\"4\"></td>\n                  <td data-row=\"12\" data-col=\"5\">0.090</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"1\">SD (Observations)</td>\n                  <td data-row=\"13\" data-col=\"2\">1.008</td>\n                  <td data-row=\"13\" data-col=\"3\">0.932</td>\n                  <td data-row=\"13\" data-col=\"4\">0.923</td>\n                  <td data-row=\"13\" data-col=\"5\">0.924</td>\n                </tr>\n                <tr>\n                  <td data-row=\"14\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"14\" data-col=\"2\">2042</td>\n                  <td data-row=\"14\" data-col=\"3\">2042</td>\n                  <td data-row=\"14\" data-col=\"4\">2042</td>\n                  <td data-row=\"14\" data-col=\"5\">2042</td>\n                </tr>\n                <tr>\n                  <td data-row=\"15\" data-col=\"1\">AIC</td>\n                  <td data-row=\"15\" data-col=\"2\">5893.4</td>\n                  <td data-row=\"15\" data-col=\"3\">5566.9</td>\n                  <td data-row=\"15\" data-col=\"4\">5549.0</td>\n                  <td data-row=\"15\" data-col=\"5\">5564.2</td>\n                </tr>\n                <tr>\n                  <td data-row=\"16\" data-col=\"1\">BIC</td>\n                  <td data-row=\"16\" data-col=\"2\">5910.3</td>\n                  <td data-row=\"16\" data-col=\"3\">5600.7</td>\n                  <td data-row=\"16\" data-col=\"4\">5594.0</td>\n                  <td data-row=\"16\" data-col=\"5\">5609.2</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n:::\n:::\n\n\n## A note on your content review\n\nYour Module 6 content review uses the Best in Class classroom data rather than these Army data. The steps are the same: calculate effect sizes from the null and conditional models, compare a random slope model using the fit indices, and see what happens when you ask for more random slopes than the data can support. What changes is the substance of the question, not the code.\n",
    "supporting": [
      "06-fit-effect-sizes_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}