<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="An online companion to Dr.&nbsp;Broda’s Multilevel Modeling course (EDUS 664) at Virginia Commonwealth University. Each chapter works through the R code for one course module.">
<title>4&nbsp; Intro to MLM and the Null Model – Applied Multilevel Modeling in R</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./04-random-intercept.html" rel="next">
<link href="./02-regression-review.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-0f3a71d5963b834a2d5774f6f36c66af.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script><script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script><script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">
<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03-null-model.html">Two-Level Models</a></li><li class="breadcrumb-item"><a href="./03-null-model.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Intro to MLM and the Null Model</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Applied Multilevel Modeling in R</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/mikediam123/mlm-textbook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
<li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
</div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-getting-started.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting Started with R and RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-reading-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Reading: Regression and Where It Runs Out</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-regression-review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Review of Linear Regression</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Two-Level Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-null-model.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Intro to MLM and the Null Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-random-intercept.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Conditional Random Intercept Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-random-slopes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Random Slope Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-fit-effect-sizes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Goodness-of-Fit and Effect Sizes</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Extending the Model</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-three-level.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Three-Level Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08a-growth-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Intro to Growth Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08b-growth-advanced.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Advanced Growth Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-binary-outcomes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Binary and Generalized Linear Mixed Models</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Checking and Complicating</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Checking Assumptions for MLMs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-cross-classified.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Cross-Classified Linear Mixed Models</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#load-some-packages-to-help-with-the-analysis-and-data-management" id="toc-load-some-packages-to-help-with-the-analysis-and-data-management" class="nav-link active" data-scroll-target="#load-some-packages-to-help-with-the-analysis-and-data-management"><span class="header-section-number">4.1</span> Load some packages to help with the analysis and data management</a></li>
  <li><a href="#load-in-the-data-and-use-glimpse-to-summarize-the-structure" id="toc-load-in-the-data-and-use-glimpse-to-summarize-the-structure" class="nav-link" data-scroll-target="#load-in-the-data-and-use-glimpse-to-summarize-the-structure"><span class="header-section-number">4.2</span> Load in the data and use <code>glimpse</code> to summarize the structure</a></li>
  <li>
<a href="#quick-data-cleaning-and-coding-tips" id="toc-quick-data-cleaning-and-coding-tips" class="nav-link" data-scroll-target="#quick-data-cleaning-and-coding-tips"><span class="header-section-number">4.3</span> Quick data cleaning and coding tips</a>
  <ul class="collapse">
<li><a href="#the-summary-command-from-base-r-is-a-quick-and-easy-way-to-explore-a-new-dataset" id="toc-the-summary-command-from-base-r-is-a-quick-and-easy-way-to-explore-a-new-dataset" class="nav-link" data-scroll-target="#the-summary-command-from-base-r-is-a-quick-and-easy-way-to-explore-a-new-dataset"><span class="header-section-number">4.3.1</span> The <code>summary</code> command from base R is a quick and easy way to explore a new dataset</a></li>
  <li><a href="#lets-give-some-variables-a-label" id="toc-lets-give-some-variables-a-label" class="nav-link" data-scroll-target="#lets-give-some-variables-a-label"><span class="header-section-number">4.3.2</span> Let’s give some variables a label</a></li>
  <li><a href="#lets-create-a-factor-version-of-sector-and-label-its-values" id="toc-lets-create-a-factor-version-of-sector-and-label-its-values" class="nav-link" data-scroll-target="#lets-create-a-factor-version-of-sector-and-label-its-values"><span class="header-section-number">4.3.3</span> Let’s create a factor version of <code>sector</code> and label its values</a></li>
  <li><a href="#run-summary-again-and-notice-how-it-handles-factors" id="toc-run-summary-again-and-notice-how-it-handles-factors" class="nav-link" data-scroll-target="#run-summary-again-and-notice-how-it-handles-factors"><span class="header-section-number">4.3.4</span> Run <code>summary</code> again and notice how it handles factors</a></li>
  </ul>
</li>
  <li><a href="#exploring-our-outcome-math-achievement" id="toc-exploring-our-outcome-math-achievement" class="nav-link" data-scroll-target="#exploring-our-outcome-math-achievement"><span class="header-section-number">4.4</span> Exploring our outcome, math achievement</a></li>
  <li><a href="#running-a-null-model" id="toc-running-a-null-model" class="nav-link" data-scroll-target="#running-a-null-model"><span class="header-section-number">4.5</span> Running a null model</a></li>
  <li><a href="#post-estimation-task-calculate-the-icc" id="toc-post-estimation-task-calculate-the-icc" class="nav-link" data-scroll-target="#post-estimation-task-calculate-the-icc"><span class="header-section-number">4.6</span> Post-estimation task: calculate the ICC</a></li>
  <li><a href="#using-lmertest-to-evaluate-random-effects" id="toc-using-lmertest-to-evaluate-random-effects" class="nav-link" data-scroll-target="#using-lmertest-to-evaluate-random-effects"><span class="header-section-number">4.7</span> Using <code>lmerTest</code> to evaluate random effects</a></li>
  <li><a href="#always-interesting-compare-our-mlm-to-a-regular-regression" id="toc-always-interesting-compare-our-mlm-to-a-regular-regression" class="nav-link" data-scroll-target="#always-interesting-compare-our-mlm-to-a-regular-regression"><span class="header-section-number">4.8</span> Always interesting: compare our MLM to a regular regression</a></li>
  <li><a href="#what-comes-next" id="toc-what-comes-next" class="nav-link" data-scroll-target="#what-comes-next"><span class="header-section-number">4.9</span> What comes next</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/mikediam123/mlm-textbook/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03-null-model.html">Two-Level Models</a></li><li class="breadcrumb-item"><a href="./03-null-model.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Intro to MLM and the Null Model</span></a></li></ol></nav><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">
<span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Intro to MLM and the Null Model</span>
</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p><strong>Data for this chapter:</strong> <code>hsbmerged.csv</code></p>
<p>This week we use a larger version of the HSB dataset from 1988. Same structure as before: students nested within schools. This is the same dataset Garson uses in Chapter 3, so you can recreate what he has as well.</p>
<section id="load-some-packages-to-help-with-the-analysis-and-data-management" class="level2" data-number="4.1"><h2 data-number="4.1" class="anchored" data-anchor-id="load-some-packages-to-help-with-the-analysis-and-data-management">
<span class="header-section-number">4.1</span> Load some packages to help with the analysis and data management</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://hbiostat.org/R/Hmisc/">Hmisc</a></span><span class="op">)</span>     <span class="co"># label()</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/lme4/lme4/">lme4</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/runehaubo/lmerTestR">lmerTest</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://easystats.github.io/performance/">performance</a></span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>Hmisc</code> is new here. We want it for two things: <code><a href="https://rdrr.io/pkg/Hmisc/man/label.html">label()</a></code>, which attaches a description to a variable, and its own version of <code><a href="https://rdrr.io/pkg/Hmisc/man/describe.html">describe()</a></code>, which reports more detail than the one in <code>psych</code>.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Package conflicts
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>Hmisc</code> and <code>dplyr</code> both define functions named <code>summarize</code> and <code>src</code>. Loading <code>Hmisc</code> after the tidyverse means its versions win, and you may see masking messages at load. If a tidyverse function starts behaving oddly, call it explicitly as <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">dplyr::summarize()</a></code>.</p>
</div>
</div>
</section><section id="load-in-the-data-and-use-glimpse-to-summarize-the-structure" class="level2" data-number="4.2"><h2 data-number="4.2" class="anchored" data-anchor-id="load-in-the-data-and-use-glimpse-to-summarize-the-structure">
<span class="header-section-number">4.2</span> Load in the data and use <code>glimpse</code> to summarize the structure</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">hsb</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"hsbmerged.csv"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">hsb</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 7,185
Columns: 11
$ schoolid &lt;dbl&gt; 1224, 1224, 1224, 1224, 1224, 1224, 1224, 1224, 1224, 1224, 1…
$ minority &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0…
$ female   &lt;dbl&gt; 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1…
$ ses      &lt;dbl&gt; -1.528, -0.588, -0.528, -0.668, -0.158, 0.022, -0.618, -0.998…
$ mathach  &lt;dbl&gt; 5.876, 19.708, 20.349, 8.781, 17.898, 4.583, -2.832, 0.523, 1…
$ size     &lt;dbl&gt; 842, 842, 842, 842, 842, 842, 842, 842, 842, 842, 842, 842, 8…
$ sector   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ pracad   &lt;dbl&gt; 0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0…
$ disclim  &lt;dbl&gt; 1.597, 1.597, 1.597, 1.597, 1.597, 1.597, 1.597, 1.597, 1.597…
$ himinty  &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ meanses  &lt;dbl&gt; -0.428, -0.428, -0.428, -0.428, -0.428, -0.428, -0.428, -0.42…</code></pre>
</div>
</div>
<p>7,185 students across 160 schools. <code>mathach</code> is our outcome, a standardized math achievement score, and <code>schoolid</code> identifies the school each student attends. That second variable is what makes multilevel modeling possible here.</p>
</section><section id="quick-data-cleaning-and-coding-tips" class="level2" data-number="4.3"><h2 data-number="4.3" class="anchored" data-anchor-id="quick-data-cleaning-and-coding-tips">
<span class="header-section-number">4.3</span> Quick data cleaning and coding tips</h2>
<section id="the-summary-command-from-base-r-is-a-quick-and-easy-way-to-explore-a-new-dataset" class="level3" data-number="4.3.1"><h3 data-number="4.3.1" class="anchored" data-anchor-id="the-summary-command-from-base-r-is-a-quick-and-easy-way-to-explore-a-new-dataset">
<span class="header-section-number">4.3.1</span> The <code>summary</code> command from base R is a quick and easy way to explore a new dataset</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">hsb</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    schoolid       minority          female            ses            
 Min.   :1224   Min.   :0.0000   Min.   :0.0000   Min.   :-3.7580000  
 1st Qu.:3020   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:-0.5380000  
 Median :5192   Median :0.0000   Median :1.0000   Median : 0.0020000  
 Mean   :5278   Mean   :0.2747   Mean   :0.5282   Mean   : 0.0001434  
 3rd Qu.:7342   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.: 0.6020000  
 Max.   :9586   Max.   :1.0000   Max.   :1.0000   Max.   : 2.6920000  
    mathach            size          sector           pracad      
 Min.   :-2.832   Min.   : 100   Min.   :0.0000   Min.   :0.0000  
 1st Qu.: 7.275   1st Qu.: 565   1st Qu.:0.0000   1st Qu.:0.3200  
 Median :13.131   Median :1016   Median :0.0000   Median :0.5300  
 Mean   :12.748   Mean   :1057   Mean   :0.4931   Mean   :0.5345  
 3rd Qu.:18.317   3rd Qu.:1436   3rd Qu.:1.0000   3rd Qu.:0.7000  
 Max.   :24.993   Max.   :2713   Max.   :1.0000   Max.   :1.0000  
    disclim           himinty        meanses         
 Min.   :-2.4160   Min.   :0.00   Min.   :-1.188000  
 1st Qu.:-0.8170   1st Qu.:0.00   1st Qu.:-0.317000  
 Median :-0.2310   Median :0.00   Median : 0.038000  
 Mean   :-0.1319   Mean   :0.28   Mean   : 0.006138  
 3rd Qu.: 0.4600   3rd Qu.:1.00   3rd Qu.: 0.333000  
 Max.   : 2.7560   Max.   :1.00   Max.   : 0.831000  </code></pre>
</div>
</div>
<p>Summary gives you a quick, high-level look at every variable in a dataset. It is also useful for your own records: copy and paste it into a Word file and you have something to refer back to.</p>
<p>Read it critically, though. Every column here gets a mean and quartiles, including <code>sector</code>, <code>female</code>, and <code>minority</code>, which are categories rather than quantities. The mean of <code>sector</code> is the proportion of students in one sector, which is mildly useful, but its quartiles are meaningless. This is the same issue from Chapter 1, and we are about to fix it.</p>
</section><section id="lets-give-some-variables-a-label" class="level3" data-number="4.3.2"><h3 data-number="4.3.2" class="anchored" data-anchor-id="lets-give-some-variables-a-label">
<span class="header-section-number">4.3.2</span> Let’s give some variables a label</h3>
<p>Now, data cleaning and coding. We will apply labels to two things: the variables themselves, and the values within a given variable. Both are good practice for keeping your data readable.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/Hmisc/man/label.html">label</a></span><span class="op">(</span><span class="va">hsb</span><span class="op">$</span><span class="va">mathach</span><span class="op">)</span> <span class="op">=</span> <span class="st">"Std. Math Score"</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/Hmisc/man/label.html">label</a></span><span class="op">(</span><span class="va">hsb</span><span class="op">$</span><span class="va">sector</span><span class="op">)</span> <span class="op">=</span> <span class="st">"School Sector"</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">hsb</span><span class="op">$</span><span class="va">sector</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> 'labelled' num [1:7185] 0 0 0 0 0 0 0 0 0 0 ...
 - attr(*, "label")= chr "School Sector"</code></pre>
</div>
</div>
<p>The <code><a href="https://rdrr.io/r/utils/str.html">str()</a></code> output now shows the label attached to the variable. This carries through to <code><a href="https://rdrr.io/pkg/Hmisc/man/describe.html">Hmisc::describe()</a></code> output and to some plotting functions, which means a table six months from now still says “Std. Math Score” rather than <code>mathach</code>.</p>
</section><section id="lets-create-a-factor-version-of-sector-and-label-its-values" class="level3" data-number="4.3.3"><h3 data-number="4.3.3" class="anchored" data-anchor-id="lets-create-a-factor-version-of-sector-and-label-its-values">
<span class="header-section-number">4.3.3</span> Let’s create a factor version of <code>sector</code> and label its values</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">hsb.clean</span> <span class="op">&lt;-</span> <span class="va">hsb</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="va">.</span>,</span>
<span>         sector.factor <span class="op">=</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/as_factor.html">as_factor</a></span><span class="op">(</span><span class="va">sector</span><span class="op">)</span>,</span>
<span>         female.factor <span class="op">=</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/as_factor.html">as_factor</a></span><span class="op">(</span><span class="va">female</span><span class="op">)</span>,</span>
<span>         minority.factor <span class="op">=</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/as_factor.html">as_factor</a></span><span class="op">(</span><span class="va">minority</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">hsb.clean</span><span class="op">$</span><span class="va">sector.factor</span><span class="op">)</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Public"</span>, <span class="st">"Parochial"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">hsb.clean</span><span class="op">$</span><span class="va">female.factor</span><span class="op">)</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Male"</span>, <span class="st">"Female"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">hsb.clean</span><span class="op">$</span><span class="va">minority.factor</span><span class="op">)</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Non-Minority"</span>, <span class="st">"Minority"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">hsb.clean</span><span class="op">$</span><span class="va">sector.factor</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 2 levels "Public","Parochial": 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
</div>
<p>Two steps here, and it is worth separating them. <code><a href="https://forcats.tidyverse.org/reference/as_factor.html">as_factor()</a></code> converts the numeric variable into a factor, so R treats it as a category. Assigning to <code><a href="https://rdrr.io/r/base/levels.html">levels()</a></code> then renames those categories from 0 and 1 into words.</p>
<p>Order matters when you assign levels this way. The names are applied in the order R already has the levels in, so <code>c("Public", "Parochial")</code> assumes 0 comes first. Always check the result:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">hsb.clean</span><span class="op">$</span><span class="va">sector.factor</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   Public Parochial 
     3642      3543 </code></pre>
</div>
</div>
<p>3,642 public and 3,543 Parochial. If those counts had come out reversed from what you expected, the labels went on backwards, and every result from here forward would be silently mislabeled.</p>
</section><section id="run-summary-again-and-notice-how-it-handles-factors" class="level3" data-number="4.3.4"><h3 data-number="4.3.4" class="anchored" data-anchor-id="run-summary-again-and-notice-how-it-handles-factors">
<span class="header-section-number">4.3.4</span> Run <code>summary</code> again and notice how it handles factors</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">hsb.clean</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    schoolid       minority          female            ses            
 Min.   :1224   Min.   :0.0000   Min.   :0.0000   Min.   :-3.7580000  
 1st Qu.:3020   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:-0.5380000  
 Median :5192   Median :0.0000   Median :1.0000   Median : 0.0020000  
 Mean   :5278   Mean   :0.2747   Mean   :0.5282   Mean   : 0.0001434  
 3rd Qu.:7342   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.: 0.6020000  
 Max.   :9586   Max.   :1.0000   Max.   :1.0000   Max.   : 2.6920000  
    mathach            size          sector           pracad      
 Min.   :-2.832   Min.   : 100   Min.   :0.0000   Min.   :0.0000  
 1st Qu.: 7.275   1st Qu.: 565   1st Qu.:0.0000   1st Qu.:0.3200  
 Median :13.131   Median :1016   Median :0.0000   Median :0.5300  
 Mean   :12.748   Mean   :1057   Mean   :0.4931   Mean   :0.5345  
 3rd Qu.:18.317   3rd Qu.:1436   3rd Qu.:1.0000   3rd Qu.:0.7000  
 Max.   :24.993   Max.   :2713   Max.   :1.0000   Max.   :1.0000  
    disclim           himinty        meanses            sector.factor 
 Min.   :-2.4160   Min.   :0.00   Min.   :-1.188000   Public   :3642  
 1st Qu.:-0.8170   1st Qu.:0.00   1st Qu.:-0.317000   Parochial:3543  
 Median :-0.2310   Median :0.00   Median : 0.038000                   
 Mean   :-0.1319   Mean   :0.28   Mean   : 0.006138                   
 3rd Qu.: 0.4600   3rd Qu.:1.00   3rd Qu.: 0.333000                   
 Max.   : 2.7560   Max.   :1.00   Max.   : 0.831000                   
 female.factor     minority.factor
 Male  :3390   Non-Minority:5211  
 Female:3795   Minority    :1974  
                                  
                                  
                                  
                                  </code></pre>
</div>
</div>
<p>Compare this to the earlier output. The factor versions of the variables no longer report meaningless means and quartiles. Instead they report counts per category, which is what you actually want to know. Same data, same function, but R now understands what kind of variable it is looking at.</p>
</section></section><section id="exploring-our-outcome-math-achievement" class="level2" data-number="4.4"><h2 data-number="4.4" class="anchored" data-anchor-id="exploring-our-outcome-math-achievement">
<span class="header-section-number">4.4</span> Exploring our outcome, math achievement</h2>
<p>Now let’s look at <code>mathach</code> using the <code>describe</code> function from the <code>Hmisc</code> package:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/Hmisc/man/describe.html">describe</a></span><span class="op">(</span><span class="va">hsb.clean</span><span class="op">$</span><span class="va">mathach</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>hsb.clean$mathach : Std. Math Score 
       n  missing distinct     Info     Mean  pMedian      Gmd      .05 
    7185        0     6031        1    12.75    12.85     7.91    1.210 
     .10      .25      .50      .75      .90      .95 
   3.301    7.275   13.131   18.317   22.016   23.123 

lowest : -2.832 -2.83  -2.721 -2.658 -2.657, highest: 24.677 24.707 24.812 24.869 24.993</code></pre>
</div>
</div>
<p><code><a href="https://rdrr.io/pkg/Hmisc/man/describe.html">Hmisc::describe()</a></code> reports more than the <code>psych</code> version: distinct values, several percentiles, and the five lowest and highest observations. That last part is a quiet outlier check. If the highest values were 24, 25, and 9999, you would see it here.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/hist.html">hist</a></span><span class="op">(</span><span class="va">hsb.clean</span><span class="op">$</span><span class="va">mathach</span>,</span>
<span>     main <span class="op">=</span> <span class="st">"Distribution of Math Achievement Scores"</span>,</span>
<span>     sub <span class="op">=</span> <span class="st">"N = 7,185. Students from the High School and Beyond Survey (1988)."</span>,</span>
<span>     xlab <span class="op">=</span> <span class="st">"Standardized Math Achievement Score"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-mathach" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-mathach-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-null-model_files/figure-html/fig-mathach-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mathach-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.1: Distribution of math achievement scores.
</figcaption></figure>
</div>
</div>
</div>
<p>This histogram describes students in general, which is useful but hides the thing we actually care about. The question motivating multilevel modeling is whether <em>schools</em> differ. One quick way to see it is to plot school averages instead of individual scores:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">school_means</span> <span class="op">&lt;-</span> <span class="va">hsb.clean</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">schoolid</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>school_mean <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">mathach</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/hist.html">hist</a></span><span class="op">(</span><span class="va">school_means</span><span class="op">$</span><span class="va">school_mean</span>,</span>
<span>     main <span class="op">=</span> <span class="st">"School Average Math Achievement"</span>,</span>
<span>     sub <span class="op">=</span> <span class="st">"Each observation is one of 160 schools."</span>,</span>
<span>     xlab <span class="op">=</span> <span class="st">"School mean math achievement"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-schoolmeans" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-schoolmeans-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03-null-model_files/figure-html/fig-schoolmeans-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-schoolmeans-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.2: Average math achievement across the 160 schools.
</figcaption></figure>
</div>
</div>
</div>
<p>If every school had the same average, this would be a single narrow spike. It is not, and that spread is exactly what the null model is about to quantify.</p>
</section><section id="running-a-null-model" class="level2" data-number="4.5"><h2 data-number="4.5" class="anchored" data-anchor-id="running-a-null-model">
<span class="header-section-number">4.5</span> Running a null model</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model.null</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">mathach</span> <span class="op">~</span> <span class="op">(</span><span class="fl">1</span><span class="op">|</span><span class="va">schoolid</span><span class="op">)</span>, REML <span class="op">=</span> <span class="cn">FALSE</span>, data <span class="op">=</span> <span class="va">hsb.clean</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">model.null</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite's
  method [lmerModLmerTest]
Formula: mathach ~ (1 | schoolid)
   Data: hsb.clean

      AIC       BIC    logLik -2*log(L)  df.resid 
  47121.8   47142.4  -23557.9   47115.8      7182 

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-3.06262 -0.75365  0.02676  0.76070  2.74184 

Random effects:
 Groups   Name        Variance Std.Dev.
 schoolid (Intercept)  8.553   2.925   
 Residual             39.148   6.257   
Number of obs: 7185, groups:  schoolid, 160

Fixed effects:
            Estimate Std. Error       df t value Pr(&gt;|t|)    
(Intercept)  12.6371     0.2436 157.6209   51.87   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The <code>(1|schoolid)</code> term is what makes this multilevel. It tells <code><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer()</a></code> to estimate a separate intercept for each school, drawn from a distribution whose variance we want to estimate.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>What makes <code>schoolid</code> a clustering variable, and what does not
</div>
</div>
<div class="callout-body-container callout-body">
<p>This is the most common early mistake, so it is worth stopping on. Nearly every dataset has categorical variables, and almost none of them belong inside <code>(1 | ... )</code>. Before writing that term, ask three questions.</p>
<p><strong>How many units are there?</strong> A random intercept does not estimate a set of group means. It estimates a <em>variance</em>, and it does so from as many observations as there are groups. Estimating a variance from nine numbers is exactly as unreliable as it sounds. Common guidance wants 30 to 50 level-2 units for reasonable precision, with roughly 20 as a floor below which the estimate should not be trusted. We have 160 schools, which is comfortable.</p>
<p><strong>Are these units a sample from a population you want to generalize to?</strong> This is the conceptual heart of it. Random effects treat groups as draws from a population of groups, so your conclusions extend to schools you did not observe. These 160 schools are a sample of American high schools. By contrast, a variable like <code>sector</code> has two categories that are not a sample of anything; they are the complete set. There is no larger population of sectors to infer toward.</p>
<p><strong>Do you want group-specific effects, or the variation among groups?</strong> If you want to know how each category differs, that is a fixed effect: put it on the right side of the <code>~</code> like any other predictor. If you want to know how much groups vary as a class, and to generalize beyond the ones you have, that is a random effect.</p>
<p>So in this dataset, <code>schoolid</code> goes in the random part and <code>sector</code>, <code>female</code>, and <code>minority</code> go in the fixed part. Sex has two categories. Treatment condition has two. Region usually has four. None of those are clustering variables, however naturally the data seem to group by them.</p>
<p>R will not stop you from writing <code>(1 | sector)</code>. It will return a variance component and standard errors and flag nothing at all. The number will simply not mean what you think it means.</p>
</div>
</div>
<p>Two numbers in the Random effects section carry the story. The variance associated with <code>schoolid</code> is the between-school variance, written <span class="math inline">\tau_{00}</span>. The Residual variance is the within-school, student-level variance, written <span class="math inline">\sigma^2</span>.</p>
<p>You also get AIC and BIC, two very common information criterion measures used to assess model fit.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Why <code>REML = FALSE</code>?
</div>
</div>
<div class="callout-body-container callout-body">
<p><code><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer()</a></code> can estimate a model two ways. Restricted maximum likelihood (REML), the default, gives less biased variance components, especially with few level-2 units. Maximum likelihood (ML), which <code>REML = FALSE</code> requests, is required whenever you compare models that differ in their <em>fixed</em> effects, because REML likelihoods are not comparable across different fixed-effect specifications.</p>
<p>This book uses ML throughout so that numbers stay consistent from one page to the next and model comparisons are always valid. With 160 schools, the difference between the two is small.</p>
</div>
</div>
</section><section id="post-estimation-task-calculate-the-icc" class="level2" data-number="4.6"><h2 data-number="4.6" class="anchored" data-anchor-id="post-estimation-task-calculate-the-icc">
<span class="header-section-number">4.6</span> Post-estimation task: calculate the ICC</h2>
<p>These commands are run after any kind of MLM. They are called post-estimation commands because they require that the model be saved in memory. If you do something else and then try to run them, you will likely get an error.</p>
<p>The intraclass correlation is the proportion of total variance lying between schools:</p>
<p><span class="math display">\text{ICC} = \frac{\tau_{00}}{\tau_{00} + \sigma^2}</span></p>
<p>Here’s a quick and easy way to get our friend the ICC:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">null.ICC</span> <span class="op">&lt;-</span> <span class="fl">8.553</span><span class="op">/</span><span class="op">(</span><span class="fl">8.553</span> <span class="op">+</span> <span class="fl">39.148</span><span class="op">)</span></span>
<span><span class="va">null.ICC</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1793044</code></pre>
</div>
</div>
<p>Roughly 18 percent of the variation in math achievement is between schools. Put another way, two students from the same school are noticeably more similar to each other than two students drawn at random from the full sample. That is the condition that makes ordinary regression standard errors too small.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Pulling the numbers out rather than typing them
</div>
</div>
<div class="callout-body-container callout-body">
<p>Typing the variance components by hand works and makes the formula visible, which is why it is worth doing once. For your own analyses it is safer to extract them from the model, since a transposed digit produces a plausible-looking wrong answer:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">vc</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/nlme/man/VarCorr.html">VarCorr</a></span><span class="op">(</span><span class="va">model.null</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">tau00</span>  <span class="op">&lt;-</span> <span class="va">vc</span><span class="op">$</span><span class="va">vcov</span><span class="op">[</span><span class="va">vc</span><span class="op">$</span><span class="va">grp</span> <span class="op">==</span> <span class="st">"schoolid"</span><span class="op">]</span></span>
<span><span class="va">sigma2</span> <span class="op">&lt;-</span> <span class="va">vc</span><span class="op">$</span><span class="va">vcov</span><span class="op">[</span><span class="va">vc</span><span class="op">$</span><span class="va">grp</span> <span class="op">==</span> <span class="st">"Residual"</span><span class="op">]</span></span>
<span></span>
<span><span class="va">tau00</span> <span class="op">/</span> <span class="op">(</span><span class="va">tau00</span> <span class="op">+</span> <span class="va">sigma2</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1793109</code></pre>
</div>
</div>
<p>The <code>performance</code> package will also compute it directly with <code>performance::icc(model.null)</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">performance</span><span class="fu">::</span><span class="fu"><a href="https://easystats.github.io/performance/reference/icc.html">icc</a></span><span class="op">(</span><span class="va">model.null</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Intraclass Correlation Coefficient

    Adjusted ICC: 0.179
  Unadjusted ICC: 0.179</code></pre>
</div>
</div>
</div>
</div>
</section><section id="using-lmertest-to-evaluate-random-effects" class="level2" data-number="4.7"><h2 data-number="4.7" class="anchored" data-anchor-id="using-lmertest-to-evaluate-random-effects">
<span class="header-section-number">4.7</span> Using <code>lmerTest</code> to evaluate random effects</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/lmerTest/man/ranova.html">ranova</a></span><span class="op">(</span><span class="va">model.null</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>ANOVA-like table for random-effects: Single term deletions

Model:
mathach ~ 1 + (1 | schoolid)
               npar logLik   AIC    LRT Df Pr(&gt;Chisq)    
&lt;none&gt;            3 -23558 47122                         
(1 | schoolid)    2 -24050 48104 983.92  1  &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>This is a likelihood ratio test comparing our model to one without the random intercept. A significant result says that letting schools have their own intercepts improves fit enough to justify the extra parameter.</p>
<p>Read it alongside the ICC rather than instead of it. The test tells you whether school-level variance is distinguishable from zero; the ICC tells you how much of it there is. With 7,185 students you have enough power to detect quite small amounts of clustering, so significance alone is weak evidence that multilevel modeling matters substantively.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span><code><a href="https://rdrr.io/pkg/lmerTest/man/ranova.html">rand()</a></code> became <code><a href="https://rdrr.io/pkg/lmerTest/man/ranova.html">ranova()</a></code>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Older handouts call <code><a href="https://rdrr.io/pkg/lmerTest/man/ranova.html">lmerTest::rand()</a></code>. The function was renamed to <code><a href="https://rdrr.io/pkg/lmerTest/man/ranova.html">ranova()</a></code> several versions ago. The old name may still work but is no longer the documented one.</p>
</div>
</div>
</section><section id="always-interesting-compare-our-mlm-to-a-regular-regression" class="level2" data-number="4.8"><h2 data-number="4.8" class="anchored" data-anchor-id="always-interesting-compare-our-mlm-to-a-regular-regression">
<span class="header-section-number">4.8</span> Always interesting: compare our MLM to a regular regression</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model.regular</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">mathach</span> <span class="op">~</span> <span class="cn">NULL</span>, data <span class="op">=</span> <span class="va">hsb.clean</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">model.regular</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mathach ~ NULL, data = hsb.clean)

Residuals:
Std. Math Score 
     Min       1Q   Median       3Q      Max 
-15.5799  -5.4729   0.3831   5.5691  12.2451 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 12.74785    0.08115   157.1   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.878 on 7184 degrees of freedom</code></pre>
</div>
</div>
<p>The intercept estimates are similar, which is expected in a null model. What differs is the standard error, and that difference is the entire practical argument for multilevel modeling. Ordinary regression treats 7,185 students as 7,185 independent pieces of information, when students within a school share teachers, curricula, neighborhoods, and funding. The result is standard errors that are too small and p-values that are too optimistic.</p>
<p>One last point students routinely get wrong. The fixed-effect intercept in the null model is not simply the mean of all 7,185 scores. It estimates the average of the <em>school</em> means, weighting schools by how much information each contributes. With balanced data the two are close; with unbalanced data they differ, and the multilevel estimate is usually the one you want.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">hsb.clean</span><span class="op">$</span><span class="va">mathach</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>   <span class="co"># grand mean of all students</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.74785</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/nlme/man/fixed.effects.html">fixef</a></span><span class="op">(</span><span class="va">model.null</span><span class="op">)</span>                       <span class="co"># model-based estimate</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   12.63707 </code></pre>
</div>
</div>
</section><section id="what-comes-next" class="level2" data-number="4.9"><h2 data-number="4.9" class="anchored" data-anchor-id="what-comes-next">
<span class="header-section-number">4.9</span> What comes next</h2>
<p>The null model tells us schools differ. It does not tell us why. The next chapter starts adding predictors, at both the student and school levels, to explain some of the variance we just found.</p>


<!-- -->

</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./02-regression-review.html" class="pagination-link" aria-label="Review of Linear Regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Review of Linear Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./04-random-intercept.html" class="pagination-link" aria-label="Conditional Random Intercept Models">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Conditional Random Intercept Models</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb34" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Intro to MLM and the Null Model</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>**Data for this chapter:** <span class="in">`hsbmerged.csv`</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>This week we use a larger version of the HSB dataset from 1988. Same structure as before: students nested within schools. This is the same dataset Garson uses in Chapter 3, so you can recreate what he has as well.</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="fu">## Load some packages to help with the analysis and data management</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hmisc)     <span class="co"># label()</span></span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmerTest)</span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a><span class="in">`Hmisc`</span> is new here. We want it for two things: <span class="in">`label()`</span>, which attaches a description to a variable, and its own version of <span class="in">`describe()`</span>, which reports more detail than the one in <span class="in">`psych`</span>.</span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-24"><a href="#cb34-24" aria-hidden="true" tabindex="-1"></a>::: {.callout-warning}</span>
<span id="cb34-25"><a href="#cb34-25" aria-hidden="true" tabindex="-1"></a><span class="fu">## Package conflicts</span></span>
<span id="cb34-26"><a href="#cb34-26" aria-hidden="true" tabindex="-1"></a><span class="in">`Hmisc`</span> and <span class="in">`dplyr`</span> both define functions named <span class="in">`summarize`</span> and <span class="in">`src`</span>. Loading <span class="in">`Hmisc`</span> after the tidyverse means its versions win, and you may see masking messages at load. If a tidyverse function starts behaving oddly, call it explicitly as <span class="in">`dplyr::summarize()`</span>.</span>
<span id="cb34-27"><a href="#cb34-27" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb34-28"><a href="#cb34-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-29"><a href="#cb34-29" aria-hidden="true" tabindex="-1"></a><span class="fu">## Load in the data and use `glimpse` to summarize the structure</span></span>
<span id="cb34-30"><a href="#cb34-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-33"><a href="#cb34-33" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-34"><a href="#cb34-34" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb34-35"><a href="#cb34-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-36"><a href="#cb34-36" aria-hidden="true" tabindex="-1"></a>hsb <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"hsbmerged.csv"</span>)</span>
<span id="cb34-37"><a href="#cb34-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-38"><a href="#cb34-38" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(hsb)</span>
<span id="cb34-39"><a href="#cb34-39" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-40"><a href="#cb34-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-41"><a href="#cb34-41" aria-hidden="true" tabindex="-1"></a>7,185 students across 160 schools. <span class="in">`mathach`</span> is our outcome, a standardized math achievement score, and <span class="in">`schoolid`</span> identifies the school each student attends. That second variable is what makes multilevel modeling possible here.</span>
<span id="cb34-42"><a href="#cb34-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-43"><a href="#cb34-43" aria-hidden="true" tabindex="-1"></a><span class="fu">## Quick data cleaning and coding tips</span></span>
<span id="cb34-44"><a href="#cb34-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-45"><a href="#cb34-45" aria-hidden="true" tabindex="-1"></a><span class="fu">### The `summary` command from base R is a quick and easy way to explore a new dataset</span></span>
<span id="cb34-46"><a href="#cb34-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-49"><a href="#cb34-49" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-50"><a href="#cb34-50" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hsb)</span>
<span id="cb34-51"><a href="#cb34-51" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-52"><a href="#cb34-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-53"><a href="#cb34-53" aria-hidden="true" tabindex="-1"></a>Summary gives you a quick, high-level look at every variable in a dataset. It is also useful for your own records: copy and paste it into a Word file and you have something to refer back to.</span>
<span id="cb34-54"><a href="#cb34-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-55"><a href="#cb34-55" aria-hidden="true" tabindex="-1"></a>Read it critically, though. Every column here gets a mean and quartiles, including <span class="in">`sector`</span>, <span class="in">`female`</span>, and <span class="in">`minority`</span>, which are categories rather than quantities. The mean of <span class="in">`sector`</span> is the proportion of students in one sector, which is mildly useful, but its quartiles are meaningless. This is the same issue from Chapter 1, and we are about to fix it.</span>
<span id="cb34-56"><a href="#cb34-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-57"><a href="#cb34-57" aria-hidden="true" tabindex="-1"></a><span class="fu">### Let's give some variables a label</span></span>
<span id="cb34-58"><a href="#cb34-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-59"><a href="#cb34-59" aria-hidden="true" tabindex="-1"></a>Now, data cleaning and coding. We will apply labels to two things: the variables themselves, and the values within a given variable. Both are good practice for keeping your data readable.</span>
<span id="cb34-60"><a href="#cb34-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-63"><a href="#cb34-63" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-64"><a href="#cb34-64" aria-hidden="true" tabindex="-1"></a><span class="fu">label</span>(hsb<span class="sc">$</span>mathach) <span class="ot">=</span> <span class="st">"Std. Math Score"</span></span>
<span id="cb34-65"><a href="#cb34-65" aria-hidden="true" tabindex="-1"></a><span class="fu">label</span>(hsb<span class="sc">$</span>sector) <span class="ot">=</span> <span class="st">"School Sector"</span></span>
<span id="cb34-66"><a href="#cb34-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-67"><a href="#cb34-67" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(hsb<span class="sc">$</span>sector)</span>
<span id="cb34-68"><a href="#cb34-68" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-69"><a href="#cb34-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-70"><a href="#cb34-70" aria-hidden="true" tabindex="-1"></a>The <span class="in">`str()`</span> output now shows the label attached to the variable. This carries through to <span class="in">`Hmisc::describe()`</span> output and to some plotting functions, which means a table six months from now still says "Std. Math Score" rather than <span class="in">`mathach`</span>.</span>
<span id="cb34-71"><a href="#cb34-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-72"><a href="#cb34-72" aria-hidden="true" tabindex="-1"></a><span class="fu">### Let's create a factor version of `sector` and label its values</span></span>
<span id="cb34-73"><a href="#cb34-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-76"><a href="#cb34-76" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-77"><a href="#cb34-77" aria-hidden="true" tabindex="-1"></a>hsb.clean <span class="ot">&lt;-</span> hsb <span class="sc">%&gt;%</span></span>
<span id="cb34-78"><a href="#cb34-78" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(.,</span>
<span id="cb34-79"><a href="#cb34-79" aria-hidden="true" tabindex="-1"></a>         <span class="at">sector.factor =</span> <span class="fu">as_factor</span>(sector),</span>
<span id="cb34-80"><a href="#cb34-80" aria-hidden="true" tabindex="-1"></a>         <span class="at">female.factor =</span> <span class="fu">as_factor</span>(female),</span>
<span id="cb34-81"><a href="#cb34-81" aria-hidden="true" tabindex="-1"></a>         <span class="at">minority.factor =</span> <span class="fu">as_factor</span>(minority))</span>
<span id="cb34-82"><a href="#cb34-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-83"><a href="#cb34-83" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(hsb.clean<span class="sc">$</span>sector.factor) <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Public"</span>, <span class="st">"Parochial"</span>)</span>
<span id="cb34-84"><a href="#cb34-84" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(hsb.clean<span class="sc">$</span>female.factor) <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Male"</span>, <span class="st">"Female"</span>)</span>
<span id="cb34-85"><a href="#cb34-85" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(hsb.clean<span class="sc">$</span>minority.factor) <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Non-Minority"</span>, <span class="st">"Minority"</span>)</span>
<span id="cb34-86"><a href="#cb34-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-87"><a href="#cb34-87" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(hsb.clean<span class="sc">$</span>sector.factor)</span>
<span id="cb34-88"><a href="#cb34-88" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-89"><a href="#cb34-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-90"><a href="#cb34-90" aria-hidden="true" tabindex="-1"></a>Two steps here, and it is worth separating them. <span class="in">`as_factor()`</span> converts the numeric variable into a factor, so R treats it as a category. Assigning to <span class="in">`levels()`</span> then renames those categories from 0 and 1 into words.</span>
<span id="cb34-91"><a href="#cb34-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-92"><a href="#cb34-92" aria-hidden="true" tabindex="-1"></a>Order matters when you assign levels this way. The names are applied in the order R already has the levels in, so <span class="in">`c("Public", "Parochial")`</span> assumes 0 comes first. Always check the result:</span>
<span id="cb34-93"><a href="#cb34-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-96"><a href="#cb34-96" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-97"><a href="#cb34-97" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(hsb.clean<span class="sc">$</span>sector.factor)</span>
<span id="cb34-98"><a href="#cb34-98" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-99"><a href="#cb34-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-100"><a href="#cb34-100" aria-hidden="true" tabindex="-1"></a>3,642 public and 3,543 Parochial. If those counts had come out reversed from what you expected, the labels went on backwards, and every result from here forward would be silently mislabeled.</span>
<span id="cb34-101"><a href="#cb34-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-102"><a href="#cb34-102" aria-hidden="true" tabindex="-1"></a><span class="fu">### Run `summary` again and notice how it handles factors</span></span>
<span id="cb34-103"><a href="#cb34-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-106"><a href="#cb34-106" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-107"><a href="#cb34-107" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hsb.clean)</span>
<span id="cb34-108"><a href="#cb34-108" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-109"><a href="#cb34-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-110"><a href="#cb34-110" aria-hidden="true" tabindex="-1"></a>Compare this to the earlier output. The factor versions of the variables no longer report meaningless means and quartiles. Instead they report counts per category, which is what you actually want to know. Same data, same function, but R now understands what kind of variable it is looking at.</span>
<span id="cb34-111"><a href="#cb34-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-112"><a href="#cb34-112" aria-hidden="true" tabindex="-1"></a><span class="fu">## Exploring our outcome, math achievement</span></span>
<span id="cb34-113"><a href="#cb34-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-114"><a href="#cb34-114" aria-hidden="true" tabindex="-1"></a>Now let's look at <span class="in">`mathach`</span> using the <span class="in">`describe`</span> function from the <span class="in">`Hmisc`</span> package:</span>
<span id="cb34-115"><a href="#cb34-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-118"><a href="#cb34-118" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-119"><a href="#cb34-119" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span>(hsb.clean<span class="sc">$</span>mathach)</span>
<span id="cb34-120"><a href="#cb34-120" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-121"><a href="#cb34-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-122"><a href="#cb34-122" aria-hidden="true" tabindex="-1"></a><span class="in">`Hmisc::describe()`</span> reports more than the <span class="in">`psych`</span> version: distinct values, several percentiles, and the five lowest and highest observations. That last part is a quiet outlier check. If the highest values were 24, 25, and 9999, you would see it here.</span>
<span id="cb34-123"><a href="#cb34-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-126"><a href="#cb34-126" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-127"><a href="#cb34-127" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-mathach</span></span>
<span id="cb34-128"><a href="#cb34-128" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Distribution of math achievement scores."</span></span>
<span id="cb34-129"><a href="#cb34-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-130"><a href="#cb34-130" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(hsb.clean<span class="sc">$</span>mathach,</span>
<span id="cb34-131"><a href="#cb34-131" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Distribution of Math Achievement Scores"</span>,</span>
<span id="cb34-132"><a href="#cb34-132" aria-hidden="true" tabindex="-1"></a>     <span class="at">sub =</span> <span class="st">"N = 7,185. Students from the High School and Beyond Survey (1988)."</span>,</span>
<span id="cb34-133"><a href="#cb34-133" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Standardized Math Achievement Score"</span>)</span>
<span id="cb34-134"><a href="#cb34-134" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-135"><a href="#cb34-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-136"><a href="#cb34-136" aria-hidden="true" tabindex="-1"></a>This histogram describes students in general, which is useful but hides the thing we actually care about. The question motivating multilevel modeling is whether *schools* differ. One quick way to see it is to plot school averages instead of individual scores:</span>
<span id="cb34-137"><a href="#cb34-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-140"><a href="#cb34-140" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-141"><a href="#cb34-141" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-schoolmeans</span></span>
<span id="cb34-142"><a href="#cb34-142" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Average math achievement across the 160 schools."</span></span>
<span id="cb34-143"><a href="#cb34-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-144"><a href="#cb34-144" aria-hidden="true" tabindex="-1"></a>school_means <span class="ot">&lt;-</span> hsb.clean <span class="sc">%&gt;%</span></span>
<span id="cb34-145"><a href="#cb34-145" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(schoolid) <span class="sc">%&gt;%</span></span>
<span id="cb34-146"><a href="#cb34-146" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">school_mean =</span> <span class="fu">mean</span>(mathach, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb34-147"><a href="#cb34-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-148"><a href="#cb34-148" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(school_means<span class="sc">$</span>school_mean,</span>
<span id="cb34-149"><a href="#cb34-149" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"School Average Math Achievement"</span>,</span>
<span id="cb34-150"><a href="#cb34-150" aria-hidden="true" tabindex="-1"></a>     <span class="at">sub =</span> <span class="st">"Each observation is one of 160 schools."</span>,</span>
<span id="cb34-151"><a href="#cb34-151" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"School mean math achievement"</span>)</span>
<span id="cb34-152"><a href="#cb34-152" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-153"><a href="#cb34-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-154"><a href="#cb34-154" aria-hidden="true" tabindex="-1"></a>If every school had the same average, this would be a single narrow spike. It is not, and that spread is exactly what the null model is about to quantify.</span>
<span id="cb34-155"><a href="#cb34-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-156"><a href="#cb34-156" aria-hidden="true" tabindex="-1"></a><span class="fu">## Running a null model</span></span>
<span id="cb34-157"><a href="#cb34-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-160"><a href="#cb34-160" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-161"><a href="#cb34-161" aria-hidden="true" tabindex="-1"></a>model.null <span class="ot">&lt;-</span> <span class="fu">lmer</span>(mathach <span class="sc">~</span> (<span class="dv">1</span><span class="sc">|</span>schoolid), <span class="at">REML =</span> <span class="cn">FALSE</span>, <span class="at">data =</span> hsb.clean)</span>
<span id="cb34-162"><a href="#cb34-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-163"><a href="#cb34-163" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.null)</span>
<span id="cb34-164"><a href="#cb34-164" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-165"><a href="#cb34-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-166"><a href="#cb34-166" aria-hidden="true" tabindex="-1"></a>The <span class="in">`(1|schoolid)`</span> term is what makes this multilevel. It tells <span class="in">`lmer()`</span> to estimate a separate intercept for each school, drawn from a distribution whose variance we want to estimate.</span>
<span id="cb34-167"><a href="#cb34-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-168"><a href="#cb34-168" aria-hidden="true" tabindex="-1"></a>::: {.callout-important}</span>
<span id="cb34-169"><a href="#cb34-169" aria-hidden="true" tabindex="-1"></a><span class="fu">## What makes `schoolid` a clustering variable, and what does not</span></span>
<span id="cb34-170"><a href="#cb34-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-171"><a href="#cb34-171" aria-hidden="true" tabindex="-1"></a>This is the most common early mistake, so it is worth stopping on. Nearly every dataset has categorical variables, and almost none of them belong inside <span class="in">`(1 | ... )`</span>. Before writing that term, ask three questions.</span>
<span id="cb34-172"><a href="#cb34-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-173"><a href="#cb34-173" aria-hidden="true" tabindex="-1"></a>**How many units are there?** A random intercept does not estimate a set of group means. It estimates a *variance*, and it does so from as many observations as there are groups. Estimating a variance from nine numbers is exactly as unreliable as it sounds. Common guidance wants 30 to 50 level-2 units for reasonable precision, with roughly 20 as a floor below which the estimate should not be trusted. We have 160 schools, which is comfortable.</span>
<span id="cb34-174"><a href="#cb34-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-175"><a href="#cb34-175" aria-hidden="true" tabindex="-1"></a>**Are these units a sample from a population you want to generalize to?** This is the conceptual heart of it. Random effects treat groups as draws from a population of groups, so your conclusions extend to schools you did not observe. These 160 schools are a sample of American high schools. By contrast, a variable like <span class="in">`sector`</span> has two categories that are not a sample of anything; they are the complete set. There is no larger population of sectors to infer toward.</span>
<span id="cb34-176"><a href="#cb34-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-177"><a href="#cb34-177" aria-hidden="true" tabindex="-1"></a>**Do you want group-specific effects, or the variation among groups?** If you want to know how each category differs, that is a fixed effect: put it on the right side of the <span class="in">`~`</span> like any other predictor. If you want to know how much groups vary as a class, and to generalize beyond the ones you have, that is a random effect.</span>
<span id="cb34-178"><a href="#cb34-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-179"><a href="#cb34-179" aria-hidden="true" tabindex="-1"></a>So in this dataset, <span class="in">`schoolid`</span> goes in the random part and <span class="in">`sector`</span>, <span class="in">`female`</span>, and <span class="in">`minority`</span> go in the fixed part. Sex has two categories. Treatment condition has two. Region usually has four. None of those are clustering variables, however naturally the data seem to group by them.</span>
<span id="cb34-180"><a href="#cb34-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-181"><a href="#cb34-181" aria-hidden="true" tabindex="-1"></a>R will not stop you from writing <span class="in">`(1 | sector)`</span>. It will return a variance component and standard errors and flag nothing at all. The number will simply not mean what you think it means.</span>
<span id="cb34-182"><a href="#cb34-182" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb34-183"><a href="#cb34-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-184"><a href="#cb34-184" aria-hidden="true" tabindex="-1"></a>Two numbers in the Random effects section carry the story. The variance associated with <span class="in">`schoolid`</span> is the between-school variance, written $\tau_{00}$. The Residual variance is the within-school, student-level variance, written $\sigma^2$.</span>
<span id="cb34-185"><a href="#cb34-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-186"><a href="#cb34-186" aria-hidden="true" tabindex="-1"></a>You also get AIC and BIC, two very common information criterion measures used to assess model fit.</span>
<span id="cb34-187"><a href="#cb34-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-188"><a href="#cb34-188" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb34-189"><a href="#cb34-189" aria-hidden="true" tabindex="-1"></a><span class="fu">## Why `REML = FALSE`?</span></span>
<span id="cb34-190"><a href="#cb34-190" aria-hidden="true" tabindex="-1"></a><span class="in">`lmer()`</span> can estimate a model two ways. Restricted maximum likelihood (REML), the default, gives less biased variance components, especially with few level-2 units. Maximum likelihood (ML), which <span class="in">`REML = FALSE`</span> requests, is required whenever you compare models that differ in their *fixed* effects, because REML likelihoods are not comparable across different fixed-effect specifications.</span>
<span id="cb34-191"><a href="#cb34-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-192"><a href="#cb34-192" aria-hidden="true" tabindex="-1"></a>This book uses ML throughout so that numbers stay consistent from one page to the next and model comparisons are always valid. With 160 schools, the difference between the two is small.</span>
<span id="cb34-193"><a href="#cb34-193" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb34-194"><a href="#cb34-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-195"><a href="#cb34-195" aria-hidden="true" tabindex="-1"></a><span class="fu">## Post-estimation task: calculate the ICC</span></span>
<span id="cb34-196"><a href="#cb34-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-197"><a href="#cb34-197" aria-hidden="true" tabindex="-1"></a>These commands are run after any kind of MLM. They are called post-estimation commands because they require that the model be saved in memory. If you do something else and then try to run them, you will likely get an error.</span>
<span id="cb34-198"><a href="#cb34-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-199"><a href="#cb34-199" aria-hidden="true" tabindex="-1"></a>The intraclass correlation is the proportion of total variance lying between schools:</span>
<span id="cb34-200"><a href="#cb34-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-201"><a href="#cb34-201" aria-hidden="true" tabindex="-1"></a>$$\text{ICC} = \frac{\tau_{00}}{\tau_{00} + \sigma^2}$$</span>
<span id="cb34-202"><a href="#cb34-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-203"><a href="#cb34-203" aria-hidden="true" tabindex="-1"></a>Here's a quick and easy way to get our friend the ICC:</span>
<span id="cb34-204"><a href="#cb34-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-207"><a href="#cb34-207" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-208"><a href="#cb34-208" aria-hidden="true" tabindex="-1"></a>null.ICC <span class="ot">&lt;-</span> <span class="fl">8.553</span><span class="sc">/</span>(<span class="fl">8.553</span> <span class="sc">+</span> <span class="fl">39.148</span>)</span>
<span id="cb34-209"><a href="#cb34-209" aria-hidden="true" tabindex="-1"></a>null.ICC</span>
<span id="cb34-210"><a href="#cb34-210" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-211"><a href="#cb34-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-212"><a href="#cb34-212" aria-hidden="true" tabindex="-1"></a>Roughly 18 percent of the variation in math achievement is between schools. Put another way, two students from the same school are noticeably more similar to each other than two students drawn at random from the full sample. That is the condition that makes ordinary regression standard errors too small.</span>
<span id="cb34-213"><a href="#cb34-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-214"><a href="#cb34-214" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip}</span>
<span id="cb34-215"><a href="#cb34-215" aria-hidden="true" tabindex="-1"></a><span class="fu">## Pulling the numbers out rather than typing them</span></span>
<span id="cb34-216"><a href="#cb34-216" aria-hidden="true" tabindex="-1"></a>Typing the variance components by hand works and makes the formula visible, which is why it is worth doing once. For your own analyses it is safer to extract them from the model, since a transposed digit produces a plausible-looking wrong answer:</span>
<span id="cb34-217"><a href="#cb34-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-220"><a href="#cb34-220" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-221"><a href="#cb34-221" aria-hidden="true" tabindex="-1"></a>vc <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">VarCorr</span>(model.null))</span>
<span id="cb34-222"><a href="#cb34-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-223"><a href="#cb34-223" aria-hidden="true" tabindex="-1"></a>tau00  <span class="ot">&lt;-</span> vc<span class="sc">$</span>vcov[vc<span class="sc">$</span>grp <span class="sc">==</span> <span class="st">"schoolid"</span>]</span>
<span id="cb34-224"><a href="#cb34-224" aria-hidden="true" tabindex="-1"></a>sigma2 <span class="ot">&lt;-</span> vc<span class="sc">$</span>vcov[vc<span class="sc">$</span>grp <span class="sc">==</span> <span class="st">"Residual"</span>]</span>
<span id="cb34-225"><a href="#cb34-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-226"><a href="#cb34-226" aria-hidden="true" tabindex="-1"></a>tau00 <span class="sc">/</span> (tau00 <span class="sc">+</span> sigma2)</span>
<span id="cb34-227"><a href="#cb34-227" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-228"><a href="#cb34-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-229"><a href="#cb34-229" aria-hidden="true" tabindex="-1"></a>The <span class="in">`performance`</span> package will also compute it directly with <span class="in">`performance::icc(model.null)`</span>.</span>
<span id="cb34-232"><a href="#cb34-232" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-233"><a href="#cb34-233" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">icc</span>(model.null)</span>
<span id="cb34-234"><a href="#cb34-234" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-235"><a href="#cb34-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-236"><a href="#cb34-236" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb34-237"><a href="#cb34-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-238"><a href="#cb34-238" aria-hidden="true" tabindex="-1"></a><span class="fu">## Using `lmerTest` to evaluate random effects</span></span>
<span id="cb34-239"><a href="#cb34-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-242"><a href="#cb34-242" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-243"><a href="#cb34-243" aria-hidden="true" tabindex="-1"></a><span class="fu">ranova</span>(model.null)</span>
<span id="cb34-244"><a href="#cb34-244" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-245"><a href="#cb34-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-246"><a href="#cb34-246" aria-hidden="true" tabindex="-1"></a>This is a likelihood ratio test comparing our model to one without the random intercept. A significant result says that letting schools have their own intercepts improves fit enough to justify the extra parameter.</span>
<span id="cb34-247"><a href="#cb34-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-248"><a href="#cb34-248" aria-hidden="true" tabindex="-1"></a>Read it alongside the ICC rather than instead of it. The test tells you whether school-level variance is distinguishable from zero; the ICC tells you how much of it there is. With 7,185 students you have enough power to detect quite small amounts of clustering, so significance alone is weak evidence that multilevel modeling matters substantively.</span>
<span id="cb34-249"><a href="#cb34-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-250"><a href="#cb34-250" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb34-251"><a href="#cb34-251" aria-hidden="true" tabindex="-1"></a><span class="fu">## `rand()` became `ranova()`</span></span>
<span id="cb34-252"><a href="#cb34-252" aria-hidden="true" tabindex="-1"></a>Older handouts call <span class="in">`lmerTest::rand()`</span>. The function was renamed to <span class="in">`ranova()`</span> several versions ago. The old name may still work but is no longer the documented one.</span>
<span id="cb34-253"><a href="#cb34-253" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb34-254"><a href="#cb34-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-255"><a href="#cb34-255" aria-hidden="true" tabindex="-1"></a><span class="fu">## Always interesting: compare our MLM to a regular regression</span></span>
<span id="cb34-256"><a href="#cb34-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-259"><a href="#cb34-259" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-260"><a href="#cb34-260" aria-hidden="true" tabindex="-1"></a>model.regular <span class="ot">&lt;-</span> <span class="fu">lm</span>(mathach <span class="sc">~</span> <span class="cn">NULL</span>, <span class="at">data =</span> hsb.clean)</span>
<span id="cb34-261"><a href="#cb34-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-262"><a href="#cb34-262" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.regular)</span>
<span id="cb34-263"><a href="#cb34-263" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-264"><a href="#cb34-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-265"><a href="#cb34-265" aria-hidden="true" tabindex="-1"></a>The intercept estimates are similar, which is expected in a null model. What differs is the standard error, and that difference is the entire practical argument for multilevel modeling. Ordinary regression treats 7,185 students as 7,185 independent pieces of information, when students within a school share teachers, curricula, neighborhoods, and funding. The result is standard errors that are too small and p-values that are too optimistic.</span>
<span id="cb34-266"><a href="#cb34-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-267"><a href="#cb34-267" aria-hidden="true" tabindex="-1"></a>One last point students routinely get wrong. The fixed-effect intercept in the null model is not simply the mean of all 7,185 scores. It estimates the average of the *school* means, weighting schools by how much information each contributes. With balanced data the two are close; with unbalanced data they differ, and the multilevel estimate is usually the one you want.</span>
<span id="cb34-268"><a href="#cb34-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-271"><a href="#cb34-271" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb34-272"><a href="#cb34-272" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(hsb.clean<span class="sc">$</span>mathach, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)   <span class="co"># grand mean of all students</span></span>
<span id="cb34-273"><a href="#cb34-273" aria-hidden="true" tabindex="-1"></a><span class="fu">fixef</span>(model.null)                       <span class="co"># model-based estimate</span></span>
<span id="cb34-274"><a href="#cb34-274" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb34-275"><a href="#cb34-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-276"><a href="#cb34-276" aria-hidden="true" tabindex="-1"></a><span class="fu">## What comes next</span></span>
<span id="cb34-277"><a href="#cb34-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-278"><a href="#cb34-278" aria-hidden="true" tabindex="-1"></a>The null model tells us schools differ. It does not tell us why. The next chapter starts adding predictors, at both the student and school levels, to explain some of the variance we just found.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>Applied Multilevel Modeling in R</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/mikediam123/mlm-textbook/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org">Quarto</a></p>
</div>
  </div>
</footer>


</body></html>