<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="An online companion to Dr.&nbsp;Broda’s Multilevel Modeling course (EDUS 664) at Virginia Commonwealth University. Each chapter works through the R code for one course module.">
<title>Applied Multilevel Modeling in R - 7&nbsp; Goodness-of-Fit and Effect Sizes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./07-three-level.html" rel="next">
<link href="./05-random-slopes.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script><script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script><script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03-null-model.html">Two-Level Models</a></li><li class="breadcrumb-item"><a href="./06-fit-effect-sizes.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Goodness-of-Fit and Effect Sizes</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Applied Multilevel Modeling in R</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/mikediam123/mlm-textbook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
<li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
</div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-getting-started.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting Started with R and RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-reading-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Reading: Regression and Where It Runs Out</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-regression-review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Review of Linear Regression</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Two-Level Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-null-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Intro to MLM and the Null Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-random-intercept.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Conditional Random Intercept Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-random-slopes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Random Slope Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-fit-effect-sizes.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Goodness-of-Fit and Effect Sizes</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Extending the Model</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-three-level.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Three-Level Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08a-growth-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Intro to Growth Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08b-growth-advanced.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Advanced Growth Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-binary-outcomes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Binary and Generalized Linear Mixed Models</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Checking and Complicating</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-assumptions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Checking Assumptions for MLMs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-cross-classified.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Cross-Classified Linear Mixed Models</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#two-models-to-compare" id="toc-two-models-to-compare" class="nav-link active" data-scroll-target="#two-models-to-compare"><span class="header-section-number">7.1</span> Two models to compare</a></li>
  <li>
<a href="#proportional-reduction-in-variance" id="toc-proportional-reduction-in-variance" class="nav-link" data-scroll-target="#proportional-reduction-in-variance"><span class="header-section-number">7.2</span> Proportional reduction in variance</a>
  <ul class="collapse">
<li><a href="#when-prv-comes-out-negative" id="toc-when-prv-comes-out-negative" class="nav-link" data-scroll-target="#when-prv-comes-out-negative"><span class="header-section-number">7.2.1</span> When PRV comes out negative</a></li>
  </ul>
</li>
  <li><a href="#the-performance-package-version" id="toc-the-performance-package-version" class="nav-link" data-scroll-target="#the-performance-package-version"><span class="header-section-number">7.3</span> The <code>performance</code> package version</a></li>
  <li><a href="#translating-for-a-non-technical-audience" id="toc-translating-for-a-non-technical-audience" class="nav-link" data-scroll-target="#translating-for-a-non-technical-audience"><span class="header-section-number">7.4</span> Translating for a non-technical audience</a></li>
  <li>
<a href="#model-comparison-with-information-criteria" id="toc-model-comparison-with-information-criteria" class="nav-link" data-scroll-target="#model-comparison-with-information-criteria"><span class="header-section-number">7.5</span> Model comparison with information criteria</a>
  <ul class="collapse">
<li><a href="#when-the-criteria-disagree" id="toc-when-the-criteria-disagree" class="nav-link" data-scroll-target="#when-the-criteria-disagree"><span class="header-section-number">7.5.1</span> When the criteria disagree</a></li>
  </ul>
</li>
  <li><a href="#when-a-model-will-not-converge" id="toc-when-a-model-will-not-converge" class="nav-link" data-scroll-target="#when-a-model-will-not-converge"><span class="header-section-number">7.6</span> When a model will not converge</a></li>
  <li><a href="#putting-it-together" id="toc-putting-it-together" class="nav-link" data-scroll-target="#putting-it-together"><span class="header-section-number">7.7</span> Putting it together</a></li>
  <li><a href="#a-note-on-your-content-review" id="toc-a-note-on-your-content-review" class="nav-link" data-scroll-target="#a-note-on-your-content-review"><span class="header-section-number">7.8</span> A note on your content review</a></li>
  </ul><div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/mikediam123/mlm-textbook/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">
<span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Goodness-of-Fit and Effect Sizes</span>
</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p><strong>Data for this chapter:</strong> <code>lq2002.csv</code></p>
<p>Significance tells you whether an association is distinguishable from zero. It does not tell you whether the association matters, and with large samples the two questions come apart badly. This chapter covers effect sizes for multilevel models and the fit statistics used to choose among competing models.</p>
<p>We return to the Gavin and Hofmann (2002) Army data from the last two chapters: 2,042 soldiers nested within 49 companies. The outcome is <code>HOSTILE</code>, a hostility scale score that runs from 0 to 4. The predictors are <code>TSIG</code> (task significance) and <code>LEAD</code> (leadership climate), both measured on each soldier, plus <code>GTSIG</code>, the company average of task significance. <code>COMPID</code> identifies the company.</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/message.html">suppressPackageStartupMessages</a></span><span class="op">(</span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/lme4/lme4/">lme4</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/runehaubo/lmerTestR">lmerTest</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://easystats.github.io/performance/">performance</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://modelsummary.com">modelsummary</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lq2002</span> <span class="op">&lt;-</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"lq2002.csv"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">COMPID</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    TSIG_gc <span class="op">=</span> <span class="va">TSIG</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">TSIG</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,   <span class="co"># group-mean center the level-1 predictors</span></span>
<span>    LEAD_gc <span class="op">=</span> <span class="va">LEAD</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">LEAD</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">ungroup</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    GTSIG_c <span class="op">=</span> <span class="va">GTSIG</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">GTSIG</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>  <span class="co"># grand-mean center the level-2 predictor</span></span>
<span>  <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 2042 Columns: 28
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (28): ROWID, COMPID, SUB, LEAD01, LEAD02, LEAD03, LEAD04, LEAD05, LEAD06...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">lq2002</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 2,042
Columns: 31
$ ROWID    &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18…
$ COMPID   &lt;dbl&gt; 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2…
$ SUB      &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18…
$ LEAD01   &lt;dbl&gt; 2, 4, 4, 1, 1, 2, 3, 3, 3, 4, 2, 2, 4, 4, 1, 2, 4, 4, 4, 4, 4…
$ LEAD02   &lt;dbl&gt; 2, 4, 4, 1, 1, 3, 2, 3, 4, 3, 4, 3, 4, 4, 1, 1, 5, 4, 5, 4, 2…
$ LEAD03   &lt;dbl&gt; 2, 2, 2, 1, 1, 2, 2, 2, 3, 3, 1, 1, 4, 4, 1, 2, 3, 4, 1, 4, 2…
$ LEAD04   &lt;dbl&gt; 3, 4, 4, 1, 1, 4, 1, 4, 2, 4, 3, 1, 4, 4, 1, 4, 5, 4, 1, 5, 1…
$ LEAD05   &lt;dbl&gt; 2, 4, 2, 1, 3, 2, 2, 2, 3, 3, 1, 2, 4, 4, 1, 3, 3, 4, 1, 2, 2…
$ LEAD06   &lt;dbl&gt; 2, 4, 4, 1, 2, 4, 2, 2, 3, 4, 3, 4, 4, 4, 1, 3, 5, 4, 4, 2, 2…
$ LEAD07   &lt;dbl&gt; 5, 4, 4, 4, 1, 3, 2, 2, 3, 3, 3, 1, 4, 3, 1, 5, 3, 4, 1, 3, 2…
$ LEAD08   &lt;dbl&gt; 5, 4, 4, 2, 1, 4, 2, 4, 1, 4, 4, 3, 4, 4, 1, 2, 5, 4, 1, 3, 2…
$ LEAD09   &lt;dbl&gt; 5, 4, 4, 3, 1, 2, 3, 2, 3, 3, 2, 2, 4, 4, 1, 4, 1, 4, 1, 4, 2…
$ LEAD10   &lt;dbl&gt; 5, 4, 4, 3, 1, 4, 4, 2, 2, 4, 3, 2, 4, 4, 1, 2, 5, 4, 4, 4, 1…
$ LEAD11   &lt;dbl&gt; 4, 3, 2, 2, 1, 3, 2, 4, 3, 3, 2, 1, 4, 4, 1, 2, 4, 4, 1, 4, 2…
$ TSIG01   &lt;dbl&gt; 1, 3, 5, 1, 4, 4, 2, 2, 4, 4, 3, 3, 4, 4, 1, 1, 4, 4, 1, 5, 1…
$ TSIG02   &lt;dbl&gt; 5, 4, 5, 3, 4, 4, 4, 2, 3, 4, 4, 3, 4, 4, 1, 5, 4, 4, 5, 5, 4…
$ TSIG03   &lt;dbl&gt; 5, 3, 5, 2, 4, 4, 4, 4, 4, 4, 3, 3, 4, 4, 1, 4, 5, 4, 5, 5, 4…
$ HOSTIL01 &lt;dbl&gt; 0, 3, 1, 2, 2, 0, 2, 0, 0, 1, 1, 2, 0, 0, 4, 3, 1, 0, 4, 3, 4…
$ HOSTIL02 &lt;dbl&gt; 0, 2, 0, 1, 0, 0, 0, 0, 4, 0, 0, 2, 0, 0, 4, 0, 0, 0, 0, 1, 4…
$ HOSTIL03 &lt;dbl&gt; 0, 0, 0, 3, 0, 0, 1, 0, 4, 0, 0, 0, 0, 0, 4, 0, 0, 0, 4, 2, 2…
$ HOSTIL04 &lt;dbl&gt; 0, 0, 0, 3, 0, 0, 1, 0, 4, 0, 0, 1, 0, 0, 4, 0, 0, 0, 4, 3, 2…
$ HOSTIL05 &lt;dbl&gt; 0, 1, 1, 0, 0, 0, 0, 0, 4, 0, 0, 2, 0, 0, 2, 0, 0, 0, 4, 2, 3…
$ LEAD     &lt;dbl&gt; 3.363636, 3.727273, 3.454545, 1.818182, 1.272727, 3.000000, 2…
$ TSIG     &lt;dbl&gt; 3.666667, 3.333333, 5.000000, 2.000000, 4.000000, 4.000000, 3…
$ HOSTILE  &lt;dbl&gt; 0.0, 1.2, 0.4, 1.8, 0.4, 0.0, 0.8, 0.0, 3.2, 0.2, 0.2, 1.4, 0…
$ GLEAD    &lt;dbl&gt; 2.882576, 2.882576, 2.882576, 2.882576, 2.882576, 2.882576, 2…
$ GTSIG    &lt;dbl&gt; 3.541667, 3.541667, 3.541667, 3.541667, 3.541667, 3.541667, 3…
$ GHOSTILE &lt;dbl&gt; 1.0416667, 1.0416667, 1.0416667, 1.0416667, 1.0416667, 1.0416…
$ TSIG_gc  &lt;dbl&gt; 0.1250000, -0.2083333, 1.4583333, -1.5416667, 0.4583333, 0.45…
$ LEAD_gc  &lt;dbl&gt; 0.4810606, 0.8446970, 0.5719697, -1.0643939, -1.6098485, 0.11…
$ GTSIG_c  &lt;dbl&gt; 0.4086272, 0.4086272, 0.4086272, 0.4086272, 0.4086272, 0.4086…</code></pre>
</div>
</div>
<p>As in the last chapter, we group-mean center the level-1 predictors and grand-mean center the level-2 predictor. <code>TSIG_gc</code> and <code>LEAD_gc</code> express each soldier’s score as a distance from their <em>own</em> company’s average, so they carry only within-company variation. <code>GTSIG_c</code> expresses each company’s average task significance as a distance from the average company. The intercept in every model below describes a soldier who sits exactly at their company’s average on both predictors, in a company of average task significance.</p>
<section id="two-models-to-compare" class="level2" data-number="7.1"><h2 data-number="7.1" class="anchored" data-anchor-id="two-models-to-compare">
<span class="header-section-number">7.1</span> Two models to compare</h2>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m_null</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">HOSTILE</span> <span class="op">~</span> <span class="fl">1</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">COMPID</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">lq2002</span>, REML <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">m_cond</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">HOSTILE</span> <span class="op">~</span> <span class="va">GTSIG_c</span> <span class="op">+</span> <span class="va">TSIG_gc</span> <span class="op">+</span> <span class="va">LEAD_gc</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">COMPID</span><span class="op">)</span>,</span>
<span>               data <span class="op">=</span> <span class="va">lq2002</span>, REML <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m_cond</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite's
  method [lmerModLmerTest]
Formula: HOSTILE ~ GTSIG_c + TSIG_gc + LEAD_gc + (1 | COMPID)
   Data: lq2002

      AIC       BIC    logLik -2*log(L)  df.resid 
   5547.9    5581.6   -2768.0    5535.9      2036 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.3339 -0.6970 -0.2219  0.5082  3.5377 

Random effects:
 Groups   Name        Variance Std.Dev.
 COMPID   (Intercept) 0.01985  0.1409  
 Residual             0.86785  0.9316  
Number of obs: 2042, groups:  COMPID, 49

Fixed effects:
              Estimate Std. Error         df t value Pr(&gt;|t|)    
(Intercept)    0.93509    0.03053   35.27446  30.625  &lt; 2e-16 ***
GTSIG_c       -0.57251    0.09204   38.68403  -6.220 2.64e-07 ***
TSIG_gc       -0.17486    0.02510 1991.15348  -6.967 4.38e-12 ***
LEAD_gc       -0.34583    0.03134 1991.15348 -11.036  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
        (Intr) GTSIG_ TSIG_g
GTSIG_c -0.063              
TSIG_gc  0.000  0.000       
LEAD_gc  0.000  0.000 -0.528</code></pre>
</div>
</div>
<p>The null model tells us that company membership accounts for only about 5% of the variance in hostility (an ICC of about .05, with <span class="math inline">\tau_{00}</span> = .058 and <span class="math inline">\sigma^2</span> = 1.017). In the conditional model, all three predictors are negatively related to hostility, and all three coefficients are clearly distinguishable from zero. Because of the centering, they answer different questions. The <code>TSIG_gc</code> and <code>LEAD_gc</code> coefficients are <em>within-company</em> effects: a soldier who finds the work more significant than their company-mates do, or who reports a better leadership climate than they do, reports less hostility. The <code>GTSIG_c</code> coefficient is a <em>between-company</em> effect: companies where task significance is high on average have lower average hostility, and the estimate (about <span class="math inline">-.57</span>) is more than three times the within-company one for <code>TSIG_gc</code> (<span class="math inline">-.17</span>). The question for the rest of the chapter is how much that matters.</p>
</section><section id="proportional-reduction-in-variance" class="level2" data-number="7.2"><h2 data-number="7.2" class="anchored" data-anchor-id="proportional-reduction-in-variance">
<span class="header-section-number">7.2</span> Proportional reduction in variance</h2>
<p>The most interpretable multilevel effect sizes ask how much variance a model explains relative to the null model, computed separately at each level. Extract the variance components first:</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">vc_null</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/nlme/man/VarCorr.html">VarCorr</a></span><span class="op">(</span><span class="va">m_null</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">vc_cond</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/nlme/man/VarCorr.html">VarCorr</a></span><span class="op">(</span><span class="va">m_cond</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">tau_null</span>   <span class="op">&lt;-</span> <span class="va">vc_null</span><span class="op">$</span><span class="va">vcov</span><span class="op">[</span><span class="va">vc_null</span><span class="op">$</span><span class="va">grp</span> <span class="op">==</span> <span class="st">"COMPID"</span><span class="op">]</span></span>
<span><span class="va">sigma_null</span> <span class="op">&lt;-</span> <span class="va">vc_null</span><span class="op">$</span><span class="va">vcov</span><span class="op">[</span><span class="va">vc_null</span><span class="op">$</span><span class="va">grp</span> <span class="op">==</span> <span class="st">"Residual"</span><span class="op">]</span></span>
<span></span>
<span><span class="va">tau_cond</span>   <span class="op">&lt;-</span> <span class="va">vc_cond</span><span class="op">$</span><span class="va">vcov</span><span class="op">[</span><span class="va">vc_cond</span><span class="op">$</span><span class="va">grp</span> <span class="op">==</span> <span class="st">"COMPID"</span><span class="op">]</span></span>
<span><span class="va">sigma_cond</span> <span class="op">&lt;-</span> <span class="va">vc_cond</span><span class="op">$</span><span class="va">vcov</span><span class="op">[</span><span class="va">vc_cond</span><span class="op">$</span><span class="va">grp</span> <span class="op">==</span> <span class="st">"Residual"</span><span class="op">]</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>tau_null <span class="op">=</span> <span class="va">tau_null</span>, sigma_null <span class="op">=</span> <span class="va">sigma_null</span>,</span>
<span>  tau_cond <span class="op">=</span> <span class="va">tau_cond</span>, sigma_cond <span class="op">=</span> <span class="va">sigma_cond</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  tau_null sigma_null   tau_cond sigma_cond 
0.05764857 1.01667991 0.01985321 0.86784844 </code></pre>
</div>
</div>
<p>Within-group proportional reduction in variance is the share of soldier-level variance the predictors account for:</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">wg_prv</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">sigma_null</span> <span class="op">-</span> <span class="va">sigma_cond</span><span class="op">)</span> <span class="op">/</span> <span class="va">sigma_null</span></span>
<span><span class="va">wg_prv</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1463897</code></pre>
</div>
</div>
<p>Between-group PRV does the same at the company level:</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">bg_prv</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">tau_null</span> <span class="op">-</span> <span class="va">tau_cond</span><span class="op">)</span> <span class="op">/</span> <span class="va">tau_null</span></span>
<span><span class="va">bg_prv</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6556165</code></pre>
</div>
</div>
<p>And a total, or multilevel, <span class="math inline">R^2</span> uses the combined variance:</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">total_null</span> <span class="op">&lt;-</span> <span class="va">tau_null</span> <span class="op">+</span> <span class="va">sigma_null</span></span>
<span><span class="va">total_cond</span> <span class="op">&lt;-</span> <span class="va">tau_cond</span> <span class="op">+</span> <span class="va">sigma_cond</span></span>
<span></span>
<span><span class="va">ml_r2</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">total_null</span> <span class="op">-</span> <span class="va">total_cond</span><span class="op">)</span> <span class="op">/</span> <span class="va">total_null</span></span>
<span><span class="va">ml_r2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1737149</code></pre>
</div>
</div>
<p>Be precise about what each denominator refers to when you write these up. WG-PRV is the proportion of <em>soldier-level</em> variance explained, not the proportion of all variance. Reporting it as though it were an overall <span class="math inline">R^2</span> overstates your model considerably.</p>
<p>These data show why. The predictors account for about 15% of the within-company variance (WG-PRV = .146) and about 66% of the between-company variance (BG-PRV = .656). That second number sounds impressive until you remember how little between-company variance there was to explain: <span class="math inline">\tau_{00}</span> fell from .058 to .020, and company differences were only about 5% of the total to begin with. The multilevel <span class="math inline">R^2</span> of .174 is the fairer summary of how much of the variation in hostility the model accounts for, and almost all of that explained variance is <em>within</em> companies.</p>
<p>Notice also where the between-company reduction comes from. The group-mean centered predictors contain no between-company information by construction, so the only predictor that can explain company differences is <code>GTSIG_c</code>. A model with <code>GTSIG_c</code> alone has a BG-PRV of about .73, higher than the .66 for the full model, which leads directly to the next point.</p>
<section id="when-prv-comes-out-negative" class="level3" data-number="7.2.1"><h3 data-number="7.2.1" class="anchored" data-anchor-id="when-prv-comes-out-negative">
<span class="header-section-number">7.2.1</span> When PRV comes out negative</h3>
<p>A negative PRV looks like an arithmetic mistake and usually is not. Adding a level-one predictor can increase the estimated level-two variance, because the level-two variance is estimated conditional on everything else in the model. If a student-level predictor is unevenly distributed across teachers, controlling for it can reveal teacher differences that were previously masked. Report the negative value and explain it. Deleting it from your table is the one clearly wrong response.</p>
<p>These data produce a clean example. Fit a model with only the two group-mean centered level-1 predictors:</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m_within</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">HOSTILE</span> <span class="op">~</span> <span class="va">TSIG_gc</span> <span class="op">+</span> <span class="va">LEAD_gc</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">COMPID</span><span class="op">)</span>,</span>
<span>                 data <span class="op">=</span> <span class="va">lq2002</span>, REML <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">vc_within</span>    <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/nlme/man/VarCorr.html">VarCorr</a></span><span class="op">(</span><span class="va">m_within</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">tau_within</span>   <span class="op">&lt;-</span> <span class="va">vc_within</span><span class="op">$</span><span class="va">vcov</span><span class="op">[</span><span class="va">vc_within</span><span class="op">$</span><span class="va">grp</span> <span class="op">==</span> <span class="st">"COMPID"</span><span class="op">]</span></span>
<span><span class="va">sigma_within</span> <span class="op">&lt;-</span> <span class="va">vc_within</span><span class="op">$</span><span class="va">vcov</span><span class="op">[</span><span class="va">vc_within</span><span class="op">$</span><span class="va">grp</span> <span class="op">==</span> <span class="st">"Residual"</span><span class="op">]</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>wg_prv <span class="op">=</span> <span class="op">(</span><span class="va">sigma_null</span> <span class="op">-</span> <span class="va">sigma_within</span><span class="op">)</span> <span class="op">/</span> <span class="va">sigma_null</span>,</span>
<span>  bg_prv <span class="op">=</span> <span class="op">(</span><span class="va">tau_null</span> <span class="op">-</span> <span class="va">tau_within</span><span class="op">)</span> <span class="op">/</span> <span class="va">tau_null</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     wg_prv      bg_prv 
 0.14907909 -0.06864074 </code></pre>
</div>
</div>
<p>The within-company PRV is positive, about .149, because these predictors do explain soldier-level variance. The between-company PRV is negative, about <span class="math inline">-.069</span>, because <span class="math inline">\tau_{00}</span> rose slightly, from .058 to .062. Group-mean centered predictors have nothing to say about differences between companies, so there was no reduction to expect. Once the within-company variance is accounted for, the estimate of the company-level variance shifts a little. The right reading is “no reduction in between-company variance,” and the right response is to report it.</p>
</section></section><section id="the-performance-package-version" class="level2" data-number="7.3"><h2 data-number="7.3" class="anchored" data-anchor-id="the-performance-package-version">
<span class="header-section-number">7.3</span> The <code>performance</code> package version</h2>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">performance</span><span class="fu">::</span><span class="fu"><a href="https://easystats.github.io/performance/reference/r2.html">r2</a></span><span class="op">(</span><span class="va">m_cond</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># R2 for Mixed Models

  Conditional R2: 0.189
     Marginal R2: 0.171</code></pre>
</div>
</div>
<p>This reports marginal <span class="math inline">R^2</span>, the variance explained by fixed effects alone (.171), and conditional <span class="math inline">R^2</span>, the variance explained by fixed and random effects together (.189). These are Nakagawa’s measures, and they answer a slightly different question than the PRV statistics above. Marginal <span class="math inline">R^2</span> lands close to our multilevel <span class="math inline">R^2</span> of .174 but is not identical to it. The conditional value is only a little larger than the marginal one because company differences are such a small share of the variance. Both are defensible. Say which you used.</p>
</section><section id="translating-for-a-non-technical-audience" class="level2" data-number="7.4"><h2 data-number="7.4" class="anchored" data-anchor-id="translating-for-a-non-technical-audience">
<span class="header-section-number">7.4</span> Translating for a non-technical audience</h2>
<p>Suppose a battalion commander asks how much leadership climate matters for hostility. Effect sizes in variance units rarely land. Predicted values usually do:</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://strengejacke.github.io/ggeffects/">ggeffects</a></span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://strengejacke.github.io/ggeffects/reference/ggpredict.html">ggpredict</a></span><span class="op">(</span><span class="va">m_cond</span>, terms <span class="op">=</span> <span class="st">"LEAD_gc [meansd]"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Predicted values of HOSTILE

LEAD_gc | Predicted |     95% CI
--------------------------------
  -0.77 |      1.20 | 1.13, 1.28
   0.00 |      0.94 | 0.88, 0.99
   0.77 |      0.67 | 0.59, 0.75

Adjusted for:
* GTSIG_c =  0.00
* TSIG_gc = -0.00
*  COMPID = 0 (population-level)</code></pre>
</div>
</div>
<p>The three rows show predicted hostility for a soldier one standard deviation below their company’s average on leadership climate (1.20), at their company’s average (0.94), and one standard deviation above (0.67), holding the other predictors at their means. Because <code>LEAD_gc</code> is centered within companies, one standard deviation here is the typical spread among soldiers in the same company (0.77), not the spread across the whole Army. Reporting that a soldier who rates leadership climate one standard deviation higher than their company-mates do is predicted to score about 0.27 points lower on hostility, on a scale that runs from 0 to 4, communicates more than a proportional reduction in variance ever will. A standardized mean difference is another good option when your audience is used to reading them: 0.27 points is about a quarter of a standard deviation of hostility (SD = 1.04).</p>
</section><section id="model-comparison-with-information-criteria" class="level2" data-number="7.5"><h2 data-number="7.5" class="anchored" data-anchor-id="model-comparison-with-information-criteria">
<span class="header-section-number">7.5</span> Model comparison with information criteria</h2>
<p>Now a different question: which model should we report? Start by adding a random slope for task significance.</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m_slope</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">HOSTILE</span> <span class="op">~</span> <span class="va">GTSIG_c</span> <span class="op">+</span> <span class="va">TSIG_gc</span> <span class="op">+</span> <span class="va">LEAD_gc</span> <span class="op">+</span></span>
<span>                  <span class="op">(</span><span class="fl">1</span> <span class="op">+</span> <span class="va">TSIG_gc</span> <span class="op">|</span> <span class="va">COMPID</span><span class="op">)</span>,</span>
<span>                data <span class="op">=</span> <span class="va">lq2002</span>, REML <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>boundary (singular) fit: see help('isSingular')</code></pre>
</div>
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/lmerTest/man/ranova.html">ranova</a></span><span class="op">(</span><span class="va">m_slope</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ANOVA-like table for random-effects: Single term deletions

Model:
HOSTILE ~ GTSIG_c + TSIG_gc + LEAD_gc + (1 + TSIG_gc | COMPID)
                                  npar  logLik    AIC    LRT Df Pr(&gt;Chisq)    
&lt;none&gt;                               8 -2757.1 5530.2                         
TSIG_gc in (1 + TSIG_gc | COMPID)    6 -2767.9 5547.9 21.723  2  1.918e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">m_cond</span>, <span class="va">m_slope</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Data: lq2002
Models:
m_cond: HOSTILE ~ GTSIG_c + TSIG_gc + LEAD_gc + (1 | COMPID)
m_slope: HOSTILE ~ GTSIG_c + TSIG_gc + LEAD_gc + (1 + TSIG_gc | COMPID)
        npar    AIC    BIC  logLik -2*log(L)  Chisq Df Pr(&gt;Chisq)    
m_cond     6 5547.9 5581.6 -2767.9    5535.9                         
m_slope    8 5530.2 5575.2 -2757.1    5514.2 21.723  2  1.918e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/AIC.html">AIC</a></span><span class="op">(</span><span class="va">m_cond</span>, <span class="va">m_slope</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        df      AIC
m_cond   6 5547.902
m_slope  8 5530.179</code></pre>
</div>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/AIC.html">BIC</a></span><span class="op">(</span><span class="va">m_cond</span>, <span class="va">m_slope</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        df      BIC
m_cond   6 5581.632
m_slope  8 5575.153</code></pre>
</div>
</div>
<section id="when-the-criteria-disagree" class="level3" data-number="7.5.1"><h3 data-number="7.5.1" class="anchored" data-anchor-id="when-the-criteria-disagree">
<span class="header-section-number">7.5.1</span> When the criteria disagree</h3>
<p>They often will, and understanding why is more useful than memorizing a rule. AIC and BIC both penalize complexity, but BIC’s penalty grows with sample size while AIC’s does not. With a large sample, BIC prefers simpler models more aggressively than AIC does. The likelihood ratio test is a third thing again: a hypothesis test with a null of no improvement, which inherits all the usual sensitivities to sample size.</p>
<p>For random effects there is an additional wrinkle. Testing whether a variance component equals zero puts the null on the boundary of the parameter space, which makes the usual chi-square reference distribution conservative, and <code><a href="https://rdrr.io/pkg/lmerTest/man/ranova.html">ranova()</a></code> does not correct for it. It is a reason not to treat a p-value of .06 on a variance component as decisive.</p>
<p>When the criteria disagree, say so, state which you weighted and why, and check whether your substantive conclusions change between the two models. If the treatment effect is essentially identical either way, the model choice matters less than it appears to.</p>
<p>For this random slope, the criteria do not disagree. The likelihood ratio test is clearly significant, <span class="math inline">\chi^2</span>(2) = 21.72, <span class="math inline">p</span> &lt; .001. AIC drops from 5547.9 to 5530.2, and even BIC, with its heavier penalty, drops from 5581.6 to 5575.2. Everything points toward keeping the slope.</p>
<p>Agreement among the criteria does not make a model trustworthy, though. Look inside it:</p>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/nlme/man/VarCorr.html">VarCorr</a></span><span class="op">(</span><span class="va">m_slope</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Groups   Name        Std.Dev. Corr   
 COMPID   (Intercept) 0.15592         
          TSIG_gc     0.11796  -1.000 
 Residual             0.92303         </code></pre>
</div>
</div>
<p>R printed <code>boundary (singular) fit</code> when it fitted this model, and the correlation between the intercept and the <code>TSIG_gc</code> slope is exactly <span class="math inline">-1.00</span>. That is not a finding about the Army. It is the model reporting that it has run out of information, which is the same thing we saw in the last chapter. The slope variance is real enough that the fit statistics reward it, but the <em>correlation</em> is more than 49 companies can support.</p>
</section></section><section id="when-a-model-will-not-converge" class="level2" data-number="7.6"><h2 data-number="7.6" class="anchored" data-anchor-id="when-a-model-will-not-converge">
<span class="header-section-number">7.6</span> When a model will not converge</h2>
<p>Ask for two random slopes and things get worse:</p>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m_two_slopes</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">HOSTILE</span> <span class="op">~</span> <span class="va">GTSIG_c</span> <span class="op">+</span> <span class="va">TSIG_gc</span> <span class="op">+</span> <span class="va">LEAD_gc</span> <span class="op">+</span></span>
<span>                       <span class="op">(</span><span class="fl">1</span> <span class="op">+</span> <span class="va">TSIG_gc</span> <span class="op">+</span> <span class="va">LEAD_gc</span> <span class="op">|</span> <span class="va">COMPID</span><span class="op">)</span>,</span>
<span>                     data <span class="op">=</span> <span class="va">lq2002</span>, REML <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>boundary (singular) fit: see help('isSingular')</code></pre>
</div>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/nlme/man/VarCorr.html">VarCorr</a></span><span class="op">(</span><span class="va">m_two_slopes</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Groups   Name        Std.Dev. Corr          
 COMPID   (Intercept) 0.15690                
          TSIG_gc     0.13269  -0.870        
          LEAD_gc     0.12223  -0.098 -0.406 
 Residual             0.91926                </code></pre>
</div>
</div>
<p>This one fits, but R again reports a singular fit. The printed correlations (<span class="math inline">-.87</span>, <span class="math inline">-.10</span>, and <span class="math inline">-.41</span>) look unremarkable, which is what makes this case easy to miss. The problem is hiding in the covariance matrix of the three random effects: it has a zero eigenvalue, meaning some combination of the intercept and the two slopes has no variance at all. The model has collapsed onto something smaller than the structure we asked for.</p>
<p>It is worth doing the arithmetic yourself before fitting a complex random effects structure. A model with <span class="math inline">q</span> random effects per company needs <span class="math inline">q(q + 1)/2</span> variance and covariance parameters: 1 for a random intercept alone, 3 for an intercept and one slope, and 6 for an intercept and two slopes. Compare that to the number of level-two units, not the number of soldiers. Slope variance is learned from how much slopes <em>differ across companies</em>, and we have only 49 companies, so 2,042 soldiers do not help as much as you might hope. The more parameters you ask 49 companies to support, the less well each one is determined, and the first thing to give is usually a correlation.</p>
<p>The more common situation is a message like this one rather than a failure to run. Instead of an outright refusal you get a singular fit, you might get a variance component estimated at essentially zero, or a correlation of exactly 1 or -1. Those are the same messages, just delivered a little more politely. The data cannot support that many random effects.</p>
<p>So how might you respond? You basically have three choices, in order from most to least preferred: 1) drop the random slope correlations and keep both slopes uncorrelated; 2) drop the less theoretically important slope; or 3) return to a random intercept model and acknowledge in your write-up that slope variation could not be estimated with these data. All three are defensible, and all are better than reporting a singular model as though it converged normally.</p>
<p>Here is the first option:</p>
<div class="cell">
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Uncorrelated random effects</span></span>
<span><span class="va">m_uncorr</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">HOSTILE</span> <span class="op">~</span> <span class="va">GTSIG_c</span> <span class="op">+</span> <span class="va">TSIG_gc</span> <span class="op">+</span> <span class="va">LEAD_gc</span> <span class="op">+</span></span>
<span>                   <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">COMPID</span><span class="op">)</span> <span class="op">+</span> <span class="op">(</span><span class="fl">0</span> <span class="op">+</span> <span class="va">TSIG_gc</span> <span class="op">|</span> <span class="va">COMPID</span><span class="op">)</span> <span class="op">+</span> <span class="op">(</span><span class="fl">0</span> <span class="op">+</span> <span class="va">LEAD_gc</span> <span class="op">|</span> <span class="va">COMPID</span><span class="op">)</span>,</span>
<span>                 data <span class="op">=</span> <span class="va">lq2002</span>, REML <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/lme4/man/isSingular.html">isSingular</a></span><span class="op">(</span><span class="va">m_uncorr</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">m_cond</span>, <span class="va">m_uncorr</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Data: lq2002
Models:
m_cond: HOSTILE ~ GTSIG_c + TSIG_gc + LEAD_gc + (1 | COMPID)
m_uncorr: HOSTILE ~ GTSIG_c + TSIG_gc + LEAD_gc + (1 | COMPID) + (0 + TSIG_gc | COMPID) + (0 + LEAD_gc | COMPID)
         npar    AIC    BIC logLik -2*log(L)  Chisq Df Pr(&gt;Chisq)  
m_cond      6 5547.9 5581.6  -2768    5535.9                       
m_uncorr    8 5545.9 5590.9  -2765    5529.9 6.0017  2    0.04975 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/AIC.html">AIC</a></span><span class="op">(</span><span class="va">m_cond</span>, <span class="va">m_uncorr</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         df      AIC
m_cond    6 5547.902
m_uncorr  8 5545.901</code></pre>
</div>
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/AIC.html">BIC</a></span><span class="op">(</span><span class="va">m_cond</span>, <span class="va">m_uncorr</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         df      BIC
m_cond    6 5581.632
m_uncorr  8 5590.874</code></pre>
</div>
</div>
<p>This model is not singular, so it is a fit we can report honestly. It also gives us the disagreement described above, in miniature. The likelihood ratio test lands right at the edge of conventional significance (<span class="math inline">\chi^2</span>(2) = 6.00, <span class="math inline">p</span> = .050), and AIC edges toward the model with random slopes (5545.9 versus 5547.9), while BIC clearly favors the simpler random intercept model (5590.9 versus 5581.6). BIC charges each extra parameter ln(2,042) <span class="math inline">\approx</span> 7.6, against 2 for AIC, so two additional variance components cost about 15 on the BIC scale and only 4 on the AIC scale.</p>
<p>So which do we report? Check whether the substantive story changes. The fixed effects barely move: <code>GTSIG_c</code> goes from <span class="math inline">-.573</span> to <span class="math inline">-.571</span>, <code>TSIG_gc</code> from <span class="math inline">-.175</span> to <span class="math inline">-.162</span>, and <code>LEAD_gc</code> from <span class="math inline">-.346</span> to <span class="math inline">-.339</span>. All three stay negative and clearly distinguishable from zero in both models. Because the conclusions about the predictors do not depend on the choice, either model is defensible as long as you say which you used and why, and report the other as a check.</p>
</section><section id="putting-it-together" class="level2" data-number="7.7"><h2 data-number="7.7" class="anchored" data-anchor-id="putting-it-together">
<span class="header-section-number">7.7</span> Putting it together</h2>
<div class="cell">
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://modelsummary.com/man/modelsummary.html">modelsummary</a></span><span class="op">(</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="st">"Null"</span> <span class="op">=</span> <span class="va">m_null</span>, <span class="st">"Conditional"</span> <span class="op">=</span> <span class="va">m_cond</span>,</span>
<span>       <span class="st">"+ Random slope"</span> <span class="op">=</span> <span class="va">m_slope</span>, <span class="st">"+ Uncorrelated slopes"</span> <span class="op">=</span> <span class="va">m_uncorr</span><span class="op">)</span>,</span>
<span>  stars <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"*"</span> <span class="op">=</span> <span class="fl">.05</span>, <span class="st">"**"</span> <span class="op">=</span> <span class="fl">.01</span>, <span class="st">"***"</span> <span class="op">=</span> <span class="fl">.001</span><span class="op">)</span>,</span>
<span>  gof_map <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"nobs"</span>, <span class="st">"aic"</span>, <span class="st">"bic"</span><span class="op">)</span>,</span>
<span>  title <span class="op">=</span> <span class="st">"Models predicting soldier hostility"</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">


    <script src="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js"></script><script>
      // Create table-specific functions using external factory
      const tableFns_l7mlew9o1uum9hcr3iki = TinyTable.createTableFunctions("tinytable_l7mlew9o1uum9hcr3iki");
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: '16', j: 2 }, { i: '16', j: 3 }, { i: '16', j: 4 }, { i: '16', j: 5 } ], css_id: 'tinytable_css_ubdepnhihna7p17x2gzx',}, 
          { positions: [ { i: '13', j: 2 }, { i: '13', j: 3 }, { i: '13', j: 4 }, { i: '13', j: 5 } ], css_id: 'tinytable_css_tbuz3nsez7kzbqc42zac',}, 
          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '14', j: 2 }, { i: '15', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '10', j: 3 }, { i: '11', j: 3 }, { i: '12', j: 3 }, { i: '14', j: 3 }, { i: '15', j: 3 }, { i: '1', j: 4 }, { i: '2', j: 4 }, { i: '3', j: 4 }, { i: '4', j: 4 }, { i: '5', j: 4 }, { i: '6', j: 4 }, { i: '7', j: 4 }, { i: '8', j: 4 }, { i: '9', j: 4 }, { i: '10', j: 4 }, { i: '11', j: 4 }, { i: '12', j: 4 }, { i: '14', j: 4 }, { i: '15', j: 4 }, { i: '1', j: 5 }, { i: '2', j: 5 }, { i: '3', j: 5 }, { i: '4', j: 5 }, { i: '5', j: 5 }, { i: '6', j: 5 }, { i: '7', j: 5 }, { i: '8', j: 5 }, { i: '9', j: 5 }, { i: '10', j: 5 }, { i: '11', j: 5 }, { i: '12', j: 5 }, { i: '14', j: 5 }, { i: '15', j: 5 } ], css_id: 'tinytable_css_k23ku5tkfh6kygpqac7r',}, 
          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 } ], css_id: 'tinytable_css_1fre2xyfbsd52qz3ml5p',}, 
          { positions: [ { i: '16', j: 1 } ], css_id: 'tinytable_css_uudve1rsvcf41eolfsge',}, 
          { positions: [ { i: '13', j: 1 } ], css_id: 'tinytable_css_zhonjanqjj3tpsjq4wnj',}, 
          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '14', j: 1 }, { i: '15', j: 1 } ], css_id: 'tinytable_css_jm7rpzzj8zlwjsdhrwz2',}, 
          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_3ngpwan3ray18wtwnvlz',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  tableFns_l7mlew9o1uum9hcr3iki.styleCell(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script><link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css">
<style>
    /* tinytable css entries after */
    #tinytable_l7mlew9o1uum9hcr3iki td.tinytable_css_ubdepnhihna7p17x2gzx, #tinytable_l7mlew9o1uum9hcr3iki th.tinytable_css_ubdepnhihna7p17x2gzx {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_l7mlew9o1uum9hcr3iki td.tinytable_css_tbuz3nsez7kzbqc42zac, #tinytable_l7mlew9o1uum9hcr3iki th.tinytable_css_tbuz3nsez7kzbqc42zac {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_l7mlew9o1uum9hcr3iki td.tinytable_css_k23ku5tkfh6kygpqac7r, #tinytable_l7mlew9o1uum9hcr3iki th.tinytable_css_k23ku5tkfh6kygpqac7r { text-align: center }
    #tinytable_l7mlew9o1uum9hcr3iki td.tinytable_css_1fre2xyfbsd52qz3ml5p, #tinytable_l7mlew9o1uum9hcr3iki th.tinytable_css_1fre2xyfbsd52qz3ml5p {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_l7mlew9o1uum9hcr3iki td.tinytable_css_uudve1rsvcf41eolfsge, #tinytable_l7mlew9o1uum9hcr3iki th.tinytable_css_uudve1rsvcf41eolfsge {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_l7mlew9o1uum9hcr3iki td.tinytable_css_zhonjanqjj3tpsjq4wnj, #tinytable_l7mlew9o1uum9hcr3iki th.tinytable_css_zhonjanqjj3tpsjq4wnj {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_l7mlew9o1uum9hcr3iki td.tinytable_css_jm7rpzzj8zlwjsdhrwz2, #tinytable_l7mlew9o1uum9hcr3iki th.tinytable_css_jm7rpzzj8zlwjsdhrwz2 { text-align: left }
    #tinytable_l7mlew9o1uum9hcr3iki td.tinytable_css_3ngpwan3ray18wtwnvlz, #tinytable_l7mlew9o1uum9hcr3iki th.tinytable_css_3ngpwan3ray18wtwnvlz {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    </style>
<div class="container">
      <table class="tinytable" id="tinytable_l7mlew9o1uum9hcr3iki" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
<caption>Models predicting soldier hostility</caption>
        <thead><tr>
<th scope="col" data-row="0" data-col="1"> </th>
                <th scope="col" data-row="0" data-col="2">Null</th>
                <th scope="col" data-row="0" data-col="3">Conditional</th>
                <th scope="col" data-row="0" data-col="4">+ Random slope</th>
                <th scope="col" data-row="0" data-col="5">+ Uncorrelated slopes</th>
              </tr></thead>
<tfoot><tr><td colspan="5">* p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td></tr></tfoot>
<tbody>
<tr>
<td data-row="1" data-col="1">(Intercept)</td>
                  <td data-row="1" data-col="2">0.906***</td>
                  <td data-row="1" data-col="3">0.935***</td>
                  <td data-row="1" data-col="4">0.923***</td>
                  <td data-row="1" data-col="5">0.935***</td>
                </tr>
<tr>
<td data-row="2" data-col="1"></td>
                  <td data-row="2" data-col="2">(0.043)</td>
                  <td data-row="2" data-col="3">(0.031)</td>
                  <td data-row="2" data-col="4">(0.032)</td>
                  <td data-row="2" data-col="5">(0.031)</td>
                </tr>
<tr>
<td data-row="3" data-col="1">GTSIG_c</td>
                  <td data-row="3" data-col="2"></td>
                  <td data-row="3" data-col="3">-0.573***</td>
                  <td data-row="3" data-col="4">-0.510***</td>
                  <td data-row="3" data-col="5">-0.571***</td>
                </tr>
<tr>
<td data-row="4" data-col="1"></td>
                  <td data-row="4" data-col="2"></td>
                  <td data-row="4" data-col="3">(0.092)</td>
                  <td data-row="4" data-col="4">(0.085)</td>
                  <td data-row="4" data-col="5">(0.092)</td>
                </tr>
<tr>
<td data-row="5" data-col="1">TSIG_gc</td>
                  <td data-row="5" data-col="2"></td>
                  <td data-row="5" data-col="3">-0.175***</td>
                  <td data-row="5" data-col="4">-0.153***</td>
                  <td data-row="5" data-col="5">-0.162***</td>
                </tr>
<tr>
<td data-row="6" data-col="1"></td>
                  <td data-row="6" data-col="2"></td>
                  <td data-row="6" data-col="3">(0.025)</td>
                  <td data-row="6" data-col="4">(0.031)</td>
                  <td data-row="6" data-col="5">(0.030)</td>
                </tr>
<tr>
<td data-row="7" data-col="1">LEAD_gc</td>
                  <td data-row="7" data-col="2"></td>
                  <td data-row="7" data-col="3">-0.346***</td>
                  <td data-row="7" data-col="4">-0.344***</td>
                  <td data-row="7" data-col="5">-0.339***</td>
                </tr>
<tr>
<td data-row="8" data-col="1"></td>
                  <td data-row="8" data-col="2"></td>
                  <td data-row="8" data-col="3">(0.031)</td>
                  <td data-row="8" data-col="4">(0.031)</td>
                  <td data-row="8" data-col="5">(0.035)</td>
                </tr>
<tr>
<td data-row="9" data-col="1">SD (Intercept COMPID)</td>
                  <td data-row="9" data-col="2">0.240</td>
                  <td data-row="9" data-col="3">0.141</td>
                  <td data-row="9" data-col="4">0.156</td>
                  <td data-row="9" data-col="5">0.142</td>
                </tr>
<tr>
<td data-row="10" data-col="1">SD (TSIG_gc COMPID)</td>
                  <td data-row="10" data-col="2"></td>
                  <td data-row="10" data-col="3"></td>
                  <td data-row="10" data-col="4">0.118</td>
                  <td data-row="10" data-col="5">0.100</td>
                </tr>
<tr>
<td data-row="11" data-col="1">Cor (Intercept~TSIG_gc COMPID)</td>
                  <td data-row="11" data-col="2"></td>
                  <td data-row="11" data-col="3"></td>
                  <td data-row="11" data-col="4">-1.000</td>
                  <td data-row="11" data-col="5"></td>
                </tr>
<tr>
<td data-row="12" data-col="1">SD (LEAD_gc COMPID)</td>
                  <td data-row="12" data-col="2"></td>
                  <td data-row="12" data-col="3"></td>
                  <td data-row="12" data-col="4"></td>
                  <td data-row="12" data-col="5">0.090</td>
                </tr>
<tr>
<td data-row="13" data-col="1">SD (Observations)</td>
                  <td data-row="13" data-col="2">1.008</td>
                  <td data-row="13" data-col="3">0.932</td>
                  <td data-row="13" data-col="4">0.923</td>
                  <td data-row="13" data-col="5">0.924</td>
                </tr>
<tr>
<td data-row="14" data-col="1">Num.Obs.</td>
                  <td data-row="14" data-col="2">2042</td>
                  <td data-row="14" data-col="3">2042</td>
                  <td data-row="14" data-col="4">2042</td>
                  <td data-row="14" data-col="5">2042</td>
                </tr>
<tr>
<td data-row="15" data-col="1">AIC</td>
                  <td data-row="15" data-col="2">5893.4</td>
                  <td data-row="15" data-col="3">5566.9</td>
                  <td data-row="15" data-col="4">5549.0</td>
                  <td data-row="15" data-col="5">5564.2</td>
                </tr>
<tr>
<td data-row="16" data-col="1">BIC</td>
                  <td data-row="16" data-col="2">5910.3</td>
                  <td data-row="16" data-col="3">5600.7</td>
                  <td data-row="16" data-col="4">5594.0</td>
                  <td data-row="16" data-col="5">5609.2</td>
                </tr>
</tbody>
</table>
</div>
<!-- hack to avoid NA insertion in last line -->
</div>
</div>
</section><section id="a-note-on-your-content-review" class="level2" data-number="7.8"><h2 data-number="7.8" class="anchored" data-anchor-id="a-note-on-your-content-review">
<span class="header-section-number">7.8</span> A note on your content review</h2>
<p>Your Module 6 content review uses the Best in Class classroom data rather than these Army data. The steps are the same: calculate effect sizes from the null and conditional models, compare a random slope model using the fit indices, and see what happens when you ask for more random slopes than the data can support. What changes is the substance of the question, not the code.</p>


<!-- -->

</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./05-random-slopes.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Random Slope Models</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./07-three-level.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Three-Level Models</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb47" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Goodness-of-Fit and Effect Sizes</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>**Data for this chapter:** <span class="in">`lq2002.csv`</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>Significance tells you whether an association is distinguishable from zero. It does not tell you whether the association matters, and with large samples the two questions come apart badly. This chapter covers effect sizes for multilevel models and the fit statistics used to choose among competing models.</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>We return to the Gavin and Hofmann (2002) Army data from the last two chapters: 2,042 soldiers nested within 49 companies. The outcome is <span class="in">`HOSTILE`</span>, a hostility scale score that runs from 0 to 4. The predictors are <span class="in">`TSIG`</span> (task significance) and <span class="in">`LEAD`</span> (leadership climate), both measured on each soldier, plus <span class="in">`GTSIG`</span>, the company average of task significance. <span class="in">`COMPID`</span> identifies the company.</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(tidyverse))</span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmerTest)</span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modelsummary)</span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-24"><a href="#cb47-24" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-25"><a href="#cb47-25" aria-hidden="true" tabindex="-1"></a>lq2002 <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="st">"lq2002.csv"</span>) <span class="sc">|&gt;</span></span>
<span id="cb47-26"><a href="#cb47-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(COMPID) <span class="sc">|&gt;</span></span>
<span id="cb47-27"><a href="#cb47-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb47-28"><a href="#cb47-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">TSIG_gc =</span> TSIG <span class="sc">-</span> <span class="fu">mean</span>(TSIG, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),   <span class="co"># group-mean center the level-1 predictors</span></span>
<span id="cb47-29"><a href="#cb47-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">LEAD_gc =</span> LEAD <span class="sc">-</span> <span class="fu">mean</span>(LEAD, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb47-30"><a href="#cb47-30" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb47-31"><a href="#cb47-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb47-32"><a href="#cb47-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb47-33"><a href="#cb47-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">GTSIG_c =</span> GTSIG <span class="sc">-</span> <span class="fu">mean</span>(GTSIG, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)  <span class="co"># grand-mean center the level-2 predictor</span></span>
<span id="cb47-34"><a href="#cb47-34" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb47-35"><a href="#cb47-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-36"><a href="#cb47-36" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(lq2002)</span>
<span id="cb47-37"><a href="#cb47-37" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-38"><a href="#cb47-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-39"><a href="#cb47-39" aria-hidden="true" tabindex="-1"></a>As in the last chapter, we group-mean center the level-1 predictors and grand-mean center the level-2 predictor. <span class="in">`TSIG_gc`</span> and <span class="in">`LEAD_gc`</span> express each soldier's score as a distance from their *own* company's average, so they carry only within-company variation. <span class="in">`GTSIG_c`</span> expresses each company's average task significance as a distance from the average company. The intercept in every model below describes a soldier who sits exactly at their company's average on both predictors, in a company of average task significance.</span>
<span id="cb47-40"><a href="#cb47-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-41"><a href="#cb47-41" aria-hidden="true" tabindex="-1"></a><span class="fu">## Two models to compare</span></span>
<span id="cb47-42"><a href="#cb47-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-45"><a href="#cb47-45" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-46"><a href="#cb47-46" aria-hidden="true" tabindex="-1"></a>m_null <span class="ot">&lt;-</span> <span class="fu">lmer</span>(HOSTILE <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> COMPID), <span class="at">data =</span> lq2002, <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb47-47"><a href="#cb47-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-48"><a href="#cb47-48" aria-hidden="true" tabindex="-1"></a>m_cond <span class="ot">&lt;-</span> <span class="fu">lmer</span>(HOSTILE <span class="sc">~</span> GTSIG_c <span class="sc">+</span> TSIG_gc <span class="sc">+</span> LEAD_gc <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> COMPID),</span>
<span id="cb47-49"><a href="#cb47-49" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> lq2002, <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb47-50"><a href="#cb47-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-51"><a href="#cb47-51" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_cond)</span>
<span id="cb47-52"><a href="#cb47-52" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-53"><a href="#cb47-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-54"><a href="#cb47-54" aria-hidden="true" tabindex="-1"></a>The null model tells us that company membership accounts for only about 5% of the variance in hostility (an ICC of about .05, with $\tau_{00}$ = .058 and $\sigma^2$ = 1.017). In the conditional model, all three predictors are negatively related to hostility, and all three coefficients are clearly distinguishable from zero. Because of the centering, they answer different questions. The <span class="in">`TSIG_gc`</span> and <span class="in">`LEAD_gc`</span> coefficients are *within-company* effects: a soldier who finds the work more significant than their company-mates do, or who reports a better leadership climate than they do, reports less hostility. The `GTSIG_c` coefficient is a *between-company* effect: companies where task significance is high on average have lower average hostility, and the estimate (about $-.57$) is more than three times the within-company one for <span class="in">`TSIG_gc`</span> ($-.17$). The question for the rest of the chapter is how much that matters.</span>
<span id="cb47-55"><a href="#cb47-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-56"><a href="#cb47-56" aria-hidden="true" tabindex="-1"></a><span class="fu">## Proportional reduction in variance</span></span>
<span id="cb47-57"><a href="#cb47-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-58"><a href="#cb47-58" aria-hidden="true" tabindex="-1"></a>The most interpretable multilevel effect sizes ask how much variance a model explains relative to the null model, computed separately at each level. Extract the variance components first:</span>
<span id="cb47-59"><a href="#cb47-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-62"><a href="#cb47-62" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-63"><a href="#cb47-63" aria-hidden="true" tabindex="-1"></a>vc_null <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">VarCorr</span>(m_null))</span>
<span id="cb47-64"><a href="#cb47-64" aria-hidden="true" tabindex="-1"></a>vc_cond <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">VarCorr</span>(m_cond))</span>
<span id="cb47-65"><a href="#cb47-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-66"><a href="#cb47-66" aria-hidden="true" tabindex="-1"></a>tau_null   <span class="ot">&lt;-</span> vc_null<span class="sc">$</span>vcov[vc_null<span class="sc">$</span>grp <span class="sc">==</span> <span class="st">"COMPID"</span>]</span>
<span id="cb47-67"><a href="#cb47-67" aria-hidden="true" tabindex="-1"></a>sigma_null <span class="ot">&lt;-</span> vc_null<span class="sc">$</span>vcov[vc_null<span class="sc">$</span>grp <span class="sc">==</span> <span class="st">"Residual"</span>]</span>
<span id="cb47-68"><a href="#cb47-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-69"><a href="#cb47-69" aria-hidden="true" tabindex="-1"></a>tau_cond   <span class="ot">&lt;-</span> vc_cond<span class="sc">$</span>vcov[vc_cond<span class="sc">$</span>grp <span class="sc">==</span> <span class="st">"COMPID"</span>]</span>
<span id="cb47-70"><a href="#cb47-70" aria-hidden="true" tabindex="-1"></a>sigma_cond <span class="ot">&lt;-</span> vc_cond<span class="sc">$</span>vcov[vc_cond<span class="sc">$</span>grp <span class="sc">==</span> <span class="st">"Residual"</span>]</span>
<span id="cb47-71"><a href="#cb47-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-72"><a href="#cb47-72" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">tau_null =</span> tau_null, <span class="at">sigma_null =</span> sigma_null,</span>
<span id="cb47-73"><a href="#cb47-73" aria-hidden="true" tabindex="-1"></a>  <span class="at">tau_cond =</span> tau_cond, <span class="at">sigma_cond =</span> sigma_cond)</span>
<span id="cb47-74"><a href="#cb47-74" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-75"><a href="#cb47-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-76"><a href="#cb47-76" aria-hidden="true" tabindex="-1"></a>Within-group proportional reduction in variance is the share of soldier-level variance the predictors account for:</span>
<span id="cb47-77"><a href="#cb47-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-80"><a href="#cb47-80" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-81"><a href="#cb47-81" aria-hidden="true" tabindex="-1"></a>wg_prv <span class="ot">&lt;-</span> (sigma_null <span class="sc">-</span> sigma_cond) <span class="sc">/</span> sigma_null</span>
<span id="cb47-82"><a href="#cb47-82" aria-hidden="true" tabindex="-1"></a>wg_prv</span>
<span id="cb47-83"><a href="#cb47-83" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-84"><a href="#cb47-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-85"><a href="#cb47-85" aria-hidden="true" tabindex="-1"></a>Between-group PRV does the same at the company level:</span>
<span id="cb47-86"><a href="#cb47-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-89"><a href="#cb47-89" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-90"><a href="#cb47-90" aria-hidden="true" tabindex="-1"></a>bg_prv <span class="ot">&lt;-</span> (tau_null <span class="sc">-</span> tau_cond) <span class="sc">/</span> tau_null</span>
<span id="cb47-91"><a href="#cb47-91" aria-hidden="true" tabindex="-1"></a>bg_prv</span>
<span id="cb47-92"><a href="#cb47-92" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-93"><a href="#cb47-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-94"><a href="#cb47-94" aria-hidden="true" tabindex="-1"></a>And a total, or multilevel, $R^2$ uses the combined variance:</span>
<span id="cb47-95"><a href="#cb47-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-98"><a href="#cb47-98" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-99"><a href="#cb47-99" aria-hidden="true" tabindex="-1"></a>total_null <span class="ot">&lt;-</span> tau_null <span class="sc">+</span> sigma_null</span>
<span id="cb47-100"><a href="#cb47-100" aria-hidden="true" tabindex="-1"></a>total_cond <span class="ot">&lt;-</span> tau_cond <span class="sc">+</span> sigma_cond</span>
<span id="cb47-101"><a href="#cb47-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-102"><a href="#cb47-102" aria-hidden="true" tabindex="-1"></a>ml_r2 <span class="ot">&lt;-</span> (total_null <span class="sc">-</span> total_cond) <span class="sc">/</span> total_null</span>
<span id="cb47-103"><a href="#cb47-103" aria-hidden="true" tabindex="-1"></a>ml_r2</span>
<span id="cb47-104"><a href="#cb47-104" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-105"><a href="#cb47-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-106"><a href="#cb47-106" aria-hidden="true" tabindex="-1"></a>Be precise about what each denominator refers to when you write these up. WG-PRV is the proportion of *soldier-level* variance explained, not the proportion of all variance. Reporting it as though it were an overall $R^2$ overstates your model considerably.</span>
<span id="cb47-107"><a href="#cb47-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-108"><a href="#cb47-108" aria-hidden="true" tabindex="-1"></a>These data show why. The predictors account for about 15% of the within-company variance (WG-PRV = .146) and about 66% of the between-company variance (BG-PRV = .656). That second number sounds impressive until you remember how little between-company variance there was to explain: $\tau_{00}$ fell from .058 to .020, and company differences were only about 5% of the total to begin with. The multilevel $R^2$ of .174 is the fairer summary of how much of the variation in hostility the model accounts for, and almost all of that explained variance is *within* companies.</span>
<span id="cb47-109"><a href="#cb47-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-110"><a href="#cb47-110" aria-hidden="true" tabindex="-1"></a>Notice also where the between-company reduction comes from. The group-mean centered predictors contain no between-company information by construction, so the only predictor that can explain company differences is <span class="in">`GTSIG_c`</span>. A model with <span class="in">`GTSIG_c`</span> alone has a BG-PRV of about .73, higher than the .66 for the full model, which leads directly to the next point.</span>
<span id="cb47-111"><a href="#cb47-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-112"><a href="#cb47-112" aria-hidden="true" tabindex="-1"></a><span class="fu">### When PRV comes out negative</span></span>
<span id="cb47-113"><a href="#cb47-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-114"><a href="#cb47-114" aria-hidden="true" tabindex="-1"></a>A negative PRV looks like an arithmetic mistake and usually is not. Adding a level-one predictor can increase the estimated level-two variance, because the level-two variance is estimated conditional on everything else in the model. If a student-level predictor is unevenly distributed across teachers, controlling for it can reveal teacher differences that were previously masked. Report the negative value and explain it. Deleting it from your table is the one clearly wrong response.</span>
<span id="cb47-115"><a href="#cb47-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-116"><a href="#cb47-116" aria-hidden="true" tabindex="-1"></a>These data produce a clean example. Fit a model with only the two group-mean centered level-1 predictors:</span>
<span id="cb47-117"><a href="#cb47-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-120"><a href="#cb47-120" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-121"><a href="#cb47-121" aria-hidden="true" tabindex="-1"></a>m_within <span class="ot">&lt;-</span> <span class="fu">lmer</span>(HOSTILE <span class="sc">~</span> TSIG_gc <span class="sc">+</span> LEAD_gc <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> COMPID),</span>
<span id="cb47-122"><a href="#cb47-122" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> lq2002, <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb47-123"><a href="#cb47-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-124"><a href="#cb47-124" aria-hidden="true" tabindex="-1"></a>vc_within    <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">VarCorr</span>(m_within))</span>
<span id="cb47-125"><a href="#cb47-125" aria-hidden="true" tabindex="-1"></a>tau_within   <span class="ot">&lt;-</span> vc_within<span class="sc">$</span>vcov[vc_within<span class="sc">$</span>grp <span class="sc">==</span> <span class="st">"COMPID"</span>]</span>
<span id="cb47-126"><a href="#cb47-126" aria-hidden="true" tabindex="-1"></a>sigma_within <span class="ot">&lt;-</span> vc_within<span class="sc">$</span>vcov[vc_within<span class="sc">$</span>grp <span class="sc">==</span> <span class="st">"Residual"</span>]</span>
<span id="cb47-127"><a href="#cb47-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-128"><a href="#cb47-128" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">wg_prv =</span> (sigma_null <span class="sc">-</span> sigma_within) <span class="sc">/</span> sigma_null,</span>
<span id="cb47-129"><a href="#cb47-129" aria-hidden="true" tabindex="-1"></a>  <span class="at">bg_prv =</span> (tau_null <span class="sc">-</span> tau_within) <span class="sc">/</span> tau_null)</span>
<span id="cb47-130"><a href="#cb47-130" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-131"><a href="#cb47-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-132"><a href="#cb47-132" aria-hidden="true" tabindex="-1"></a>The within-company PRV is positive, about .149, because these predictors do explain soldier-level variance. The between-company PRV is negative, about $-.069$, because $\tau_{00}$ rose slightly, from .058 to .062. Group-mean centered predictors have nothing to say about differences between companies, so there was no reduction to expect. Once the within-company variance is accounted for, the estimate of the company-level variance shifts a little. The right reading is "no reduction in between-company variance," and the right response is to report it.</span>
<span id="cb47-133"><a href="#cb47-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-134"><a href="#cb47-134" aria-hidden="true" tabindex="-1"></a><span class="fu">## The `performance` package version</span></span>
<span id="cb47-135"><a href="#cb47-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-138"><a href="#cb47-138" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-139"><a href="#cb47-139" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">r2</span>(m_cond)</span>
<span id="cb47-140"><a href="#cb47-140" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-141"><a href="#cb47-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-142"><a href="#cb47-142" aria-hidden="true" tabindex="-1"></a>This reports marginal $R^2$, the variance explained by fixed effects alone (.171), and conditional $R^2$, the variance explained by fixed and random effects together (.189). These are Nakagawa's measures, and they answer a slightly different question than the PRV statistics above. Marginal $R^2$ lands close to our multilevel $R^2$ of .174 but is not identical to it. The conditional value is only a little larger than the marginal one because company differences are such a small share of the variance. Both are defensible. Say which you used.</span>
<span id="cb47-143"><a href="#cb47-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-144"><a href="#cb47-144" aria-hidden="true" tabindex="-1"></a><span class="fu">## Translating for a non-technical audience</span></span>
<span id="cb47-145"><a href="#cb47-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-146"><a href="#cb47-146" aria-hidden="true" tabindex="-1"></a>Suppose a battalion commander asks how much leadership climate matters for hostility. Effect sizes in variance units rarely land. Predicted values usually do:</span>
<span id="cb47-147"><a href="#cb47-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-150"><a href="#cb47-150" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-151"><a href="#cb47-151" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb47-152"><a href="#cb47-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-153"><a href="#cb47-153" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggeffects)</span>
<span id="cb47-154"><a href="#cb47-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-155"><a href="#cb47-155" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpredict</span>(m_cond, <span class="at">terms =</span> <span class="st">"LEAD_gc [meansd]"</span>)</span>
<span id="cb47-156"><a href="#cb47-156" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-157"><a href="#cb47-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-158"><a href="#cb47-158" aria-hidden="true" tabindex="-1"></a>The three rows show predicted hostility for a soldier one standard deviation below their company's average on leadership climate (1.20), at their company's average (0.94), and one standard deviation above (0.67), holding the other predictors at their means. Because <span class="in">`LEAD_gc`</span> is centered within companies, one standard deviation here is the typical spread among soldiers in the same company (0.77), not the spread across the whole Army. Reporting that a soldier who rates leadership climate one standard deviation higher than their company-mates do is predicted to score about 0.27 points lower on hostility, on a scale that runs from 0 to 4, communicates more than a proportional reduction in variance ever will. A standardized mean difference is another good option when your audience is used to reading them: 0.27 points is about a quarter of a standard deviation of hostility (SD = 1.04).</span>
<span id="cb47-159"><a href="#cb47-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-160"><a href="#cb47-160" aria-hidden="true" tabindex="-1"></a><span class="fu">## Model comparison with information criteria</span></span>
<span id="cb47-161"><a href="#cb47-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-162"><a href="#cb47-162" aria-hidden="true" tabindex="-1"></a>Now a different question: which model should we report? Start by adding a random slope for task significance.</span>
<span id="cb47-163"><a href="#cb47-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-166"><a href="#cb47-166" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-167"><a href="#cb47-167" aria-hidden="true" tabindex="-1"></a>m_slope <span class="ot">&lt;-</span> <span class="fu">lmer</span>(HOSTILE <span class="sc">~</span> GTSIG_c <span class="sc">+</span> TSIG_gc <span class="sc">+</span> LEAD_gc <span class="sc">+</span></span>
<span id="cb47-168"><a href="#cb47-168" aria-hidden="true" tabindex="-1"></a>                  (<span class="dv">1</span> <span class="sc">+</span> TSIG_gc <span class="sc">|</span> COMPID),</span>
<span id="cb47-169"><a href="#cb47-169" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> lq2002, <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb47-170"><a href="#cb47-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-171"><a href="#cb47-171" aria-hidden="true" tabindex="-1"></a><span class="fu">ranova</span>(m_slope)</span>
<span id="cb47-172"><a href="#cb47-172" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-173"><a href="#cb47-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-176"><a href="#cb47-176" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-177"><a href="#cb47-177" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m_cond, m_slope)</span>
<span id="cb47-178"><a href="#cb47-178" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-179"><a href="#cb47-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-182"><a href="#cb47-182" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-183"><a href="#cb47-183" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(m_cond, m_slope)</span>
<span id="cb47-184"><a href="#cb47-184" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(m_cond, m_slope)</span>
<span id="cb47-185"><a href="#cb47-185" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-186"><a href="#cb47-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-187"><a href="#cb47-187" aria-hidden="true" tabindex="-1"></a><span class="fu">### When the criteria disagree</span></span>
<span id="cb47-188"><a href="#cb47-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-189"><a href="#cb47-189" aria-hidden="true" tabindex="-1"></a>They often will, and understanding why is more useful than memorizing a rule. AIC and BIC both penalize complexity, but BIC's penalty grows with sample size while AIC's does not. With a large sample, BIC prefers simpler models more aggressively than AIC does. The likelihood ratio test is a third thing again: a hypothesis test with a null of no improvement, which inherits all the usual sensitivities to sample size.</span>
<span id="cb47-190"><a href="#cb47-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-191"><a href="#cb47-191" aria-hidden="true" tabindex="-1"></a>For random effects there is an additional wrinkle. Testing whether a variance component equals zero puts the null on the boundary of the parameter space, which makes the usual chi-square reference distribution conservative, and <span class="in">`ranova()`</span> does not correct for it. It is a reason not to treat a p-value of .06 on a variance component as decisive.</span>
<span id="cb47-192"><a href="#cb47-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-193"><a href="#cb47-193" aria-hidden="true" tabindex="-1"></a>When the criteria disagree, say so, state which you weighted and why, and check whether your substantive conclusions change between the two models. If the treatment effect is essentially identical either way, the model choice matters less than it appears to.</span>
<span id="cb47-194"><a href="#cb47-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-195"><a href="#cb47-195" aria-hidden="true" tabindex="-1"></a>For this random slope, the criteria do not disagree. The likelihood ratio test is clearly significant, $\chi^2$(2) = 21.72, $p$ &lt; .001. AIC drops from 5547.9 to 5530.2, and even BIC, with its heavier penalty, drops from 5581.6 to 5575.2. Everything points toward keeping the slope.</span>
<span id="cb47-196"><a href="#cb47-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-197"><a href="#cb47-197" aria-hidden="true" tabindex="-1"></a>Agreement among the criteria does not make a model trustworthy, though. Look inside it:</span>
<span id="cb47-198"><a href="#cb47-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-201"><a href="#cb47-201" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-202"><a href="#cb47-202" aria-hidden="true" tabindex="-1"></a><span class="fu">VarCorr</span>(m_slope)</span>
<span id="cb47-203"><a href="#cb47-203" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-204"><a href="#cb47-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-205"><a href="#cb47-205" aria-hidden="true" tabindex="-1"></a>R printed <span class="in">`boundary (singular) fit`</span> when it fitted this model, and the correlation between the intercept and the <span class="in">`TSIG_gc`</span> slope is exactly $-1.00$. That is not a finding about the Army. It is the model reporting that it has run out of information, which is the same thing we saw in the last chapter. The slope variance is real enough that the fit statistics reward it, but the *correlation* is more than 49 companies can support.</span>
<span id="cb47-206"><a href="#cb47-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-207"><a href="#cb47-207" aria-hidden="true" tabindex="-1"></a><span class="fu">## When a model will not converge</span></span>
<span id="cb47-208"><a href="#cb47-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-209"><a href="#cb47-209" aria-hidden="true" tabindex="-1"></a>Ask for two random slopes and things get worse:</span>
<span id="cb47-210"><a href="#cb47-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-213"><a href="#cb47-213" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-214"><a href="#cb47-214" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: true</span></span>
<span id="cb47-215"><a href="#cb47-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-216"><a href="#cb47-216" aria-hidden="true" tabindex="-1"></a>m_two_slopes <span class="ot">&lt;-</span> <span class="fu">lmer</span>(HOSTILE <span class="sc">~</span> GTSIG_c <span class="sc">+</span> TSIG_gc <span class="sc">+</span> LEAD_gc <span class="sc">+</span></span>
<span id="cb47-217"><a href="#cb47-217" aria-hidden="true" tabindex="-1"></a>                       (<span class="dv">1</span> <span class="sc">+</span> TSIG_gc <span class="sc">+</span> LEAD_gc <span class="sc">|</span> COMPID),</span>
<span id="cb47-218"><a href="#cb47-218" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> lq2002, <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb47-219"><a href="#cb47-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-220"><a href="#cb47-220" aria-hidden="true" tabindex="-1"></a><span class="fu">VarCorr</span>(m_two_slopes)</span>
<span id="cb47-221"><a href="#cb47-221" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-222"><a href="#cb47-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-223"><a href="#cb47-223" aria-hidden="true" tabindex="-1"></a>This one fits, but R again reports a singular fit. The printed correlations ($-.87$, $-.10$, and $-.41$) look unremarkable, which is what makes this case easy to miss. The problem is hiding in the covariance matrix of the three random effects: it has a zero eigenvalue, meaning some combination of the intercept and the two slopes has no variance at all. The model has collapsed onto something smaller than the structure we asked for.</span>
<span id="cb47-224"><a href="#cb47-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-225"><a href="#cb47-225" aria-hidden="true" tabindex="-1"></a>It is worth doing the arithmetic yourself before fitting a complex random effects structure. A model with $q$ random effects per company needs $q(q + 1)/2$ variance and covariance parameters: 1 for a random intercept alone, 3 for an intercept and one slope, and 6 for an intercept and two slopes. Compare that to the number of level-two units, not the number of soldiers. Slope variance is learned from how much slopes *differ across companies*, and we have only 49 companies, so 2,042 soldiers do not help as much as you might hope. The more parameters you ask 49 companies to support, the less well each one is determined, and the first thing to give is usually a correlation.</span>
<span id="cb47-226"><a href="#cb47-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-227"><a href="#cb47-227" aria-hidden="true" tabindex="-1"></a>The more common situation is a message like this one rather than a failure to run. Instead of an outright refusal you get a singular fit, you might get a variance component estimated at essentially zero, or a correlation of exactly 1 or -1. Those are the same messages, just delivered a little more politely. The data cannot support that many random effects.</span>
<span id="cb47-228"><a href="#cb47-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-229"><a href="#cb47-229" aria-hidden="true" tabindex="-1"></a>So how might you respond? You basically have three choices, in order from most to least preferred: 1) drop the random slope correlations and keep both slopes uncorrelated; 2) drop the less theoretically important slope; or 3) return to a random intercept model and acknowledge in your write-up that slope variation could not be estimated with these data. All three are defensible, and all are better than reporting a singular model as though it converged normally.</span>
<span id="cb47-230"><a href="#cb47-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-231"><a href="#cb47-231" aria-hidden="true" tabindex="-1"></a>Here is the first option:</span>
<span id="cb47-232"><a href="#cb47-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-235"><a href="#cb47-235" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-236"><a href="#cb47-236" aria-hidden="true" tabindex="-1"></a><span class="co"># Uncorrelated random effects</span></span>
<span id="cb47-237"><a href="#cb47-237" aria-hidden="true" tabindex="-1"></a>m_uncorr <span class="ot">&lt;-</span> <span class="fu">lmer</span>(HOSTILE <span class="sc">~</span> GTSIG_c <span class="sc">+</span> TSIG_gc <span class="sc">+</span> LEAD_gc <span class="sc">+</span></span>
<span id="cb47-238"><a href="#cb47-238" aria-hidden="true" tabindex="-1"></a>                   (<span class="dv">1</span> <span class="sc">|</span> COMPID) <span class="sc">+</span> (<span class="dv">0</span> <span class="sc">+</span> TSIG_gc <span class="sc">|</span> COMPID) <span class="sc">+</span> (<span class="dv">0</span> <span class="sc">+</span> LEAD_gc <span class="sc">|</span> COMPID),</span>
<span id="cb47-239"><a href="#cb47-239" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> lq2002, <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb47-240"><a href="#cb47-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-241"><a href="#cb47-241" aria-hidden="true" tabindex="-1"></a><span class="fu">isSingular</span>(m_uncorr)</span>
<span id="cb47-242"><a href="#cb47-242" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-243"><a href="#cb47-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-246"><a href="#cb47-246" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-247"><a href="#cb47-247" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m_cond, m_uncorr)</span>
<span id="cb47-248"><a href="#cb47-248" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(m_cond, m_uncorr)</span>
<span id="cb47-249"><a href="#cb47-249" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(m_cond, m_uncorr)</span>
<span id="cb47-250"><a href="#cb47-250" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-251"><a href="#cb47-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-252"><a href="#cb47-252" aria-hidden="true" tabindex="-1"></a>This model is not singular, so it is a fit we can report honestly. It also gives us the disagreement described above, in miniature. The likelihood ratio test lands right at the edge of conventional significance ($\chi^2$(2) = 6.00, $p$ = .050), and AIC edges toward the model with random slopes (5545.9 versus 5547.9), while BIC clearly favors the simpler random intercept model (5590.9 versus 5581.6). BIC charges each extra parameter ln(2,042) $\approx$ 7.6, against 2 for AIC, so two additional variance components cost about 15 on the BIC scale and only 4 on the AIC scale.</span>
<span id="cb47-253"><a href="#cb47-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-254"><a href="#cb47-254" aria-hidden="true" tabindex="-1"></a>So which do we report? Check whether the substantive story changes. The fixed effects barely move: <span class="in">`GTSIG_c`</span> goes from $-.573$ to $-.571$, <span class="in">`TSIG_gc`</span> from $-.175$ to $-.162$, and <span class="in">`LEAD_gc`</span> from $-.346$ to $-.339$. All three stay negative and clearly distinguishable from zero in both models. Because the conclusions about the predictors do not depend on the choice, either model is defensible as long as you say which you used and why, and report the other as a check.</span>
<span id="cb47-255"><a href="#cb47-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-256"><a href="#cb47-256" aria-hidden="true" tabindex="-1"></a><span class="fu">## Putting it together</span></span>
<span id="cb47-257"><a href="#cb47-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-260"><a href="#cb47-260" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-261"><a href="#cb47-261" aria-hidden="true" tabindex="-1"></a><span class="fu">modelsummary</span>(</span>
<span id="cb47-262"><a href="#cb47-262" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="st">"Null"</span> <span class="ot">=</span> m_null, <span class="st">"Conditional"</span> <span class="ot">=</span> m_cond,</span>
<span id="cb47-263"><a href="#cb47-263" aria-hidden="true" tabindex="-1"></a>       <span class="st">"+ Random slope"</span> <span class="ot">=</span> m_slope, <span class="st">"+ Uncorrelated slopes"</span> <span class="ot">=</span> m_uncorr),</span>
<span id="cb47-264"><a href="#cb47-264" aria-hidden="true" tabindex="-1"></a>  <span class="at">stars =</span> <span class="fu">c</span>(<span class="st">"*"</span> <span class="ot">=</span> .<span class="dv">05</span>, <span class="st">"**"</span> <span class="ot">=</span> .<span class="dv">01</span>, <span class="st">"***"</span> <span class="ot">=</span> .<span class="dv">001</span>),</span>
<span id="cb47-265"><a href="#cb47-265" aria-hidden="true" tabindex="-1"></a>  <span class="at">gof_map =</span> <span class="fu">c</span>(<span class="st">"nobs"</span>, <span class="st">"aic"</span>, <span class="st">"bic"</span>),</span>
<span id="cb47-266"><a href="#cb47-266" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"Models predicting soldier hostility"</span></span>
<span id="cb47-267"><a href="#cb47-267" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb47-268"><a href="#cb47-268" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-269"><a href="#cb47-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-270"><a href="#cb47-270" aria-hidden="true" tabindex="-1"></a><span class="fu">## A note on your content review</span></span>
<span id="cb47-271"><a href="#cb47-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-272"><a href="#cb47-272" aria-hidden="true" tabindex="-1"></a>Your Module 6 content review uses the Best in Class classroom data rather than these Army data. The steps are the same: calculate effect sizes from the null and conditional models, compare a random slope model using the fit indices, and see what happens when you ask for more random slopes than the data can support. What changes is the substance of the question, not the code.</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">Applied Multilevel Modeling in R</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">Built with <a href="https://quarto.org">Quarto</a></div>
  </div>
</footer>


</body></html>