<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="An online companion to Dr.&nbsp;Broda’s Multilevel Modeling course (EDUS 664) at Virginia Commonwealth University. Each chapter works through the R code for one course module.">
<title>Applied Multilevel Modeling in R - 12&nbsp; Checking Assumptions for MLMs</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./11-cross-classified.html" rel="next">
<link href="./09-binary-outcomes.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./10-assumptions.html">Checking and Complicating</a></li><li class="breadcrumb-item"><a href="./10-assumptions.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Checking Assumptions for MLMs</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Applied Multilevel Modeling in R</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/YOURUSERNAME/mlm-textbook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
<li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
</div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-getting-started.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting Started with R and RStudio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-reading-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Reading: Regression and Where It Runs Out</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-regression-review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Review of Linear Regression</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Two-Level Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-null-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Intro to MLM and the Null Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-random-intercept.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Conditional Random Intercept Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-random-slopes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Random Slope Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-fit-effect-sizes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Goodness-of-Fit and Effect Sizes</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Extending the Model</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-three-level.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Three-Level Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08a-growth-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Intro to Growth Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08b-growth-advanced.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Advanced Growth Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-binary-outcomes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Binary and Generalized Linear Mixed Models</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Checking and Complicating</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-assumptions.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Checking Assumptions for MLMs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-cross-classified.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Cross-Classified Linear Mixed Models</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#load-in-our-mvp-packages" id="toc-load-in-our-mvp-packages" class="nav-link active" data-scroll-target="#load-in-our-mvp-packages"><span class="header-section-number">12.1</span> Load in our MVP packages</a></li>
  <li>
<a href="#part-1-loading-in-the-data-and-then-recoding-variables" id="toc-part-1-loading-in-the-data-and-then-recoding-variables" class="nav-link" data-scroll-target="#part-1-loading-in-the-data-and-then-recoding-variables"><span class="header-section-number">12.2</span> Part 1: loading in the data, and then recoding variables</a>
  <ul class="collapse">
<li><a href="#load-in-the-data" id="toc-load-in-the-data" class="nav-link" data-scroll-target="#load-in-the-data"><span class="header-section-number">12.2.1</span> Load in the data</a></li>
  <li><a href="#the-describe-function-from-hmisc-is-a-nice-codebook" id="toc-the-describe-function-from-hmisc-is-a-nice-codebook" class="nav-link" data-scroll-target="#the-describe-function-from-hmisc-is-a-nice-codebook"><span class="header-section-number">12.2.2</span> The <code>describe</code> function from <code>Hmisc</code> is a nice codebook</a></li>
  </ul>
</li>
  <li><a href="#a-little-quick-cleaning" id="toc-a-little-quick-cleaning" class="nav-link" data-scroll-target="#a-little-quick-cleaning"><span class="header-section-number">12.3</span> A little quick cleaning</a></li>
  <li>
<a href="#part-2-find-your-final-or-preferred-model" id="toc-part-2-find-your-final-or-preferred-model" class="nav-link" data-scroll-target="#part-2-find-your-final-or-preferred-model"><span class="header-section-number">12.4</span> Part 2: find your “final” or preferred model</a>
  <ul class="collapse">
<li><a href="#start-with-a-null-growth-model-since-this-is-longitudinal-data" id="toc-start-with-a-null-growth-model-since-this-is-longitudinal-data" class="nav-link" data-scroll-target="#start-with-a-null-growth-model-since-this-is-longitudinal-data"><span class="header-section-number">12.4.1</span> Start with a null growth model since this is longitudinal data</a></li>
  <li><a href="#add-in-quadratic-effects" id="toc-add-in-quadratic-effects" class="nav-link" data-scroll-target="#add-in-quadratic-effects"><span class="header-section-number">12.4.2</span> Add in quadratic effects</a></li>
  <li><a href="#add-in-cubic-effects" id="toc-add-in-cubic-effects" class="nav-link" data-scroll-target="#add-in-cubic-effects"><span class="header-section-number">12.4.3</span> Add in cubic effects</a></li>
  <li><a href="#both-quadratic-and-cubic-effects" id="toc-both-quadratic-and-cubic-effects" class="nav-link" data-scroll-target="#both-quadratic-and-cubic-effects"><span class="header-section-number">12.4.4</span> Both quadratic and cubic effects</a></li>
  <li><a href="#now-for-some-more-predictors" id="toc-now-for-some-more-predictors" class="nav-link" data-scroll-target="#now-for-some-more-predictors"><span class="header-section-number">12.4.5</span> Now for some more predictors</a></li>
  </ul>
</li>
  <li><a href="#use-the-augment-function-from-the-broom.mixed-package" id="toc-use-the-augment-function-from-the-broom.mixed-package" class="nav-link" data-scroll-target="#use-the-augment-function-from-the-broom.mixed-package"><span class="header-section-number">12.5</span> Use the <code>augment</code> function from the <code>broom.mixed</code> package</a></li>
  <li>
<a href="#step-1-assess-normality-of-residuals" id="toc-step-1-assess-normality-of-residuals" class="nav-link" data-scroll-target="#step-1-assess-normality-of-residuals"><span class="header-section-number">12.6</span> Step 1: assess normality of residuals</a>
  <ul class="collapse">
<li><a href="#visually-with-a-histogram" id="toc-visually-with-a-histogram" class="nav-link" data-scroll-target="#visually-with-a-histogram"><span class="header-section-number">12.6.1</span> Visually, with a histogram</a></li>
  <li><a href="#statistically-with-the-shapiro-wilk-test" id="toc-statistically-with-the-shapiro-wilk-test" class="nav-link" data-scroll-target="#statistically-with-the-shapiro-wilk-test"><span class="header-section-number">12.6.2</span> Statistically, with the Shapiro-Wilk test</a></li>
  </ul>
</li>
  <li>
<a href="#step-2-use-a-residuals-vs.-fitted-rvf-plot-to-assess-homoskedasticity-of-errors" id="toc-step-2-use-a-residuals-vs.-fitted-rvf-plot-to-assess-homoskedasticity-of-errors" class="nav-link" data-scroll-target="#step-2-use-a-residuals-vs.-fitted-rvf-plot-to-assess-homoskedasticity-of-errors"><span class="header-section-number">12.7</span> Step 2: use a residuals vs.&nbsp;fitted (RVF) plot to assess homoskedasticity of errors</a>
  <ul class="collapse">
<li><a href="#basic-rvf-plot-without-groups" id="toc-basic-rvf-plot-without-groups" class="nav-link" data-scroll-target="#basic-rvf-plot-without-groups"><span class="header-section-number">12.7.1</span> Basic RVF plot, without groups</a></li>
  <li><a href="#same-thing-but-with-added-color-by-year0" id="toc-same-thing-but-with-added-color-by-year0" class="nav-link" data-scroll-target="#same-thing-but-with-added-color-by-year0"><span class="header-section-number">12.7.2</span> Same thing, but with added color by year0</a></li>
  </ul>
</li>
  <li><a href="#step-3-use-cooks-distance-to-identify-outliers" id="toc-step-3-use-cooks-distance-to-identify-outliers" class="nav-link" data-scroll-target="#step-3-use-cooks-distance-to-identify-outliers"><span class="header-section-number">12.8</span> Step 3: use Cook’s distance to identify outliers</a></li>
  <li><a href="#step-4-re-run-model-with-robust-standard-errors" id="toc-step-4-re-run-model-with-robust-standard-errors" class="nav-link" data-scroll-target="#step-4-re-run-model-with-robust-standard-errors"><span class="header-section-number">12.9</span> Step 4: re-run model with robust standard errors</a></li>
  <li><a href="#step-5-re-run-model-with-outliers-removed-cooks-distance-.10" id="toc-step-5-re-run-model-with-outliers-removed-cooks-distance-.10" class="nav-link" data-scroll-target="#step-5-re-run-model-with-outliers-removed-cooks-distance-.10"><span class="header-section-number">12.10</span> Step 5: re-run model with outliers removed (Cook’s distance &gt; .10)</a></li>
  <li><a href="#step-6-compare-original-final-model-robust-model-and-trimmed-model" id="toc-step-6-compare-original-final-model-robust-model-and-trimmed-model" class="nav-link" data-scroll-target="#step-6-compare-original-final-model-robust-model-and-trimmed-model"><span class="header-section-number">12.11</span> Step 6: compare original “final” model, robust model, and trimmed model</a></li>
  <li><a href="#writing-it-up" id="toc-writing-it-up" class="nav-link" data-scroll-target="#writing-it-up"><span class="header-section-number">12.12</span> Writing it up</a></li>
  </ul><div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/YOURUSERNAME/mlm-textbook/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">
<span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Checking Assumptions for MLMs</span>
</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p><strong>Data for this chapter:</strong> <code>productivity.dta</code></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Data file needed
</div>
</div>
<div class="callout-body-container callout-body">
<p>Copy <code>productivity.dta</code> into this project folder before rendering.</p>
</div>
</div>
<p>This week, we will use the <code>productivity</code> dataset from Stata, developed by Dr.&nbsp;Alicia Munnell and published by the Federal Reserve Bank of Boston (1990). It tracks US states over time, so observations are years nested within states.</p>
<p>Diagnostics are not a pass-fail checklist. They are evidence you weigh, and the useful question is never “was an assumption violated” but “is this violation bad enough to change what I conclude.” This chapter runs the standard checks and then does the thing that actually settles the question: refits the model under different assumptions and sees whether the answer moves.</p>
<section id="load-in-our-mvp-packages" class="level2" data-number="12.1"><h2 data-number="12.1" class="anchored" data-anchor-id="load-in-our-mvp-packages">
<span class="header-section-number">12.1</span> Load in our MVP packages</h2>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/message.html">suppressPackageStartupMessages</a></span><span class="op">(</span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/lme4/lme4/">lme4</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://hbiostat.org/R/Hmisc/">Hmisc</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="part-1-loading-in-the-data-and-then-recoding-variables" class="level2" data-number="12.2"><h2 data-number="12.2" class="anchored" data-anchor-id="part-1-loading-in-the-data-and-then-recoding-variables">
<span class="header-section-number">12.2</span> Part 1: loading in the data, and then recoding variables</h2>
<section id="load-in-the-data" class="level3" data-number="12.2.1"><h3 data-number="12.2.1" class="anchored" data-anchor-id="load-in-the-data">
<span class="header-section-number">12.2.1</span> Load in the data</h3>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">productivity</span> <span class="op">&lt;-</span> <span class="fu">haven</span><span class="fu">::</span><span class="fu"><a href="https://haven.tidyverse.org/reference/read_dta.html">read_dta</a></span><span class="op">(</span><span class="st">"productivity.dta"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">productivity</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 816
Columns: 11
$ state   &lt;dbl&gt; 19, 44, 5, 41, 45, 16, 37, 20, 25, 11, 14, 40, 23, 42, 4, 26, …
$ region  &lt;dbl&gt; 1, 5, 8, 7, 9, 7, 1, 3, 4, 3, 4, 6, 4, 8, 9, 8, 3, 8, 3, 1, 2,…
$ year    &lt;dbl&gt; 1970, 1970, 1970, 1970, 1970, 1970, 1970, 1970, 1970, 1970, 19…
$ public  &lt;dbl&gt; 21923.28, 20732.56, 11402.52, 53639.88, 25751.49, 19638.31, 43…
$ hwy     &lt;dbl&gt; 9.052737, 9.329386, 8.390089, 10.163615, 9.066138, 9.199419, 7…
$ water   &lt;dbl&gt; 7.714320, 7.892493, 7.680190, 9.030341, 8.142238, 7.886390, 6.…
$ other   &lt;dbl&gt; 9.318403, 8.823389, 8.483487, 9.870202, 9.522063, 8.865893, 7.…
$ private &lt;dbl&gt; 10.543170, 10.454692, 10.073642, 12.272218, 10.529598, 11.4907…
$ gsp     &lt;dbl&gt; 11.073319, 10.784545, 10.153818, 11.988675, 10.577044, 11.0455…
$ emp     &lt;dbl&gt; 7.715793, 7.325742, 6.620340, 8.195582, 6.984160, 6.940803, 5.…
$ unemp   &lt;dbl&gt; 4.6, 3.4, 4.4, 4.4, 9.1, 6.6, 5.2, 6.7, 3.1, 4.1, 4.8, 4.8, 3.…</code></pre>
</div>
</div>
</section><section id="the-describe-function-from-hmisc-is-a-nice-codebook" class="level3" data-number="12.2.2"><h3 data-number="12.2.2" class="anchored" data-anchor-id="the-describe-function-from-hmisc-is-a-nice-codebook">
<span class="header-section-number">12.2.2</span> The <code>describe</code> function from <code>Hmisc</code> is a nice codebook</h3>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">Hmisc</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/Hmisc/man/describe.html">describe</a></span><span class="op">(</span><span class="va">productivity</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>productivity 

 11  Variables      816  Observations
--------------------------------------------------------------------------------
state : states 1-48  Format:%9.0g 
       n  missing distinct     Info     Mean  pMedian      Gmd      .05 
     816        0       48        1     24.5     24.5    16.01     3.00 
     .10      .25      .50      .75      .90      .95 
    5.00    12.75    24.50    36.25    44.00    46.00 

lowest :  1  2  3  4  5, highest: 44 45 46 47 48
--------------------------------------------------------------------------------
region : regions 1-9  Format:%9.0g 
       n  missing distinct     Info     Mean  pMedian      Gmd 
     816        0        9    0.983    4.958        5    2.811 
                                                                
Value          1     2     3     4     5     6     7     8     9
Frequency    102    51    85   119   136    68    68   136    51
Proportion 0.125 0.062 0.104 0.146 0.167 0.083 0.083 0.167 0.062
--------------------------------------------------------------------------------
year : years 1970-1986  Format:%9.0g 
       n  missing distinct     Info     Mean  pMedian      Gmd      .05 
     816        0       17    0.997     1978     1978    5.654     1970 
     .10      .25      .50      .75      .90      .95 
    1971     1974     1978     1982     1985     1986 
                                                                            
Value       1970  1971  1972  1973  1974  1975  1976  1977  1978  1979  1980
Frequency     48    48    48    48    48    48    48    48    48    48    48
Proportion 0.059 0.059 0.059 0.059 0.059 0.059 0.059 0.059 0.059 0.059 0.059
                                              
Value       1981  1982  1983  1984  1985  1986
Frequency     48    48    48    48    48    48
Proportion 0.059 0.059 0.059 0.059 0.059 0.059
--------------------------------------------------------------------------------
public : public capital stock  Format:%9.0g 
       n  missing distinct     Info     Mean  pMedian      Gmd      .05 
     816        0      815        1    25037    18713    24904     4025 
     .10      .25      .50      .75      .90      .95 
    4407     7097    17572    27692    56488    69628 

lowest : 2627.12 2756.19 2894.58 2925.39 2927.85
highest: 139514  139662  139777  139910  140217 
--------------------------------------------------------------------------------
hwy : log(highway component of public)  Format:%9.0g 
       n  missing distinct     Info     Mean  pMedian      Gmd      .05 
     816        0      816        1      8.9    8.894   0.9192    7.639 
     .10      .25      .50      .75      .90      .95 
   7.758    8.258    8.930    9.330   10.113   10.308 

lowest : 7.51051 7.51216 7.51681 7.52155 7.52692
highest: 10.7593 10.7608 10.7699 10.77   10.7727
--------------------------------------------------------------------------------
water : log(water component of public)  Format:%9.0g 
       n  missing distinct     Info     Mean  pMedian      Gmd      .05 
     816        0      815        1      7.6    7.613      1.3    5.662 
     .10      .25      .50      .75      .90      .95 
   5.962    6.639    7.726    8.371    9.097    9.299 

lowest : 5.43136 5.43747 5.44029 5.45357 5.4563 
highest: 10.0649 10.0786 10.0792 10.0909 10.1102
--------------------------------------------------------------------------------
other : log(bldg/other component of public)  Format:%9.0g 
       n  missing distinct     Info     Mean  pMedian      Gmd      .05 
     816        0      816        1    8.736    8.754    1.245    6.995 
     .10      .25      .50      .75      .90      .95 
   7.202    7.819    8.855    9.359   10.067   10.265 

lowest : 6.28877 6.4271  6.50578 6.50776 6.51569
highest: 11.2758 11.2893 11.2968 11.2978 11.2988
--------------------------------------------------------------------------------
private : log(private capital stock)  Format:%9.0g 
       n  missing distinct     Info     Mean  pMedian      Gmd      .05 
     816        0      816        1    10.56    10.57    1.044    8.926 
     .10      .25      .50      .75      .90      .95 
   9.285    9.983   10.613   11.079   11.791   12.061 

lowest : 8.30714 8.35474 8.39001 8.42893 8.47431
highest: 12.7913 12.8    12.8043 12.8058 12.8356
--------------------------------------------------------------------------------
gsp : log(gross state product)  Format:%9.0g 
       n  missing distinct     Info     Mean  pMedian      Gmd      .05 
     816        0      807        1    10.51    10.51    1.165    8.961 
     .10      .25      .50      .75      .90      .95 
   9.099    9.711   10.596   11.129   11.882   12.392 

lowest : 8.37885 8.39796 8.41804 8.4362  8.44505
highest: 12.8485 12.8753 12.9493 13.0038 13.0488
--------------------------------------------------------------------------------
emp : log(non-agriculture payrolls)  Format:%9.0g 
       n  missing distinct     Info     Mean  pMedian      Gmd      .05 
     816        0      807        1    6.978    6.987    1.166    5.332 
     .10      .25      .50      .75      .90      .95 
   5.516    6.163    7.060    7.656    8.381    8.642 

lowest : 4.68491 4.70953 4.76473 4.83708 4.91632
highest: 9.20691 9.20887 9.26615 9.30374 9.32883
--------------------------------------------------------------------------------
unemp : state unemployment rate  Format:%9.0g 
       n  missing distinct     Info     Mean  pMedian      Gmd      .05 
     816        0       80        1    6.602     6.45    2.456      3.6 
     .10      .25      .50      .75      .90      .95 
     4.0      5.0      6.2      7.9      9.5     11.0 

lowest : 2.8 2.9 3   3.1 3.2, highest: 13  14  15  16  18 
--------------------------------------------------------------------------------</code></pre>
</div>
</div>
</section></section><section id="a-little-quick-cleaning" class="level2" data-number="12.3"><h2 data-number="12.3" class="anchored" data-anchor-id="a-little-quick-cleaning">
<span class="header-section-number">12.3</span> A little quick cleaning</h2>
<p>Convert region to a factor variable, rescale public capital stock, “zero out” year, and create nonlinear terms.</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">prod.clean</span> <span class="op">&lt;-</span> <span class="va">productivity</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="va">.</span>,</span>
<span>         region.fac <span class="op">=</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/as_factor.html">as_factor</a></span><span class="op">(</span><span class="va">region</span><span class="op">)</span>,</span>
<span>         year0 <span class="op">=</span> <span class="va">year</span> <span class="op">-</span> <span class="fl">1970</span>,</span>
<span>         year_sq <span class="op">=</span> <span class="va">year0</span><span class="op">^</span><span class="fl">2</span>,</span>
<span>         year_cube <span class="op">=</span> <span class="va">year0</span><span class="op">^</span><span class="fl">3</span>,</span>
<span>         pub_cap_1000 <span class="op">=</span> <span class="va">public</span><span class="op">/</span><span class="fl">1000</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">prod.clean</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 816
Columns: 16
$ state        &lt;dbl&gt; 19, 44, 5, 41, 45, 16, 37, 20, 25, 11, 14, 40, 23, 42, 4,…
$ region       &lt;dbl&gt; 1, 5, 8, 7, 9, 7, 1, 3, 4, 3, 4, 6, 4, 8, 9, 8, 3, 8, 3, …
$ year         &lt;dbl&gt; 1970, 1970, 1970, 1970, 1970, 1970, 1970, 1970, 1970, 197…
$ public       &lt;dbl&gt; 21923.28, 20732.56, 11402.52, 53639.88, 25751.49, 19638.3…
$ hwy          &lt;dbl&gt; 9.052737, 9.329386, 8.390089, 10.163615, 9.066138, 9.1994…
$ water        &lt;dbl&gt; 7.714320, 7.892493, 7.680190, 9.030341, 8.142238, 7.88639…
$ other        &lt;dbl&gt; 9.318403, 8.823389, 8.483487, 9.870202, 9.522063, 8.86589…
$ private      &lt;dbl&gt; 10.543170, 10.454692, 10.073642, 12.272218, 10.529598, 11…
$ gsp          &lt;dbl&gt; 11.073319, 10.784545, 10.153818, 11.988675, 10.577044, 11…
$ emp          &lt;dbl&gt; 7.715793, 7.325742, 6.620340, 8.195582, 6.984160, 6.94080…
$ unemp        &lt;dbl&gt; 4.6, 3.4, 4.4, 4.4, 9.1, 6.6, 5.2, 6.7, 3.1, 4.1, 4.8, 4.…
$ region.fac   &lt;fct&gt; 1, 5, 8, 7, 9, 7, 1, 3, 4, 3, 4, 6, 4, 8, 9, 8, 3, 8, 3, …
$ year0        &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ year_sq      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ year_cube    &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ pub_cap_1000 &lt;dbl&gt; 21.92328, 20.73256, 11.40252, 53.63988, 25.75149, 19.6383…</code></pre>
</div>
</div>
<p>Two of these deserve a note.</p>
<p>Subtracting 1970 from <code>year</code> puts the intercept at the start of the observation window rather than at year zero of the common era, which is both meaningless and thousands of units away from any data we have. Polynomial terms built from the recentered variable are also far less collinear with each other than they would be otherwise.</p>
<p>Dividing public capital by 1,000 is rescaling, and it changes nothing about the model’s fit. What it changes is readability: a coefficient expressed per thousand dollars is easier to report than one carrying several leading zeros. Rescaling a predictor is always safe. Rescaling only <em>some</em> predictors and forgetting which is where people get into trouble, so a name like <code>pub_cap_1000</code> that records the units is worth the extra characters.</p>
</section><section id="part-2-find-your-final-or-preferred-model" class="level2" data-number="12.4"><h2 data-number="12.4" class="anchored" data-anchor-id="part-2-find-your-final-or-preferred-model">
<span class="header-section-number">12.4</span> Part 2: find your “final” or preferred model</h2>
<section id="start-with-a-null-growth-model-since-this-is-longitudinal-data" class="level3" data-number="12.4.1"><h3 data-number="12.4.1" class="anchored" data-anchor-id="start-with-a-null-growth-model-since-this-is-longitudinal-data">
<span class="header-section-number">12.4.1</span> Start with a null growth model since this is longitudinal data</h3>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model.null.growth</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">unemp</span> <span class="op">~</span> <span class="va">year0</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span><span class="op">|</span><span class="va">state</span><span class="op">)</span>, REML <span class="op">=</span> <span class="cn">FALSE</span>, data <span class="op">=</span> <span class="va">prod.clean</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">model.null.growth</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by maximum likelihood  ['lmerMod']
Formula: unemp ~ year0 + (1 | state)
   Data: prod.clean

      AIC       BIC    logLik -2*log(L)  df.resid 
   3268.6    3287.4   -1630.3    3260.6       812 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.6688 -0.6260 -0.1167  0.4891  4.8594 

Random effects:
 Groups   Name        Variance Std.Dev.
 state    (Intercept) 1.428    1.195   
 Residual             2.785    1.669   
Number of obs: 816, groups:  state, 48

Fixed effects:
            Estimate Std. Error t value
(Intercept)  5.17075    0.20557   25.15
year0        0.17893    0.01193   15.01

Correlation of Fixed Effects:
      (Intr)
year0 -0.464</code></pre>
</div>
</div>
<p>The outcome is state unemployment rate, and the clustering variable is state. This is the same structure as the growth models from Module 8, with states in place of children and years in place of grades.</p>
</section><section id="add-in-quadratic-effects" class="level3" data-number="12.4.2"><h3 data-number="12.4.2" class="anchored" data-anchor-id="add-in-quadratic-effects">
<span class="header-section-number">12.4.2</span> Add in quadratic effects</h3>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model.2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">unemp</span> <span class="op">~</span> <span class="va">year0</span> <span class="op">+</span> <span class="va">year_sq</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span><span class="op">|</span><span class="va">state</span><span class="op">)</span>, REML <span class="op">=</span> <span class="cn">FALSE</span>, data <span class="op">=</span> <span class="va">prod.clean</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">model.2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by maximum likelihood  ['lmerMod']
Formula: unemp ~ year0 + year_sq + (1 | state)
   Data: prod.clean

      AIC       BIC    logLik -2*log(L)  df.resid 
   3257.7    3281.2   -1623.8    3247.7       811 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.4550 -0.6449 -0.1213  0.4901  4.9036 

Random effects:
 Groups   Name        Variance Std.Dev.
 state    (Intercept) 1.431    1.196   
 Residual             2.738    1.655   
Number of obs: 816, groups:  state, 48

Fixed effects:
             Estimate Std. Error t value
(Intercept)  4.778638   0.232126  20.586
year0        0.335777   0.044987   7.464
year_sq     -0.009803   0.002713  -3.614

Correlation of Fixed Effects:
        (Intr) year0 
year0   -0.558       
year_sq  0.467 -0.965</code></pre>
</div>
</div>
</section><section id="add-in-cubic-effects" class="level3" data-number="12.4.3"><h3 data-number="12.4.3" class="anchored" data-anchor-id="add-in-cubic-effects">
<span class="header-section-number">12.4.3</span> Add in cubic effects</h3>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model.3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">unemp</span> <span class="op">~</span> <span class="va">year0</span> <span class="op">+</span> <span class="va">year_cube</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span><span class="op">|</span><span class="va">state</span><span class="op">)</span>, REML <span class="op">=</span> <span class="cn">FALSE</span>, data <span class="op">=</span> <span class="va">prod.clean</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Some predictor variables are on very different scales: consider rescaling. 
You may also use (g)lmerControl(autoscale = TRUE) to improve numerical stability.</code></pre>
</div>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">model.3</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by maximum likelihood  ['lmerMod']
Formula: unemp ~ year0 + year_cube + (1 | state)
   Data: prod.clean

      AIC       BIC    logLik -2*log(L)  df.resid 
   3252.2    3275.7   -1621.1    3242.2       811 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.3740 -0.6587 -0.1254  0.4910  4.8949 

Random effects:
 Groups   Name        Variance Std.Dev.
 state    (Intercept) 1.432    1.197   
 Residual             2.719    1.649   
Number of obs: 816, groups:  state, 48

Fixed effects:
              Estimate Std. Error t value
(Intercept)  4.7913162  0.2230693   21.48
year0        0.2915168  0.0286038   10.19
year_cube   -0.0004791  0.0001109   -4.32

Correlation of Fixed Effects:
          (Intr) year0 
year0     -0.533       
year_cube  0.394 -0.911
fit warnings:
Some predictor variables are on very different scales: consider rescaling. 
You may also use (g)lmerControl(autoscale = TRUE) to improve numerical stability.</code></pre>
</div>
</div>
</section><section id="both-quadratic-and-cubic-effects" class="level3" data-number="12.4.4"><h3 data-number="12.4.4" class="anchored" data-anchor-id="both-quadratic-and-cubic-effects">
<span class="header-section-number">12.4.4</span> Both quadratic and cubic effects</h3>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model.4</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">unemp</span> <span class="op">~</span> <span class="va">year0</span> <span class="op">+</span> <span class="va">year_sq</span> <span class="op">+</span> <span class="va">year_cube</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span><span class="op">|</span><span class="va">state</span><span class="op">)</span>, REML <span class="op">=</span> <span class="cn">FALSE</span>, data <span class="op">=</span> <span class="va">prod.clean</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Some predictor variables are on very different scales: consider rescaling. 
You may also use (g)lmerControl(autoscale = TRUE) to improve numerical stability.</code></pre>
</div>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">model.4</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by maximum likelihood  ['lmerMod']
Formula: unemp ~ year0 + year_sq + year_cube + (1 | state)
   Data: prod.clean

      AIC       BIC    logLik -2*log(L)  df.resid 
   3241.1    3269.3   -1614.5    3229.1       810 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.2040 -0.6472 -0.1329  0.4740  4.8086 

Random effects:
 Groups   Name        Variance Std.Dev.
 state    (Intercept) 1.434    1.198   
 Residual             2.673    1.635   
Number of obs: 816, groups:  state, 48

Fixed effects:
              Estimate Std. Error t value
(Intercept)  5.2388480  0.2542656  20.604
year0       -0.0723854  0.1040941  -0.695
year_sq      0.0559415  0.0153967   3.633
year_cube   -0.0027393  0.0006317  -4.336

Correlation of Fixed Effects:
          (Intr) year0  yer_sq
year0     -0.592              
year_sq    0.484 -0.962       
year_cube -0.417  0.904 -0.985
fit warnings:
Some predictor variables are on very different scales: consider rescaling. 
You may also use (g)lmerControl(autoscale = TRUE) to improve numerical stability.</code></pre>
</div>
</div>
<p>Unemployment over the 1970s and 1980s went through recessions and recoveries, so a straight line is unlikely to describe it well. The polynomial terms give the trajectory room to bend more than once.</p>
</section><section id="now-for-some-more-predictors" class="level3" data-number="12.4.5"><h3 data-number="12.4.5" class="anchored" data-anchor-id="now-for-some-more-predictors">
<span class="header-section-number">12.4.5</span> Now for some more predictors</h3>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model.5</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">unemp</span> <span class="op">~</span> <span class="va">year0</span> <span class="op">+</span> <span class="va">year_sq</span> <span class="op">+</span> <span class="va">year_cube</span> <span class="op">+</span> <span class="va">gsp</span> <span class="op">+</span> <span class="va">private</span> <span class="op">+</span> <span class="va">pub_cap_1000</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span><span class="op">|</span><span class="va">state</span><span class="op">)</span>, REML <span class="op">=</span> <span class="cn">FALSE</span>, data <span class="op">=</span> <span class="va">prod.clean</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Some predictor variables are on very different scales: consider rescaling. 
You may also use (g)lmerControl(autoscale = TRUE) to improve numerical stability.</code></pre>
</div>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">model.5</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by maximum likelihood  ['lmerMod']
Formula: unemp ~ year0 + year_sq + year_cube + gsp + private + pub_cap_1000 +  
    (1 | state)
   Data: prod.clean

      AIC       BIC    logLik -2*log(L)  df.resid 
   3108.9    3151.3   -1545.5    3090.9       807 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.5959 -0.6424 -0.1207  0.5125  4.7506 

Random effects:
 Groups   Name        Variance Std.Dev.
 state    (Intercept) 9.703    3.115   
 Residual             1.993    1.412   
Number of obs: 816, groups:  state, 48

Fixed effects:
               Estimate Std. Error t value
(Intercept)   2.704e+01  5.335e+00   5.068
year0        -6.084e-03  9.176e-02  -0.066
year_sq       3.750e-02  1.338e-02   2.803
year_cube    -1.787e-03  5.502e-04  -3.247
gsp          -1.073e+01  7.365e-01 -14.574
private       8.409e+00  8.502e-01   9.891
pub_cap_1000  9.064e-02  1.686e-02   5.376

Correlation of Fixed Effects:
            (Intr) year0  yer_sq yer_cb gsp    privat
year0        0.134                                   
year_sq      0.019 -0.944                            
year_cube   -0.029  0.882 -0.984                     
gsp         -0.127 -0.043  0.103 -0.126              
private     -0.518 -0.058 -0.089  0.116 -0.780       
pub_cp_1000  0.550 -0.012  0.026 -0.011 -0.167 -0.232
fit warnings:
Some predictor variables are on very different scales: consider rescaling. 
You may also use (g)lmerControl(autoscale = TRUE) to improve numerical stability.</code></pre>
</div>
</div>
<p>This is our “final” model, and everything that follows examines it rather than building further.</p>
</section></section><section id="use-the-augment-function-from-the-broom.mixed-package" class="level2" data-number="12.5"><h2 data-number="12.5" class="anchored" data-anchor-id="use-the-augment-function-from-the-broom.mixed-package">
<span class="header-section-number">12.5</span> Use the <code>augment</code> function from the <code>broom.mixed</code> package</h2>
<p>This gets predictions, residuals, Cook’s distances, and more.</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/bbolker/broom.mixed">broom.mixed</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">diagnostics</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span><span class="op">(</span><span class="va">model.5</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code><a href="https://generics.r-lib.org/reference/augment.html">augment()</a></code> returns the original data plus a set of new columns whose names begin with a dot: <code>.fitted</code>, <code>.resid</code>, <code>.cooksd</code>, and others. Everything in this chapter works from that data frame.</p>
<p>One thing worth knowing: <code>diagnostics</code> contains one row per observation <em>the model actually used</em>. If any rows were dropped for missing data, this frame is smaller than <code>prod.clean</code>. That is a feature, since it means residuals and fitted values always line up, but it does mean you should use <code>diagnostics</code> rather than the original data for anything downstream.</p>
</section><section id="step-1-assess-normality-of-residuals" class="level2" data-number="12.6"><h2 data-number="12.6" class="anchored" data-anchor-id="step-1-assess-normality-of-residuals">
<span class="header-section-number">12.6</span> Step 1: assess normality of residuals</h2>
<section id="visually-with-a-histogram" class="level3" data-number="12.6.1"><h3 data-number="12.6.1" class="anchored" data-anchor-id="visually-with-a-histogram">
<span class="header-section-number">12.6.1</span> Visually, with a histogram</h3>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">diagnostics</span>, mapping <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">.resid</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span>binwidth <span class="op">=</span> <span class="fl">.25</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Histogram of Residuals for State Unemployment Model"</span>,</span>
<span>                      x <span class="op">=</span> <span class="st">"Residual Value"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_vline</a></span><span class="op">(</span>xintercept <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">2.5</span>, <span class="fl">2.5</span><span class="op">)</span>, linetype <span class="op">=</span> <span class="st">"dotted"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-resid-hist" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="10-assumptions_files/figure-html/fig-resid-hist-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;12.1: Histogram of residuals with reference lines at ±2.5.</figcaption></figure>
</div>
</div>
</div>
<p>The dotted reference lines mark ±2.5, a rough boundary beyond which residuals are worth a closer look. What you are checking for is severe skew, heavy tails, or obvious multimodality, not perfect symmetry.</p>
</section><section id="statistically-with-the-shapiro-wilk-test" class="level3" data-number="12.6.2"><h3 data-number="12.6.2" class="anchored" data-anchor-id="statistically-with-the-shapiro-wilk-test">
<span class="header-section-number">12.6.2</span> Statistically, with the Shapiro-Wilk test</h3>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/shapiro.test.html">shapiro.test</a></span><span class="op">(</span><span class="va">diagnostics</span><span class="op">$</span><span class="va">.resid</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  diagnostics$.resid
W = 0.97666, p-value = 3.899e-10</code></pre>
</div>
</div>
<p>Expect this to be significant, and do not make much of it. Shapiro-Wilk detects arbitrarily small departures from normality once the sample is reasonably large, and with several hundred observations it will reject for essentially any real dataset.</p>
<p>The histogram carries more information than the test. It is also worth remembering what this assumption buys: normality of residuals matters mainly for small-sample inference, and at these sample sizes the central limit theorem does most of the work regardless.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
A size limit on this test
</div>
</div>
<div class="callout-body-container callout-body">
<p><code><a href="https://rdrr.io/r/stats/shapiro.test.html">shapiro.test()</a></code> accepts between 3 and 5,000 observations and errors outside that range. If you apply it to a larger model, sample first:</p>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">664</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/shapiro.test.html">shapiro.test</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="va">diagnostics</span><span class="op">$</span><span class="va">.resid</span>, <span class="fl">5000</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section></section><section id="step-2-use-a-residuals-vs.-fitted-rvf-plot-to-assess-homoskedasticity-of-errors" class="level2" data-number="12.7"><h2 data-number="12.7" class="anchored" data-anchor-id="step-2-use-a-residuals-vs.-fitted-rvf-plot-to-assess-homoskedasticity-of-errors">
<span class="header-section-number">12.7</span> Step 2: use a residuals vs.&nbsp;fitted (RVF) plot to assess homoskedasticity of errors</h2>
<section id="basic-rvf-plot-without-groups" class="level3" data-number="12.7.1"><h3 data-number="12.7.1" class="anchored" data-anchor-id="basic-rvf-plot-without-groups">
<span class="header-section-number">12.7.1</span> Basic RVF plot, without groups</h3>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">diagnostics</span>, mapping <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">.fitted</span>, y <span class="op">=</span> <span class="va">.resid</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"RVF Plot for State Unemployment Model"</span>,</span>
<span>                      x <span class="op">=</span> <span class="st">"Predicted Value, % Unemployment"</span>,</span>
<span>                      y <span class="op">=</span> <span class="st">"Residual Value"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-rvf" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="10-assumptions_files/figure-html/fig-rvf-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;12.2: Residuals versus fitted values.</figcaption></figure>
</div>
</div>
</div>
<p>Read this plot for shape rather than for scatter. A fan or funnel means the residual variance depends on the fitted value, which is heteroskedasticity. A curve means the relationship is not linear in the predictors as specified. An even, shapeless cloud is what you want.</p>
<p>Be specific in your write-up about <em>where</em> in the fitted range any problem appears. A violation confined to a sparse tail is a different matter from one across the whole range.</p>
</section><section id="same-thing-but-with-added-color-by-year0" class="level3" data-number="12.7.2"><h3 data-number="12.7.2" class="anchored" data-anchor-id="same-thing-but-with-added-color-by-year0">
<span class="header-section-number">12.7.2</span> Same thing, but with added color by year0</h3>
<div class="cell">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">diagnostics</span>, mapping <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">.fitted</span>, y <span class="op">=</span> <span class="va">.resid</span>, color <span class="op">=</span> <span class="va">year0</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"RVF Plot for State Unemployment Model, by Year"</span>,</span>
<span>                      x <span class="op">=</span> <span class="st">"Predicted Value, % Unemployment"</span>,</span>
<span>                      y <span class="op">=</span> <span class="st">"Residual Value"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-rvf-year" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="10-assumptions_files/figure-html/fig-rvf-year-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;12.3: The same plot, colored by year.</figcaption></figure>
</div>
</div>
</div>
<p>Adding color turns a general diagnostic into a specific one. If residuals cluster by year, with all the dark points high and the light ones low, the model is systematically missing something about time. That is far more actionable than knowing the residuals are merely uneven, and it is the kind of pattern longitudinal data produces routinely.</p>
</section></section><section id="step-3-use-cooks-distance-to-identify-outliers" class="level2" data-number="12.8"><h2 data-number="12.8" class="anchored" data-anchor-id="step-3-use-cooks-distance-to-identify-outliers">
<span class="header-section-number">12.8</span> Step 3: use Cook’s distance to identify outliers</h2>
<div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">diagnostics</span>, mapping <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">.fitted</span>, y <span class="op">=</span> <span class="va">.cooksd</span>, label <span class="op">=</span> <span class="va">state</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_text.html">geom_text</a></span><span class="op">(</span>nudge_x <span class="op">=</span> <span class="fl">.25</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Cook's Distance Plot for State Unemployment Model"</span>,</span>
<span>                      x <span class="op">=</span> <span class="st">"Predicted Value, % Unemployment"</span>,</span>
<span>                      y <span class="op">=</span> <span class="st">"Cook's Distance"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">4</span><span class="op">/</span><span class="fl">816</span>, linetype <span class="op">=</span> <span class="st">"dotted"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-cooks" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="10-assumptions_files/figure-html/fig-cooks-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;12.4: Cook’s distance by fitted value, labelled by state.</figcaption></figure>
</div>
</div>
</div>
<p>Labelling the points is what makes this plot useful rather than decorative. An unlabelled outlier is a puzzle; a labelled one is a case you can go look at.</p>
<p>The reference line at 4/816 is the conventional 4/n cutoff, where 816 is the number of observations. It is a flag, not a verdict.</p>
<p>When a case is flagged, look at it before doing anything. An observation with an impossible value is a data error and should be fixed or removed. An observation that is simply unusual, a state with a genuinely severe recession, is data. Deleting inconvenient observations because a statistic flagged them is not a diagnostic procedure; it is a way of guaranteeing the result you already wanted.</p>
</section><section id="step-4-re-run-model-with-robust-standard-errors" class="level2" data-number="12.9"><h2 data-number="12.9" class="anchored" data-anchor-id="step-4-re-run-model-with-robust-standard-errors">
<span class="header-section-number">12.9</span> Step 4: re-run model with robust standard errors</h2>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/kollerma/robustlmm">robustlmm</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">model.robust</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/robustlmm/man/rlmer.html">rlmer</a></span><span class="op">(</span><span class="va">unemp</span> <span class="op">~</span> <span class="va">year0</span> <span class="op">+</span> <span class="va">year_sq</span> <span class="op">+</span> <span class="va">year_cube</span> <span class="op">+</span> <span class="va">gsp</span> <span class="op">+</span> <span class="va">private</span> <span class="op">+</span> <span class="va">pub_cap_1000</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span><span class="op">|</span><span class="va">state</span><span class="op">)</span>, REML <span class="op">=</span> <span class="cn">FALSE</span>, data <span class="op">=</span> <span class="va">prod.clean</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Some predictor variables are on very different scales: consider rescaling. 
You may also use (g)lmerControl(autoscale = TRUE) to improve numerical stability.</code></pre>
</div>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">model.robust</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Robust linear mixed model fit by DAStau 
Formula: unemp ~ year0 + year_sq + year_cube + gsp + private + pub_cap_1000 +      (1 | state) 
   Data: prod.clean 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.9180 -0.6434 -0.0609  0.5851  5.5981 

Random effects:
 Groups   Name        Variance Std.Dev.
 state    (Intercept) 7.072    2.659   
 Residual             1.729    1.315   
Number of obs: 816, groups: state, 48

Fixed effects:
               Estimate Std. Error t value
(Intercept)   2.606e+01  4.862e+00   5.359
year0         4.230e-03  8.744e-02   0.048
year_sq       3.277e-02  1.278e-02   2.565
year_cube    -1.512e-03  5.255e-04  -2.877
gsp          -1.011e+01  6.922e-01 -14.607
private       7.908e+00  7.923e-01   9.982
pub_cap_1000  8.644e-02  1.554e-02   5.562
  note: Satterthwaite df skipped: problem size 32,640 exceeds the 5,000 auto cutoff; showing t-values without p-values. Request it with summary(object, df = "satterthwaite"), or raise options(robustlmm.summary.df.max). 

Correlation of Fixed Effects:
            (Intr) year0  yer_sq yer_cb gsp    privat
year0        0.122                                   
year_sq      0.021 -0.946                            
year_cube   -0.029  0.884 -0.984                     
gsp         -0.125 -0.039  0.100 -0.124              
private     -0.506 -0.053 -0.089  0.115 -0.790       
pub_cp_1000  0.574 -0.007  0.022 -0.008 -0.184 -0.222

Robustness weights for the residuals: 
 650 weights are ~= 1. The remaining 166 ones are summarized as
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  0.240   0.638   0.819   0.768   0.934   0.999 

Robustness weights for the random effects: 
 37 weights are ~= 1. The remaining 11 ones are summarized as
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  0.451   0.581   0.755   0.725   0.841   0.984 

Rho functions used for fitting:
  Residuals:
    eff: smoothed Huber (k = 1.345, s = 10) 
    sig: smoothed Huber, Proposal 2 (k = 1.345, s = 10) 
  Random Effects, variance component 1 (state):
    eff: smoothed Huber (k = 1.345, s = 10) 
    vcp: smoothed Huber, Proposal 2 (k = 1.345, s = 10) </code></pre>
</div>
</div>
<p><code><a href="https://rdrr.io/pkg/robustlmm/man/rlmer.html">rlmer()</a></code> from <code>robustlmm</code> fits the same model but downweights observations with large residuals rather than letting them exert full influence. If the estimates barely move relative to <code>model.5</code>, outliers were not driving your results.</p>
<p>This model can take a while to fit, since it works iteratively.</p>
</section><section id="step-5-re-run-model-with-outliers-removed-cooks-distance-.10" class="level2" data-number="12.10"><h2 data-number="12.10" class="anchored" data-anchor-id="step-5-re-run-model-with-outliers-removed-cooks-distance-.10">
<span class="header-section-number">12.10</span> Step 5: re-run model with outliers removed (Cook’s distance &gt; .10)</h2>
<div class="cell">
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">prod.trimmed</span> <span class="op">&lt;-</span> <span class="va">diagnostics</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">.</span>, <span class="va">.cooksd</span> <span class="op">&lt;</span> <span class="fl">.10</span><span class="op">)</span></span>
<span></span>
<span><span class="va">model.trimmed</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/lme4/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">unemp</span> <span class="op">~</span> <span class="va">year0</span> <span class="op">+</span> <span class="va">year_sq</span> <span class="op">+</span> <span class="va">year_cube</span> <span class="op">+</span> <span class="va">gsp</span> <span class="op">+</span> <span class="va">private</span> <span class="op">+</span> <span class="va">pub_cap_1000</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span><span class="op">|</span><span class="va">state</span><span class="op">)</span>, REML <span class="op">=</span> <span class="cn">FALSE</span>, data <span class="op">=</span> <span class="va">prod.trimmed</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Some predictor variables are on very different scales: consider rescaling. 
You may also use (g)lmerControl(autoscale = TRUE) to improve numerical stability.</code></pre>
</div>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">model.trimmed</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by maximum likelihood  ['lmerMod']
Formula: unemp ~ year0 + year_sq + year_cube + gsp + private + pub_cap_1000 +  
    (1 | state)
   Data: prod.trimmed

      AIC       BIC    logLik -2*log(L)  df.resid 
   3034.4    3076.7   -1508.2    3016.4       803 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.6754 -0.6721 -0.1032  0.5324  3.4192 

Random effects:
 Groups   Name        Variance Std.Dev.
 state    (Intercept) 9.107    3.018   
 Residual             1.849    1.360   
Number of obs: 812, groups:  state, 48

Fixed effects:
               Estimate Std. Error t value
(Intercept)   2.678e+01  5.157e+00   5.194
year0        -1.779e-02  8.868e-02  -0.201
year_sq       3.859e-02  1.293e-02   2.984
year_cube    -1.819e-03  5.316e-04  -3.420
gsp          -1.041e+01  7.132e-01 -14.597
private       8.107e+00  8.230e-01   9.850
pub_cap_1000  9.258e-02  1.629e-02   5.685

Correlation of Fixed Effects:
            (Intr) year0  yer_sq yer_cb gsp    privat
year0        0.134                                   
year_sq      0.019 -0.944                            
year_cube   -0.029  0.882 -0.984                     
gsp         -0.127 -0.045  0.104 -0.127              
private     -0.517 -0.057 -0.091  0.117 -0.781       
pub_cp_1000  0.549 -0.013  0.027 -0.012 -0.165 -0.232
fit warnings:
Some predictor variables are on very different scales: consider rescaling. 
You may also use (g)lmerControl(autoscale = TRUE) to improve numerical stability.</code></pre>
</div>
</div>
<p>Note that the filtering happens on <code>diagnostics</code>, not on <code>prod.clean</code>. That works because <code><a href="https://generics.r-lib.org/reference/augment.html">augment()</a></code> kept all the original columns alongside the new diagnostic ones, so the trimmed frame still has everything the model formula needs.</p>
<div class="cell">
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">diagnostics</span><span class="op">)</span>; <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">prod.trimmed</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 816</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 812</code></pre>
</div>
</div>
<p>Reporting how many observations came out is not optional. A reader needs to know whether the robustness check dropped three cases or three hundred.</p>
</section><section id="step-6-compare-original-final-model-robust-model-and-trimmed-model" class="level2" data-number="12.11"><h2 data-number="12.11" class="anchored" data-anchor-id="step-6-compare-original-final-model-robust-model-and-trimmed-model">
<span class="header-section-number">12.11</span> Step 6: compare original “final” model, robust model, and trimmed model</h2>
<p>This is the sensitivity analysis.</p>
<div class="cell">
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://modelsummary.com">modelsummary</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">models</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="va">model.5</span>, <span class="va">model.trimmed</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://modelsummary.com/man/modelsummary.html">modelsummary</a></span><span class="op">(</span><span class="va">models</span>, output <span class="op">=</span> <span class="st">"markdown"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 31%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead><tr class="header">
<th></th>
<th><ol type="1">
<li>
</li></ol></th>
<th><ol start="2" type="1">
<li>
</li></ol></th>
</tr></thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>27.040</td>
<td>26.785</td>
</tr>
<tr class="even">
<td></td>
<td>(5.335)</td>
<td>(5.157)</td>
</tr>
<tr class="odd">
<td>year0</td>
<td>-0.006</td>
<td>-0.018</td>
</tr>
<tr class="even">
<td></td>
<td>(0.092)</td>
<td>(0.089)</td>
</tr>
<tr class="odd">
<td>year_sq</td>
<td>0.037</td>
<td>0.039</td>
</tr>
<tr class="even">
<td></td>
<td>(0.013)</td>
<td>(0.013)</td>
</tr>
<tr class="odd">
<td>year_cube</td>
<td>-0.002</td>
<td>-0.002</td>
</tr>
<tr class="even">
<td></td>
<td>(0.001)</td>
<td>(0.001)</td>
</tr>
<tr class="odd">
<td>gsp</td>
<td>-10.734</td>
<td>-10.411</td>
</tr>
<tr class="even">
<td></td>
<td>(0.737)</td>
<td>(0.713)</td>
</tr>
<tr class="odd">
<td>private</td>
<td>8.409</td>
<td>8.107</td>
</tr>
<tr class="even">
<td></td>
<td>(0.850)</td>
<td>(0.823)</td>
</tr>
<tr class="odd">
<td>pub_cap_1000</td>
<td>0.091</td>
<td>0.093</td>
</tr>
<tr class="even">
<td></td>
<td>(0.017)</td>
<td>(0.016)</td>
</tr>
<tr class="odd">
<td>SD (Intercept state)</td>
<td>3.115</td>
<td>3.018</td>
</tr>
<tr class="even">
<td>SD (Observations)</td>
<td>1.412</td>
<td>1.360</td>
</tr>
<tr class="odd">
<td>Num.Obs.</td>
<td>816</td>
<td>812</td>
</tr>
<tr class="even">
<td>R2 Marg.</td>
<td>0.433</td>
<td>0.434</td>
</tr>
<tr class="odd">
<td>R2 Cond.</td>
<td>0.903</td>
<td>0.904</td>
</tr>
<tr class="even">
<td>AIC</td>
<td>3144.5</td>
<td>3070.4</td>
</tr>
<tr class="odd">
<td>BIC</td>
<td>3186.8</td>
<td>3112.7</td>
</tr>
<tr class="even">
<td>ICC</td>
<td>0.8</td>
<td>0.8</td>
</tr>
<tr class="odd">
<td>RMSE</td>
<td>1.37</td>
<td>1.32</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>This is the part that actually settles the question. Rather than arguing about whether assumptions hold, refit under different assumptions and compare.</p>
<p>Read across the columns for the coefficient you care about most. If it holds steady in magnitude, direction, and significance, you have an answer to the reviewer worried about your residuals: the conclusion does not depend on the assumption in question. That is a much stronger response than asserting the assumption was met.</p>
</section><section id="writing-it-up" class="level2" data-number="12.12"><h2 data-number="12.12" class="anchored" data-anchor-id="writing-it-up">
<span class="header-section-number">12.12</span> Writing it up</h2>
<p>A sensitivity analysis paragraph belongs in nearly every quantitative paper, and it has a predictable shape. State which diagnostics you examined. Report what they showed, honestly, including the parts that looked imperfect. Describe the robustness checks you ran. Then state whether your substantive conclusion held.</p>
<p>The version that reads as defensive says the assumptions were met and moves on. The version that reads as competent concedes that residuals showed mild skew and a handful of state-years exceeded the conventional Cook’s distance threshold, then reports that the coefficients changed negligibly under robust estimation and with those cases excluded. The second is more honest and considerably more persuasive.</p>


<!-- -->

</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./09-binary-outcomes.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Binary and Generalized Linear Mixed Models</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./11-cross-classified.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Cross-Classified Linear Mixed Models</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb44" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Checking Assumptions for MLMs</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>**Data for this chapter:** <span class="in">`productivity.dta`</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data file needed</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>Copy <span class="in">`productivity.dta`</span> into this project folder before rendering.</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>This week, we will use the <span class="in">`productivity`</span> dataset from Stata, developed by Dr. Alicia Munnell and published by the Federal Reserve Bank of Boston (1990). It tracks US states over time, so observations are years nested within states.</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>Diagnostics are not a pass-fail checklist. They are evidence you weigh, and the useful question is never "was an assumption violated" but "is this violation bad enough to change what I conclude." This chapter runs the standard checks and then does the thing that actually settles the question: refits the model under different assumptions and sees whether the answer moves.</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a><span class="fu">## Load in our MVP packages</span></span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb44-21"><a href="#cb44-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-22"><a href="#cb44-22" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(tidyverse))</span>
<span id="cb44-23"><a href="#cb44-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb44-24"><a href="#cb44-24" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hmisc)</span>
<span id="cb44-25"><a href="#cb44-25" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-26"><a href="#cb44-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-27"><a href="#cb44-27" aria-hidden="true" tabindex="-1"></a><span class="fu">## Part 1: loading in the data, and then recoding variables</span></span>
<span id="cb44-28"><a href="#cb44-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-29"><a href="#cb44-29" aria-hidden="true" tabindex="-1"></a><span class="fu">### Load in the data</span></span>
<span id="cb44-30"><a href="#cb44-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-33"><a href="#cb44-33" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-34"><a href="#cb44-34" aria-hidden="true" tabindex="-1"></a>productivity <span class="ot">&lt;-</span> haven<span class="sc">::</span><span class="fu">read_dta</span>(<span class="st">"productivity.dta"</span>)</span>
<span id="cb44-35"><a href="#cb44-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-36"><a href="#cb44-36" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(productivity)</span>
<span id="cb44-37"><a href="#cb44-37" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-38"><a href="#cb44-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-39"><a href="#cb44-39" aria-hidden="true" tabindex="-1"></a><span class="fu">### The `describe` function from `Hmisc` is a nice codebook</span></span>
<span id="cb44-40"><a href="#cb44-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-43"><a href="#cb44-43" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-44"><a href="#cb44-44" aria-hidden="true" tabindex="-1"></a>Hmisc<span class="sc">::</span><span class="fu">describe</span>(productivity)</span>
<span id="cb44-45"><a href="#cb44-45" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-46"><a href="#cb44-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-47"><a href="#cb44-47" aria-hidden="true" tabindex="-1"></a><span class="fu">## A little quick cleaning</span></span>
<span id="cb44-48"><a href="#cb44-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-49"><a href="#cb44-49" aria-hidden="true" tabindex="-1"></a>Convert region to a factor variable, rescale public capital stock, "zero out" year, and create nonlinear terms.</span>
<span id="cb44-50"><a href="#cb44-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-53"><a href="#cb44-53" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-54"><a href="#cb44-54" aria-hidden="true" tabindex="-1"></a>prod.clean <span class="ot">&lt;-</span> productivity <span class="sc">%&gt;%</span></span>
<span id="cb44-55"><a href="#cb44-55" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(.,</span>
<span id="cb44-56"><a href="#cb44-56" aria-hidden="true" tabindex="-1"></a>         <span class="at">region.fac =</span> <span class="fu">as_factor</span>(region),</span>
<span id="cb44-57"><a href="#cb44-57" aria-hidden="true" tabindex="-1"></a>         <span class="at">year0 =</span> year <span class="sc">-</span> <span class="dv">1970</span>,</span>
<span id="cb44-58"><a href="#cb44-58" aria-hidden="true" tabindex="-1"></a>         <span class="at">year_sq =</span> year0<span class="sc">^</span><span class="dv">2</span>,</span>
<span id="cb44-59"><a href="#cb44-59" aria-hidden="true" tabindex="-1"></a>         <span class="at">year_cube =</span> year0<span class="sc">^</span><span class="dv">3</span>,</span>
<span id="cb44-60"><a href="#cb44-60" aria-hidden="true" tabindex="-1"></a>         <span class="at">pub_cap_1000 =</span> public<span class="sc">/</span><span class="dv">1000</span>)</span>
<span id="cb44-61"><a href="#cb44-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-62"><a href="#cb44-62" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(prod.clean)</span>
<span id="cb44-63"><a href="#cb44-63" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-64"><a href="#cb44-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-65"><a href="#cb44-65" aria-hidden="true" tabindex="-1"></a>Two of these deserve a note.</span>
<span id="cb44-66"><a href="#cb44-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-67"><a href="#cb44-67" aria-hidden="true" tabindex="-1"></a>Subtracting 1970 from <span class="in">`year`</span> puts the intercept at the start of the observation window rather than at year zero of the common era, which is both meaningless and thousands of units away from any data we have. Polynomial terms built from the recentered variable are also far less collinear with each other than they would be otherwise.</span>
<span id="cb44-68"><a href="#cb44-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-69"><a href="#cb44-69" aria-hidden="true" tabindex="-1"></a>Dividing public capital by 1,000 is rescaling, and it changes nothing about the model's fit. What it changes is readability: a coefficient expressed per thousand dollars is easier to report than one carrying several leading zeros. Rescaling a predictor is always safe. Rescaling only *some* predictors and forgetting which is where people get into trouble, so a name like <span class="in">`pub_cap_1000`</span> that records the units is worth the extra characters.</span>
<span id="cb44-70"><a href="#cb44-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-71"><a href="#cb44-71" aria-hidden="true" tabindex="-1"></a><span class="fu">## Part 2: find your "final" or preferred model</span></span>
<span id="cb44-72"><a href="#cb44-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-73"><a href="#cb44-73" aria-hidden="true" tabindex="-1"></a><span class="fu">### Start with a null growth model since this is longitudinal data</span></span>
<span id="cb44-74"><a href="#cb44-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-77"><a href="#cb44-77" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-78"><a href="#cb44-78" aria-hidden="true" tabindex="-1"></a>model.null.growth <span class="ot">&lt;-</span> <span class="fu">lmer</span>(unemp <span class="sc">~</span> year0 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>state), <span class="at">REML =</span> <span class="cn">FALSE</span>, <span class="at">data =</span> prod.clean)</span>
<span id="cb44-79"><a href="#cb44-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-80"><a href="#cb44-80" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.null.growth)</span>
<span id="cb44-81"><a href="#cb44-81" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-82"><a href="#cb44-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-83"><a href="#cb44-83" aria-hidden="true" tabindex="-1"></a>The outcome is state unemployment rate, and the clustering variable is state. This is the same structure as the growth models from Module 8, with states in place of children and years in place of grades.</span>
<span id="cb44-84"><a href="#cb44-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-85"><a href="#cb44-85" aria-hidden="true" tabindex="-1"></a><span class="fu">### Add in quadratic effects</span></span>
<span id="cb44-86"><a href="#cb44-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-89"><a href="#cb44-89" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-90"><a href="#cb44-90" aria-hidden="true" tabindex="-1"></a>model<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">lmer</span>(unemp <span class="sc">~</span> year0 <span class="sc">+</span> year_sq <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>state), <span class="at">REML =</span> <span class="cn">FALSE</span>, <span class="at">data =</span> prod.clean)</span>
<span id="cb44-91"><a href="#cb44-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-92"><a href="#cb44-92" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model<span class="fl">.2</span>)</span>
<span id="cb44-93"><a href="#cb44-93" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-94"><a href="#cb44-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-95"><a href="#cb44-95" aria-hidden="true" tabindex="-1"></a><span class="fu">### Add in cubic effects</span></span>
<span id="cb44-96"><a href="#cb44-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-99"><a href="#cb44-99" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-100"><a href="#cb44-100" aria-hidden="true" tabindex="-1"></a>model<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">lmer</span>(unemp <span class="sc">~</span> year0 <span class="sc">+</span> year_cube <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>state), <span class="at">REML =</span> <span class="cn">FALSE</span>, <span class="at">data =</span> prod.clean)</span>
<span id="cb44-101"><a href="#cb44-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-102"><a href="#cb44-102" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model<span class="fl">.3</span>)</span>
<span id="cb44-103"><a href="#cb44-103" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-104"><a href="#cb44-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-105"><a href="#cb44-105" aria-hidden="true" tabindex="-1"></a><span class="fu">### Both quadratic and cubic effects</span></span>
<span id="cb44-106"><a href="#cb44-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-109"><a href="#cb44-109" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-110"><a href="#cb44-110" aria-hidden="true" tabindex="-1"></a>model<span class="fl">.4</span> <span class="ot">&lt;-</span> <span class="fu">lmer</span>(unemp <span class="sc">~</span> year0 <span class="sc">+</span> year_sq <span class="sc">+</span> year_cube <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>state), <span class="at">REML =</span> <span class="cn">FALSE</span>, <span class="at">data =</span> prod.clean)</span>
<span id="cb44-111"><a href="#cb44-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-112"><a href="#cb44-112" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model<span class="fl">.4</span>)</span>
<span id="cb44-113"><a href="#cb44-113" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-114"><a href="#cb44-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-115"><a href="#cb44-115" aria-hidden="true" tabindex="-1"></a>Unemployment over the 1970s and 1980s went through recessions and recoveries, so a straight line is unlikely to describe it well. The polynomial terms give the trajectory room to bend more than once.</span>
<span id="cb44-116"><a href="#cb44-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-117"><a href="#cb44-117" aria-hidden="true" tabindex="-1"></a><span class="fu">### Now for some more predictors</span></span>
<span id="cb44-118"><a href="#cb44-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-121"><a href="#cb44-121" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-122"><a href="#cb44-122" aria-hidden="true" tabindex="-1"></a>model<span class="fl">.5</span> <span class="ot">&lt;-</span> <span class="fu">lmer</span>(unemp <span class="sc">~</span> year0 <span class="sc">+</span> year_sq <span class="sc">+</span> year_cube <span class="sc">+</span> gsp <span class="sc">+</span> private <span class="sc">+</span> pub_cap_1000 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>state), <span class="at">REML =</span> <span class="cn">FALSE</span>, <span class="at">data =</span> prod.clean)</span>
<span id="cb44-123"><a href="#cb44-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-124"><a href="#cb44-124" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model<span class="fl">.5</span>)</span>
<span id="cb44-125"><a href="#cb44-125" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-126"><a href="#cb44-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-127"><a href="#cb44-127" aria-hidden="true" tabindex="-1"></a>This is our "final" model, and everything that follows examines it rather than building further.</span>
<span id="cb44-128"><a href="#cb44-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-129"><a href="#cb44-129" aria-hidden="true" tabindex="-1"></a><span class="fu">## Use the `augment` function from the `broom.mixed` package</span></span>
<span id="cb44-130"><a href="#cb44-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-131"><a href="#cb44-131" aria-hidden="true" tabindex="-1"></a>This gets predictions, residuals, Cook's distances, and more.</span>
<span id="cb44-132"><a href="#cb44-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-135"><a href="#cb44-135" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-136"><a href="#cb44-136" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb44-137"><a href="#cb44-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-138"><a href="#cb44-138" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom.mixed)</span>
<span id="cb44-139"><a href="#cb44-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-140"><a href="#cb44-140" aria-hidden="true" tabindex="-1"></a>diagnostics <span class="ot">&lt;-</span> <span class="fu">augment</span>(model<span class="fl">.5</span>)</span>
<span id="cb44-141"><a href="#cb44-141" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-142"><a href="#cb44-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-143"><a href="#cb44-143" aria-hidden="true" tabindex="-1"></a><span class="in">`augment()`</span> returns the original data plus a set of new columns whose names begin with a dot: <span class="in">`.fitted`</span>, <span class="in">`.resid`</span>, <span class="in">`.cooksd`</span>, and others. Everything in this chapter works from that data frame.</span>
<span id="cb44-144"><a href="#cb44-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-145"><a href="#cb44-145" aria-hidden="true" tabindex="-1"></a>One thing worth knowing: <span class="in">`diagnostics`</span> contains one row per observation *the model actually used*. If any rows were dropped for missing data, this frame is smaller than <span class="in">`prod.clean`</span>. That is a feature, since it means residuals and fitted values always line up, but it does mean you should use <span class="in">`diagnostics`</span> rather than the original data for anything downstream.</span>
<span id="cb44-146"><a href="#cb44-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-147"><a href="#cb44-147" aria-hidden="true" tabindex="-1"></a><span class="fu">## Step 1: assess normality of residuals</span></span>
<span id="cb44-148"><a href="#cb44-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-149"><a href="#cb44-149" aria-hidden="true" tabindex="-1"></a><span class="fu">### Visually, with a histogram</span></span>
<span id="cb44-150"><a href="#cb44-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-153"><a href="#cb44-153" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-154"><a href="#cb44-154" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-resid-hist</span></span>
<span id="cb44-155"><a href="#cb44-155" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Histogram of residuals with reference lines at ±2.5."</span></span>
<span id="cb44-156"><a href="#cb44-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-157"><a href="#cb44-157" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> diagnostics, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> .resid)) <span class="sc">+</span></span>
<span id="cb44-158"><a href="#cb44-158" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> .<span class="dv">25</span>) <span class="sc">+</span> <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb44-159"><a href="#cb44-159" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histogram of Residuals for State Unemployment Model"</span>,</span>
<span id="cb44-160"><a href="#cb44-160" aria-hidden="true" tabindex="-1"></a>                      <span class="at">x =</span> <span class="st">"Residual Value"</span>) <span class="sc">+</span></span>
<span id="cb44-161"><a href="#cb44-161" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">2.5</span>, <span class="fl">2.5</span>), <span class="at">linetype =</span> <span class="st">"dotted"</span>)</span>
<span id="cb44-162"><a href="#cb44-162" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-163"><a href="#cb44-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-164"><a href="#cb44-164" aria-hidden="true" tabindex="-1"></a>The dotted reference lines mark ±2.5, a rough boundary beyond which residuals are worth a closer look. What you are checking for is severe skew, heavy tails, or obvious multimodality, not perfect symmetry.</span>
<span id="cb44-165"><a href="#cb44-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-166"><a href="#cb44-166" aria-hidden="true" tabindex="-1"></a><span class="fu">### Statistically, with the Shapiro-Wilk test</span></span>
<span id="cb44-167"><a href="#cb44-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-170"><a href="#cb44-170" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-171"><a href="#cb44-171" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(diagnostics<span class="sc">$</span>.resid)</span>
<span id="cb44-172"><a href="#cb44-172" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-173"><a href="#cb44-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-174"><a href="#cb44-174" aria-hidden="true" tabindex="-1"></a>Expect this to be significant, and do not make much of it. Shapiro-Wilk detects arbitrarily small departures from normality once the sample is reasonably large, and with several hundred observations it will reject for essentially any real dataset.</span>
<span id="cb44-175"><a href="#cb44-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-176"><a href="#cb44-176" aria-hidden="true" tabindex="-1"></a>The histogram carries more information than the test. It is also worth remembering what this assumption buys: normality of residuals matters mainly for small-sample inference, and at these sample sizes the central limit theorem does most of the work regardless.</span>
<span id="cb44-177"><a href="#cb44-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-178"><a href="#cb44-178" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb44-179"><a href="#cb44-179" aria-hidden="true" tabindex="-1"></a><span class="fu">## A size limit on this test</span></span>
<span id="cb44-180"><a href="#cb44-180" aria-hidden="true" tabindex="-1"></a><span class="in">`shapiro.test()`</span> accepts between 3 and 5,000 observations and errors outside that range. If you apply it to a larger model, sample first:</span>
<span id="cb44-181"><a href="#cb44-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-182"><a href="#cb44-182" aria-hidden="true" tabindex="-1"></a><span class="in">```r</span></span>
<span id="cb44-183"><a href="#cb44-183" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">664</span>)</span>
<span id="cb44-184"><a href="#cb44-184" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">sample</span>(diagnostics<span class="sc">$</span>.resid, <span class="dv">5000</span>))</span>
<span id="cb44-185"><a href="#cb44-185" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-186"><a href="#cb44-186" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb44-187"><a href="#cb44-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-188"><a href="#cb44-188" aria-hidden="true" tabindex="-1"></a><span class="fu">## Step 2: use a residuals vs. fitted (RVF) plot to assess homoskedasticity of errors</span></span>
<span id="cb44-189"><a href="#cb44-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-190"><a href="#cb44-190" aria-hidden="true" tabindex="-1"></a><span class="fu">### Basic RVF plot, without groups</span></span>
<span id="cb44-191"><a href="#cb44-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-194"><a href="#cb44-194" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-195"><a href="#cb44-195" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-rvf</span></span>
<span id="cb44-196"><a href="#cb44-196" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Residuals versus fitted values."</span></span>
<span id="cb44-197"><a href="#cb44-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-198"><a href="#cb44-198" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> diagnostics, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid)) <span class="sc">+</span></span>
<span id="cb44-199"><a href="#cb44-199" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"RVF Plot for State Unemployment Model"</span>,</span>
<span id="cb44-200"><a href="#cb44-200" aria-hidden="true" tabindex="-1"></a>                      <span class="at">x =</span> <span class="st">"Predicted Value, % Unemployment"</span>,</span>
<span id="cb44-201"><a href="#cb44-201" aria-hidden="true" tabindex="-1"></a>                      <span class="at">y =</span> <span class="st">"Residual Value"</span>) <span class="sc">+</span> <span class="fu">theme_classic</span>()</span>
<span id="cb44-202"><a href="#cb44-202" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-203"><a href="#cb44-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-204"><a href="#cb44-204" aria-hidden="true" tabindex="-1"></a>Read this plot for shape rather than for scatter. A fan or funnel means the residual variance depends on the fitted value, which is heteroskedasticity. A curve means the relationship is not linear in the predictors as specified. An even, shapeless cloud is what you want.</span>
<span id="cb44-205"><a href="#cb44-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-206"><a href="#cb44-206" aria-hidden="true" tabindex="-1"></a>Be specific in your write-up about *where* in the fitted range any problem appears. A violation confined to a sparse tail is a different matter from one across the whole range.</span>
<span id="cb44-207"><a href="#cb44-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-208"><a href="#cb44-208" aria-hidden="true" tabindex="-1"></a><span class="fu">### Same thing, but with added color by year0</span></span>
<span id="cb44-209"><a href="#cb44-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-212"><a href="#cb44-212" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-213"><a href="#cb44-213" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-rvf-year</span></span>
<span id="cb44-214"><a href="#cb44-214" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "The same plot, colored by year."</span></span>
<span id="cb44-215"><a href="#cb44-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-216"><a href="#cb44-216" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> diagnostics, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid, <span class="at">color =</span> year0)) <span class="sc">+</span></span>
<span id="cb44-217"><a href="#cb44-217" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"RVF Plot for State Unemployment Model, by Year"</span>,</span>
<span id="cb44-218"><a href="#cb44-218" aria-hidden="true" tabindex="-1"></a>                      <span class="at">x =</span> <span class="st">"Predicted Value, % Unemployment"</span>,</span>
<span id="cb44-219"><a href="#cb44-219" aria-hidden="true" tabindex="-1"></a>                      <span class="at">y =</span> <span class="st">"Residual Value"</span>) <span class="sc">+</span> <span class="fu">theme_classic</span>()</span>
<span id="cb44-220"><a href="#cb44-220" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-221"><a href="#cb44-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-222"><a href="#cb44-222" aria-hidden="true" tabindex="-1"></a>Adding color turns a general diagnostic into a specific one. If residuals cluster by year, with all the dark points high and the light ones low, the model is systematically missing something about time. That is far more actionable than knowing the residuals are merely uneven, and it is the kind of pattern longitudinal data produces routinely.</span>
<span id="cb44-223"><a href="#cb44-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-224"><a href="#cb44-224" aria-hidden="true" tabindex="-1"></a><span class="fu">## Step 3: use Cook's distance to identify outliers</span></span>
<span id="cb44-225"><a href="#cb44-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-228"><a href="#cb44-228" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-229"><a href="#cb44-229" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-cooks</span></span>
<span id="cb44-230"><a href="#cb44-230" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Cook's distance by fitted value, labelled by state."</span></span>
<span id="cb44-231"><a href="#cb44-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-232"><a href="#cb44-232" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> diagnostics, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .cooksd, <span class="at">label =</span> state)) <span class="sc">+</span></span>
<span id="cb44-233"><a href="#cb44-233" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_text</span>(<span class="at">nudge_x =</span> .<span class="dv">25</span>) <span class="sc">+</span> <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb44-234"><a href="#cb44-234" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Cook's Distance Plot for State Unemployment Model"</span>,</span>
<span id="cb44-235"><a href="#cb44-235" aria-hidden="true" tabindex="-1"></a>                      <span class="at">x =</span> <span class="st">"Predicted Value, % Unemployment"</span>,</span>
<span id="cb44-236"><a href="#cb44-236" aria-hidden="true" tabindex="-1"></a>                      <span class="at">y =</span> <span class="st">"Cook's Distance"</span>) <span class="sc">+</span></span>
<span id="cb44-237"><a href="#cb44-237" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">4</span><span class="sc">/</span><span class="dv">816</span>, <span class="at">linetype =</span> <span class="st">"dotted"</span>)</span>
<span id="cb44-238"><a href="#cb44-238" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-239"><a href="#cb44-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-240"><a href="#cb44-240" aria-hidden="true" tabindex="-1"></a>Labelling the points is what makes this plot useful rather than decorative. An unlabelled outlier is a puzzle; a labelled one is a case you can go look at.</span>
<span id="cb44-241"><a href="#cb44-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-242"><a href="#cb44-242" aria-hidden="true" tabindex="-1"></a>The reference line at 4/816 is the conventional 4/n cutoff, where 816 is the number of observations. It is a flag, not a verdict.</span>
<span id="cb44-243"><a href="#cb44-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-244"><a href="#cb44-244" aria-hidden="true" tabindex="-1"></a>When a case is flagged, look at it before doing anything. An observation with an impossible value is a data error and should be fixed or removed. An observation that is simply unusual, a state with a genuinely severe recession, is data. Deleting inconvenient observations because a statistic flagged them is not a diagnostic procedure; it is a way of guaranteeing the result you already wanted.</span>
<span id="cb44-245"><a href="#cb44-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-246"><a href="#cb44-246" aria-hidden="true" tabindex="-1"></a><span class="fu">## Step 4: re-run model with robust standard errors</span></span>
<span id="cb44-247"><a href="#cb44-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-250"><a href="#cb44-250" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-251"><a href="#cb44-251" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb44-252"><a href="#cb44-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-253"><a href="#cb44-253" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(robustlmm)</span>
<span id="cb44-254"><a href="#cb44-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-255"><a href="#cb44-255" aria-hidden="true" tabindex="-1"></a>model.robust <span class="ot">&lt;-</span> <span class="fu">rlmer</span>(unemp <span class="sc">~</span> year0 <span class="sc">+</span> year_sq <span class="sc">+</span> year_cube <span class="sc">+</span> gsp <span class="sc">+</span> private <span class="sc">+</span> pub_cap_1000 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>state), <span class="at">REML =</span> <span class="cn">FALSE</span>, <span class="at">data =</span> prod.clean)</span>
<span id="cb44-256"><a href="#cb44-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-257"><a href="#cb44-257" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.robust)</span>
<span id="cb44-258"><a href="#cb44-258" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-259"><a href="#cb44-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-260"><a href="#cb44-260" aria-hidden="true" tabindex="-1"></a><span class="in">`rlmer()`</span> from <span class="in">`robustlmm`</span> fits the same model but downweights observations with large residuals rather than letting them exert full influence. If the estimates barely move relative to <span class="in">`model.5`</span>, outliers were not driving your results.</span>
<span id="cb44-261"><a href="#cb44-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-262"><a href="#cb44-262" aria-hidden="true" tabindex="-1"></a>This model can take a while to fit, since it works iteratively.</span>
<span id="cb44-263"><a href="#cb44-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-264"><a href="#cb44-264" aria-hidden="true" tabindex="-1"></a><span class="fu">## Step 5: re-run model with outliers removed (Cook's distance &gt; .10)</span></span>
<span id="cb44-265"><a href="#cb44-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-268"><a href="#cb44-268" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-269"><a href="#cb44-269" aria-hidden="true" tabindex="-1"></a>prod.trimmed <span class="ot">&lt;-</span> diagnostics <span class="sc">%&gt;%</span></span>
<span id="cb44-270"><a href="#cb44-270" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(., .cooksd <span class="sc">&lt;</span> .<span class="dv">10</span>)</span>
<span id="cb44-271"><a href="#cb44-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-272"><a href="#cb44-272" aria-hidden="true" tabindex="-1"></a>model.trimmed <span class="ot">&lt;-</span> <span class="fu">lmer</span>(unemp <span class="sc">~</span> year0 <span class="sc">+</span> year_sq <span class="sc">+</span> year_cube <span class="sc">+</span> gsp <span class="sc">+</span> private <span class="sc">+</span> pub_cap_1000 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>state), <span class="at">REML =</span> <span class="cn">FALSE</span>, <span class="at">data =</span> prod.trimmed)</span>
<span id="cb44-273"><a href="#cb44-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-274"><a href="#cb44-274" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.trimmed)</span>
<span id="cb44-275"><a href="#cb44-275" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-276"><a href="#cb44-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-277"><a href="#cb44-277" aria-hidden="true" tabindex="-1"></a>Note that the filtering happens on <span class="in">`diagnostics`</span>, not on <span class="in">`prod.clean`</span>. That works because <span class="in">`augment()`</span> kept all the original columns alongside the new diagnostic ones, so the trimmed frame still has everything the model formula needs.</span>
<span id="cb44-278"><a href="#cb44-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-281"><a href="#cb44-281" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-282"><a href="#cb44-282" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(diagnostics); <span class="fu">nrow</span>(prod.trimmed)</span>
<span id="cb44-283"><a href="#cb44-283" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-284"><a href="#cb44-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-285"><a href="#cb44-285" aria-hidden="true" tabindex="-1"></a>Reporting how many observations came out is not optional. A reader needs to know whether the robustness check dropped three cases or three hundred.</span>
<span id="cb44-286"><a href="#cb44-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-287"><a href="#cb44-287" aria-hidden="true" tabindex="-1"></a><span class="fu">## Step 6: compare original "final" model, robust model, and trimmed model</span></span>
<span id="cb44-288"><a href="#cb44-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-289"><a href="#cb44-289" aria-hidden="true" tabindex="-1"></a>This is the sensitivity analysis.</span>
<span id="cb44-290"><a href="#cb44-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-293"><a href="#cb44-293" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb44-294"><a href="#cb44-294" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb44-295"><a href="#cb44-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-296"><a href="#cb44-296" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modelsummary)</span>
<span id="cb44-297"><a href="#cb44-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-298"><a href="#cb44-298" aria-hidden="true" tabindex="-1"></a>models <span class="ot">&lt;-</span> <span class="fu">list</span>(model<span class="fl">.5</span>, model.trimmed)</span>
<span id="cb44-299"><a href="#cb44-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-300"><a href="#cb44-300" aria-hidden="true" tabindex="-1"></a><span class="fu">modelsummary</span>(models, <span class="at">output =</span> <span class="st">"markdown"</span>)</span>
<span id="cb44-301"><a href="#cb44-301" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb44-302"><a href="#cb44-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-303"><a href="#cb44-303" aria-hidden="true" tabindex="-1"></a>This is the part that actually settles the question. Rather than arguing about whether assumptions hold, refit under different assumptions and compare.</span>
<span id="cb44-304"><a href="#cb44-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-305"><a href="#cb44-305" aria-hidden="true" tabindex="-1"></a>Read across the columns for the coefficient you care about most. If it holds steady in magnitude, direction, and significance, you have an answer to the reviewer worried about your residuals: the conclusion does not depend on the assumption in question. That is a much stronger response than asserting the assumption was met.</span>
<span id="cb44-306"><a href="#cb44-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-307"><a href="#cb44-307" aria-hidden="true" tabindex="-1"></a><span class="fu">## Writing it up</span></span>
<span id="cb44-308"><a href="#cb44-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-309"><a href="#cb44-309" aria-hidden="true" tabindex="-1"></a>A sensitivity analysis paragraph belongs in nearly every quantitative paper, and it has a predictable shape. State which diagnostics you examined. Report what they showed, honestly, including the parts that looked imperfect. Describe the robustness checks you ran. Then state whether your substantive conclusion held.</span>
<span id="cb44-310"><a href="#cb44-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-311"><a href="#cb44-311" aria-hidden="true" tabindex="-1"></a>The version that reads as defensive says the assumptions were met and moves on. The version that reads as competent concedes that residuals showed mild skew and a handful of state-years exceeded the conventional Cook's distance threshold, then reports that the coefficients changed negligibly under robust estimation and with those cases excluded. The second is more honest and considerably more persuasive.</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">Applied Multilevel Modeling in R</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">Built with <a href="https://quarto.org">Quarto</a></div>
  </div>
</footer>


</body></html>